{
 "title": "Netflow overview",
 "tags": [ "neflow-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"obi_network_flow_bytes_total|network_io_by_flow_bytes|beyla_network_flow_bytes_total\"}, job)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"obi_network_flow_bytes_total|network_io_by_flow_bytes|beyla_network_flow_bytes_total\",job=~\"$job\"}, job)"
   },
   { "name": "adhoc", "label": "Ad hoc filters" }
  ]
 },
 "panels": [
  {
   "title": "Traffic rate",
   "type": "timeseries",
   "description": "Total observed traffic, aggregated by collecting device",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__rate_interval])) by (job)\nor\nsum(irate(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__rate_interval])) by (job)\nor\nsum(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}) by (device_name)",
     "legendFormat": "{{job}}: Traffic rate"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Known sources, destinations, endpoints and total overall traffic",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "count(count(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}) by (job))\nor\ncount(count(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}) by (device_name))\nor\ncount(count(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}) by (job))",
     "legendFormat": "Collecting devices"
    },
    {
     "expr": "count(count(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}) by (src_cidr))\nor\ncount(count(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}) by (network_local_address))\nor\ncount(count(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}) by (src_cidr))",
     "legendFormat": "Sources"
    },
    {
     "expr": "count(count(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}) by (dst_cidr))\nor\ncount(count(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}) by (network_peer_address))\nor\ncount(count(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}) by (dst_cidr))",
     "legendFormat": "Destinations"
    },
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range]))\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range]))\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Total observed traffic"
    }
   ]
  },
  {
   "title": "Top sources",
   "type": "table",
   "description": "Source adresses ordered by observed traffic during the time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range]))\nor\ntopk(5,increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range]))\nor\ntopk(5,network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"})",
     "legendFormat": "{{job}}: Top sources"
    }
   ]
  },
  {
   "title": "Top destinations",
   "type": "table",
   "description": "Destination adresses ordered by observed traffic during the time range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range]))\nor\ntopk(5,increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range]))\nor\ntopk(5,network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"})",
     "legendFormat": "{{job}}: Top sources"
    }
   ]
  },
  { "title": "Conversations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Conversation total bytes",
   "type": "table",
   "description": "Source/Destination pairs and their total traffic across all dimensions. Ordered by total traffic during selected time range",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_cidr,dst_cidr)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_cidr,dst_cidr)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_local_address,network_peer_address)",
     "legendFormat": "{{job}}: Conversation total bytes"
    }
   ]
  },
  {
   "title": "Conversation traffic over time",
   "type": "timeseries",
   "description": "Traffic distribution of source/destination pairs over time",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__rate_interval])) by (src_cidr,dst_cidr)\nor\nsum(irate(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__rate_interval])) by (src_cidr,dst_cidr)\nor\nsum(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}) by (network_local_address,network_peer_address,device_name) / 60",
     "legendFormat": "{{src_cidr}} -> {{ dst_cidr }} // {{job}}"
    }
   ]
  },
  {
   "title": "Breakdown by source/destination pair",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_cidr,dst_cidr,job)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_cidr,dst_cidr,job)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_local_address, network_peer_address, device_name)",
     "legendFormat": "{{src_cidr}} -> {{ dst_cidr }} // {{job}}"
    }
   ]
  },
  { "title": "Protocols", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total bytes",
   "type": "table",
   "description": "List of protocols and the total amount of observed traffic during the selected time range",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_protocol_name)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_protocol_name)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_protocol_name)",
     "legendFormat": "{{network_protocol_name}}"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "piechart",
   "description": "Distribution of protocols and the total amount of observed traffic during the selected time range",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_protocol_name)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_protocol_name)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}[$__range])) by (network_protocol_name)",
     "legendFormat": "{{network_protocol_name}}"
    }
   ]
  },
  {
   "title": "Protocol traffic over time",
   "type": "timeseries",
   "description": "Protocols and the amount of observed traffic over the selected time range",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__interval])) by (network_protocol_name)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__interval])) by (network_protocol_name)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}[$__interval])) by (network_protocol_name)",
     "legendFormat": "{{network_protocol_name}}"
    }
   ]
  },
  { "title": "Geographic data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Top destination",
   "type": "geomap",
   "description": "Geographic heatmap showing the total amount of traffic to specific countries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (dst_country)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (dst_country)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\",network_peer_country!=\"Private IP\"}[$__range])) by (network_peer_country)",
     "legendFormat": "{{job}}: Traffic by destination"
    }
   ]
  },
  {
   "title": "Traffic by destination",
   "type": "table",
   "description": "Total traffic to specific countries during the selected time range",
   "gridPos": { "h": 13, "w": 4, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (dst_country)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (dst_country)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\",network_peer_country!=\"Private IP\"}[$__range])) by (network_peer_country)",
     "legendFormat": "{{job}}: Traffic by destination"
    }
   ]
  },
  {
   "title": "Top sources",
   "type": "geomap",
   "description": "Geographic heatmap showing the total amount of traffic from specific countries",
   "gridPos": { "h": 13, "w": 8, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_country)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_country)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\",network_local_country!=\"Private IP\"}[$__range])) by (network_local_country)",
     "legendFormat": "{{job}}: Traffic by Source"
    }
   ]
  },
  {
   "title": "Traffic by source",
   "type": "table",
   "description": "Total traffic from specific countries during the selected time range",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_country)\nor\nsum(increase(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__range])) by (src_country)\nor\nsum(sum_over_time(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\",network_local_country!=\"Private IP\"}[$__range])) by (network_local_country)",
     "legendFormat": "{{job}}: Traffic by Source"
    }
   ]
  },
  { "title": "Collector details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Collector logs",
   "type": "logs",
   "description": "Logs of the ktranslate instance",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "{service_name=\"integrations/ktranslate-netflow\"}\n"
    }
   ]
  },
  {
   "title": "Devices sending flows",
   "type": "stat",
   "description": "Protocol statistics per device sending them",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(beyla_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__rate_interval])) by (job)\nor\nsum(irate(obi_network_flow_bytes_total{job=~\"$job\",job=~\"$job\"}[$__rate_interval])) by (job)\nor\nsum(network_io_by_flow_bytes{job=~\"$job\",job=~\"$job\"}) by (device_name)",
     "legendFormat": "{{job}}: Traffic rate"
    }
   ]
  }
 ]
}