{
 "title": "Python  runtime metrics",
 "description": "Python runtime metrics",
 "tags": [ "python-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(python_info, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(python_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "GC stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GC collections",
   "type": "graph",
   "description": "The rate of GC collections, by generation",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (job, generation) (rate(python_gc_collections_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ job }} (generation {{ generation }})"
    }
   ]
  },
  {
   "title": "GC objects collected",
   "type": "graph",
   "description": "The amount of object collected during GC, by generation",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, generation) (rate(python_gc_objects_collected_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ job }} (generation {{ generation }})"
    }
   ]
  },
  {
   "title": "Uncollectable GC objects",
   "type": "graph",
   "description": "The amount of uncollectable GC objects, by generation",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, generation) (rate(python_gc_objects_uncollectable_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ job }} (generation {{ generation }})"
    }
   ]
  },
  { "title": "Process stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Total user and system CPU time spent in seconds per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(process_cpu_seconds_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory set size",
   "type": "graph",
   "description": "The size of virtual and resident memory sets",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ job }} (virtual)"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ job }} (resident)"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "description": "Current and maximum amount of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ job }} (open)"
    },
    {
     "expr": "process_max_fds{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ job }} (max)"
    }
   ]
  }
 ]
}