{
 "title": "Cloudflare zone overview",
 "tags": [ "cloudflare-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cloudflare_zone_requests_total{job=\"integrations/cloudflare\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cloudflare_zone_requests_total{job=\"integrations/cloudflare\",job=~\"$job\"}, cluster)"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(cloudflare_zone_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\"}, zone)"
   },
   {
    "name": "script_name",
    "label": "Script",
    "query": "label_values(cloudflare_zone_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\"}, script_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cloudflare_zone_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\"}, instance)"
   },
   {
    "name": "geo_metric",
    "label": "Geomap metric",
    "query": "cloudflare_zone_requests_country : cloudflare_zone_requests_country,cloudflare_zone_bandwidth_country : cloudflare_zone_bandwidth_country,cloudflare_zone_threats_country : cloudflare_zone_threats_country"
   }
  ]
 },
 "panels": [
  { "title": "Zone overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Pool status",
   "type": "table",
   "description": "A table view of the pools in your zone showing their health and rate of requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "cloudflare_zone_pool_health_status{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}"
    },
    {
     "expr": "rate(cloudflare_zone_pool_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "The rate at which requests to the zone occur.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Cached requests / $__interval",
   "type": "timeseries",
   "description": "The percentage of requests to the zone that are cached.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_cached{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval) / increase(cloudflare_zone_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Threats / $__interval",
   "type": "timeseries",
   "description": "The number of threats that have targeted the zone.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_threats_total{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Bandwidth rate",
   "type": "timeseries",
   "description": "The rate at which all bandwidth in the zone occurs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_bandwidth_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Bandwidth type / $__interval",
   "type": "timeseries",
   "description": "The amount of cached and encrypted bandwidth that occurs in the zone.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_bandwidth_ssl_encrypted{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{zone}} - SSL encrypted"
    },
    {
     "expr": "increase(cloudflare_zone_bandwidth_cached{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{zone}} - Cached"
    }
   ]
  },
  {
   "title": "Bandwidth content type / $__interval",
   "type": "timeseries",
   "description": "The content types that bandwidth is being used for in the zone.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_bandwidth_content_type{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ content_type }}"
    }
   ]
  },
  {
   "title": "Browser page views / $__interval",
   "type": "timeseries",
   "description": "The number of zone views by browser family.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_browser_map_page_views_count{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{zone}} - {{family}}"
    }
   ]
  },
  {
   "title": "Unique page views / $__interval",
   "type": "timeseries",
   "description": "The number of unique and total page views.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_uniques_total{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{zone}} - unique"
    },
    {
     "expr": "increase(cloudflare_zone_pageviews_total{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval) - increase(cloudflare_zone_uniques_total{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{zone}} - non-unique"
    }
   ]
  },
  {
   "title": "Request HTTP status / $__interval",
   "type": "timeseries",
   "description": "The number of different HTTP status codes used for requests in the zone.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_status{job=~\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{zone}} - {{status}}"
    }
   ]
  },
  {
   "title": "Colocation requests",
   "type": "table",
   "description": "The different colocations being used by the zone and their request rates.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(cloudflare_zone_colocation_requests_total{job=\"integrations/cloudflare\",job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  }
 ]
}