{
 "title": "OpenLDAP overview",
 "tags": [ "openldap" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(openldap_dial{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(openldap_dial{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The total time since the LDAP server was last started.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Uptime,cn=Time,cn=Monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Referrals",
   "type": "stat",
   "description": "The number of LDAP referrals.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Referrals,cn=Statistics,cn=Monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "OpenLDAP alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 } },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "Connections / $__interval",
   "type": "timeseries",
   "description": "The increase of new LDAP connections over time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_monitor_counter_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Current,cn=Connections,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiters",
   "type": "timeseries",
   "description": "The number of read and write waiters.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Read,cn=Waiters,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Read"
    },
    {
     "expr": "openldap_monitor_counter_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Write,cn=Waiters,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Write"
    }
   ]
  },
  {
   "title": "Network connectivity / $__interval",
   "type": "timeseries",
   "description": "The LDAP network connection attempts over time.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_dial{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 14 } },
  {
   "title": "Directory entries / $__interval",
   "type": "timeseries",
   "description": "The total increase of new directory entries added over time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_monitor_counter_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Entries,cn=Statistics,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PDU processed / $__interval",
   "type": "timeseries",
   "description": "The number of LDAP Protocol Data Units (PDUs) processed over time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_monitor_counter_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=PDU,cn=Statistics,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authentication attempts / $__interval",
   "type": "timeseries",
   "description": "The total increase of authentication attempts over time.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_bind{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Core operations / $__interval",
   "type": "timeseries",
   "description": "The key LDAP operations.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Add,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Add"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Bind,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Bind"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Modify,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Modify"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Search,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Search"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Delete,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Delete"
    }
   ]
  },
  {
   "title": "Auxiliary operations / $__interval",
   "type": "timeseries",
   "description": "The less frequent but important LDAP operations.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Abandon,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Abandon"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Compare,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Compare"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Unbind,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Unbind"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Extended,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Extended"
    },
    {
     "expr": "increase(openldap_monitor_operation{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Modrdn,cn=Operations,cn=Monitor\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Modrdn"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Primary thread activity",
   "type": "timeseries",
   "description": "The active, open, and maximum threads in the LDAP server.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Open,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Open"
    },
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Active,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Active"
    },
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Max,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Max"
    }
   ]
  },
  {
   "title": "Thread queue management",
   "type": "timeseries",
   "description": "The LDAP server's thread backlog and pending status.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Starting,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Starting"
    },
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Pending,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Pending"
    },
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Max Pending,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Max Pending"
    },
    {
     "expr": "openldap_monitored_object{job=~\"$job\",instance=~\"$instance\", dn=\"cn=Backload,cn=Threads,cn=Monitor\"}",
     "legendFormat": "{{instance}} - Backload"
    }
   ]
  }
 ]
}