{
 "title": "JVM overview",
 "tags": [
  "java",
  "jvm",
  "prometheus_client"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(jvm_memory_used_bytes{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Memory used(heap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    }
   ]
  },
  {
   "title": "Memory used(nonheap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_threads_current{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "stat",
   "description": "The number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_classes_loaded{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Classes loaded"
    }
   ]
  },
  { "title": "Process overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Process start time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_start_time_seconds{job=~\"$job\",instance=~\"$instance\"} * 1000\n)",
     "legendFormat": "{{instance}}: Process start time"
    }
   ]
  },
  {
   "type": "text",
   "description": "Load average: Signal not found.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } }
  },
  {
   "title": "CPU usage (process)",
   "type": "timeseries",
   "description": "Process CPU usage.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (process)"
    }
   ]
  },
  {
   "title": "Process memory used (rss)",
   "type": "timeseries",
   "description": "Process resident memory size in bytes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process memory used (rss)"
    }
   ]
  },
  {
   "title": "Process files open",
   "type": "timeseries",
   "description": "Process files opened.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_open_fds{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files open"
    },
    {
     "expr": "avg by (job,instance) (\n  process_max_fds{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files max"
    }
   ]
  },
  { "title": "JVM memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "JVM memory used(heap)",
   "type": "timeseries",
   "description": "The used space is the amount of memory that is currently occupied by Java objects.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(heap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_committed_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(heap)"
    }
   ]
  },
  {
   "title": "JVM memory used(nonheap)",
   "type": "timeseries",
   "description": "The amount of memory that is currently in non-heap.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_committed_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(nonheap)"
    }
   ]
  },
  { "title": "JVM garbage collection", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Eden Space (used)",
   "type": "timeseries",
   "description": "Memory used for G1 Eden Space Collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_used_bytes{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (used)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_max_bytes{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_committed_bytes{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (committed)"
    }
   ]
  },
  {
   "title": "Survival space (used)",
   "type": "timeseries",
   "description": "Memory used for Survival collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_used_bytes{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (used)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_max_bytes{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"} != -1\n)",
     "legendFormat": "{{job}}: Survival space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_committed_bytes{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (committed)"
    }
   ]
  },
  {
   "title": "Tenured space (used)",
   "type": "timeseries",
   "description": "Memory used for Tenured(Old Gen) collection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_used_bytes{pool=\"PS Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_pool_used_bytes{pool=\"PS Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1",
     "legendFormat": "{{job}}: Tenured space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_committed_bytes{pool=\"PS Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (committed)"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg by (job,gc) (\n  rate(jvm_gc_collection_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "avg by (job, gc) (\n  rate(jvm_gc_collection_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n  /\n  rate(jvm_gc_collection_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ job }}: {{ gc }} (avg)"
    }
   ]
  },
  {
   "title": "Allocated/promoted",
   "type": "timeseries",
   "description": "'Allocated' is the size increase of the young generation memory pool after one GC and before the next. It reflects minor GC.\n'Promoted' is the size increase of the old generation memory pool after GC. It reflects full GC.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  rate(jvm_memory_pool_allocated_bytes_total{pool=~\"(G1 |PS )?Eden Space\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Allocated (bytes)"
    }
   ]
  },
  { "title": "JVM threads", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_threads_current{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_daemon{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (daemon)"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_peak{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (peak)"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_deadlocked{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (deadlocked)"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "timeseries",
   "description": "Threads by current state.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by (state, job) (jvm_threads_state{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "JVM buffers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 53 } },
  {
   "title": "Direct buffer used bytes",
   "type": "timeseries",
   "description": "Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_pool_used_bytes{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer used bytes"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_pool_capacity_bytes{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer capacity"
    }
   ]
  },
  {
   "title": "Mapped buffer used",
   "type": "timeseries",
   "description": "The mapped buffer pool is used for its FileChannel instances.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_pool_used_bytes{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer used"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_pool_capacity_bytes{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer capacity"
    }
   ]
  }
 ]
}