{
 "title": "Redis Enterprise databases",
 "tags": [ "redis-enterprise-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(node_up{}, job)" },
   {
    "name": "redis_cluster",
    "label": "Redis cluster",
    "query": "label_values(node_up{job=~\"$job\"}, redis_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "node", "label": "Node", "query": "label_values(node_up, node)" },
   { "name": "bdb", "label": "Database", "query": "label_values(bdb_up, bdb)" }
  ]
 },
 "panels": [
  { "title": "Database overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Database up",
   "type": "timeseries",
   "description": "Displays up/down status for the selected database.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bdb_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Shards up",
   "type": "bargauge",
   "description": "Displays up/down status for each shard related to the database.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - redis: {{ redis }}"
    }
   ]
  },
  {
   "title": "Nodes up",
   "type": "timeseries",
   "description": "Displays up/down status for each node related to the database.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Database metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "Database operations",
   "type": "timeseries",
   "description": "Rate of read and write requests.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bdb_read_req{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - read"
    },
    {
     "expr": "bdb_write_req{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - write"
    }
   ]
  },
  {
   "title": "Database latency",
   "type": "timeseries",
   "description": "Average latency for read and write requests.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bdb_avg_read_latency{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - read"
    },
    {
     "expr": "bdb_avg_write_latency{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - write"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "description": "Number of client connections.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bdb_conns{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database key count",
   "type": "timeseries",
   "description": "Number of keys in the database.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bdb_no_of_keys{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database cache hit ratio",
   "type": "timeseries",
   "description": "Calculated cache hit rate for the database.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(bdb_read_hits{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}) by (job, redis_cluster, bdb) / clamp_min(sum(bdb_read_hits{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}) by (job, redis_cluster, bdb) + sum(bdb_read_misses{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}) by (job, redis_cluster, bdb), 1) * 100",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database memory utilization",
   "type": "timeseries",
   "description": "Calculated memory utilization % of the database compared to the limit.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bdb_used_memory{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"} / bdb_memory_limit{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"} * 100",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database evictions vs expired objects",
   "type": "timeseries",
   "description": "Number of evicted and expired objects from the database.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "bdb_evicted_objects{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - evicted"
    },
    {
     "expr": "bdb_expired_objects{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - expired"
    }
   ]
  },
  {
   "title": "Database memory fragmentation ratio",
   "type": "timeseries",
   "description": "RAM fragmentation ratio between RSS and allocated RAM.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bdb_mem_frag_ratio{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database LUA heap size",
   "type": "timeseries",
   "description": "LUA scripting heap size.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bdb_mem_size_lua{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database network ingress",
   "type": "timeseries",
   "description": "Rate of incoming network traffic.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "bdb_ingress_bytes{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "Database network egress",
   "type": "timeseries",
   "description": "Rate of outgoing network traffic.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "bdb_egress_bytes{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  { "title": "Active-Active", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 32 } },
  {
   "title": "Sync status",
   "type": "timeseries",
   "description": "Sync status for CRDB traffic (0=in-sync, 1=syncing, 2=out of sync).",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_status{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }} - repl_id: {{ crdt_replica_id }}"
    }
   ]
  },
  {
   "title": "Local lag",
   "type": "timeseries",
   "description": "Lag between source and destination for CRDB traffic.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_local_ingress_lag_time{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "CRDB ingress compressed",
   "type": "timeseries",
   "description": "Rate of compressed network traffic to the CRDB.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "bdb_crdt_syncer_ingress_bytes{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  },
  {
   "title": "CRDB ingress decompressed",
   "type": "timeseries",
   "description": "Rate of decompressed network traffic to the CRDB.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "bdb_crdt_ingress_bytes_decompressed{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", bdb=~\"$bdb\"}",
     "legendFormat": "{{ bdb }}"
    }
   ]
  }
 ]
}