{
 "title": "Redis Enterprise nodes",
 "tags": [ "redis-enterprise-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(node_up{}, job)" },
   {
    "name": "redis_cluster",
    "label": "Redis cluster",
    "query": "label_values(node_up{job=~\"$job\"}, redis_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "node", "label": "Node", "query": "label_values(node_up, node)" }
  ]
 },
 "panels": [
  { "title": "Node overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Nodes up",
   "type": "timeseries",
   "description": "Displays up/down status for the selected node.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Database up",
   "type": "bargauge",
   "description": "Displays up/down status for the databases of the selected node(s).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Shards up",
   "type": "bargauge",
   "description": "Displays up/down status for the shards on the selected node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "redis: {{ redis }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Inventory of the Redis Enterprise node(s).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(redis_used_memory{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, node, job) / clamp_min(sum(node_available_memory{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, node, job), 1)) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "node_up{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Node metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "Node memory utilization",
   "type": "timeseries",
   "description": "Memory utilization % for the selected node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(redis_used_memory{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, node, job) / clamp_min(sum(node_available_memory{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, node, job), 1)) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for the selected node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_cpu_system{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"} * 100",
     "legendFormat": "{{ node }} - system"
    },
    {
     "expr": "node_cpu_user{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"} * 100",
     "legendFormat": "{{ node }} - user"
    }
   ]
  },
  {
   "title": "Node network ingress",
   "type": "timeseries",
   "description": "Network ingress for the selected node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "node_ingress_bytes{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node network egress",
   "type": "timeseries",
   "description": "Network egress for the selected node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "node_egress_bytes{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node requests",
   "type": "timeseries",
   "description": "Total endpoint request rate for the selected node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_total_req{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node client connections",
   "type": "timeseries",
   "description": "Number of client connections to the selected node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_conns{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node average latency",
   "type": "timeseries",
   "description": "Average latency for the selected node.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_avg_latency{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node ephemeral free storage",
   "type": "timeseries",
   "description": "Ephemeral storage available for the selected node.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_ephemeral_storage_free{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node persistent free storage",
   "type": "timeseries",
   "description": "Persistent storage available for the selected node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_persistent_storage_free{job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}