{
 "title": "Redis Enterprise overview",
 "tags": [ "redis-enterprise-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_up{job=\"integrations/redis-enterprise\"}, job)"
   },
   {
    "name": "redis_cluster",
    "label": "Redis cluster",
    "query": "label_values(node_up{job=\"integrations/redis-enterprise\",job=~\"$job\"}, redis_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_up{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Nodes up",
   "type": "bargauge",
   "description": "Up/down status for each node in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_up{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ redis_cluster }} - {{ node }}"
    }
   ]
  },
  {
   "title": "Databases up",
   "type": "bargauge",
   "description": "Up/down status for each database in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bdb_up{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ redis_cluster }} - bdb={{ bdb }}"
    }
   ]
  },
  {
   "title": "Shards up",
   "type": "bargauge",
   "description": "Up/down status for each shard in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ redis_cluster }} - redis: {{ redis }}"
    }
   ]
  },
  {
   "title": "Cluster total requests",
   "type": "timeseries",
   "description": "Total requests handled by endpoints aggregated across all nodes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_total_req{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, job)",
     "legendFormat": "{{ redis_cluster }}"
    }
   ]
  },
  {
   "title": "Cluster total memory used",
   "type": "timeseries",
   "description": "Total memory used by each database in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(bdb_used_memory{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (job, bdb, redis_cluster)",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Cluster total connections",
   "type": "timeseries",
   "description": "Total connections to each database in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(bdb_conns{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (bdb, redis_cluster, job)",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Cluster total keys",
   "type": "timeseries",
   "description": "Total cluster key count for each database in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(bdb_no_of_keys{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, bdb, job)",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Cluster cache hit ratio",
   "type": "timeseries",
   "description": "Ratio of database cache key hits against hits and misses.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bdb_read_hits{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"} / (clamp_min(bdb_read_hits{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"} + bdb_read_misses{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}, 1)) * 100",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Cluster evictions vs expired objects",
   "type": "timeseries",
   "description": "Sum of key evictions and expirations in the cluster by database.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "bdb_evicted_objects{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }} - evicted"
    },
    {
     "expr": "bdb_expired_objects{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }} - expired"
    }
   ]
  },
  { "title": "Nodes KPIs", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 19 } },
  {
   "title": "Node requests",
   "type": "timeseries",
   "description": "Endpoint request rate for each node in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_total_req{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ redis_cluster }} - node: {{ node }}"
    }
   ]
  },
  {
   "title": "Node average latency",
   "type": "timeseries",
   "description": "Average latency for each node in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_avg_latency{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ redis_cluster }} - node: {{ node }}"
    }
   ]
  },
  {
   "title": "Node memory utilization",
   "type": "timeseries",
   "description": "Memory utilization % for each node in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(redis_used_memory{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, node, job) / clamp_min(sum(node_available_memory{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, node, job), 1)) * 100",
     "legendFormat": "{{ redis_cluster }} - node: {{ node }}"
    }
   ]
  },
  {
   "title": "Node CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for each node in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_cpu_system{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"} * 100",
     "legendFormat": "node: {{ node }} - system"
    },
    {
     "expr": "node_cpu_user{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"} * 100",
     "legendFormat": "node: {{ node }} - user"
    }
   ]
  },
  { "title": "Database KPIs", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 26 } },
  {
   "title": "Database operations",
   "type": "timeseries",
   "description": "Rate of requests handled by each database in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(bdb_instantaneous_ops_per_sec{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, bdb, job)",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Database average latency",
   "type": "timeseries",
   "description": "Average latency for each database in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(bdb_avg_latency{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (redis_cluster, job, bdb)",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Database memory utilization",
   "type": "timeseries",
   "description": "Calculated memory utilization % for each database in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(bdb_used_memory{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (job, redis_cluster, bdb) / clamp_min(sum(bdb_memory_limit{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (job, redis_cluster, bdb), 1) * 100",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  },
  {
   "title": "Database cache hit ratio",
   "type": "timeseries",
   "description": "Calculated cache hit rate for each database in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(bdb_read_hits{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (job, redis_cluster, bdb) / clamp_min(sum(bdb_read_hits{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (job, redis_cluster, bdb) + sum(bdb_read_misses{job=\"integrations/redis-enterprise\",job=~\"$job\",redis_cluster=~\"$redis_cluster\",instance=~\"$instance\"}) by (job, redis_cluster, bdb), 1) * 100",
     "legendFormat": "{{ redis_cluster }} - db: {{ bdb }}"
    }
   ]
  }
 ]
}