{
 "title": "Azure Virtual network",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(azure_microsoft_network_loadbalancers_bytecount_total_bytes{job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "ResourceGroup",
    "query": "label_values(azure_microsoft_network_loadbalancers_bytecount_total_bytes{job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "SubscriptionName",
    "query": "label_values(azure_microsoft_network_loadbalancers_bytecount_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   },
   {
    "name": "resourceName",
    "label": "ResourceName",
    "query": "label_values(azure_microsoft_network_loadbalancers_bytecount_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}, resourceName)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Current DDoS status",
   "type": "stat",
   "description": "Is the system currently under DDoS attack or not.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "\n  avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_ifunderddosattack_count_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)\nOR on() vector(0)",
     "legendFormat": "{{resourceName}}: Current DDoS status"
    }
   ]
  },
  {
   "title": "Round trip time for pings to a VM",
   "type": "timeseries",
   "description": "Round trip time for Pings sent to a destination VM",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_pingmeshaveragerountdripms_milliseconds_average{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Round trip time for pings to a VM"
    }
   ]
  },
  {
   "title": "DDoS trigger packets by type",
   "type": "timeseries",
   "description": "Total packet count contributing to DDoS mitigation being triggered, grouped by protocol.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_ddostriggersynpackets_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "SYN"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_ddostriggertcppackets_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "TCP"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_ddostriggerudppackets_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "UDP"
    }
   ]
  },
  { "title": "Bytes", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 7 } },
  {
   "title": "Bytes by DDoS action",
   "type": "timeseries",
   "description": "Total byte count handled by DDoS mitigation, grouped by action.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_bytesdroppedddos_bytespersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "Dropped"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_bytesforwardedddos_bytespersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Bytes dropped in DDoS by protocol",
   "type": "timeseries",
   "description": "Total byte count dropped by DDoS mitigation, grouped by protocol.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_tcpbytesdroppedddos_bytespersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "TCP Dropped"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_udpbytesdroppedddos_bytespersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "UDP Dropped"
    }
   ]
  },
  {
   "title": "Bytes forwarded in DDoS by protocol",
   "type": "timeseries",
   "description": "Total byte count forwarded by DDoS mitigation, grouped by protocol.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_tcpbytesforwardedddos_bytespersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "TCP forwarded"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_udpbytesforwardedddos_bytespersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "UDP Forwarded"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 16 } },
  {
   "title": "Packets by DDoS action",
   "type": "timeseries",
   "description": "Total packet per second count handled by DDoS mitigation, grouped by action.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_packetsdroppedddos_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "Dropped"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_packetsforwardedddos_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "Forwarded"
    }
   ]
  },
  {
   "title": "Packets dropped in DDoS by protocol",
   "type": "timeseries",
   "description": "Total packet per second count dropped by DDoS mitigation, grouped by protocol.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_tcppacketsdroppedddos_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "TCP Dropped"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_udppacketsdroppedddos_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "UDP Dropped"
    }
   ]
  },
  {
   "title": "Packets forwarded in DDoS by protocol",
   "type": "timeseries",
   "description": "Total packet per second count forwarded by DDoS mitigation, grouped by protocol.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_tcppacketsforwardedddos_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "TCP Forwarded"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_network_virtualnetworks_udppacketsforwardedddos_countpersecond_maximum{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "UDP Forwarded"
    }
   ]
  }
 ]
}