{
 "title": "Azure Blob storage",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"azure_microsoft_storage_storageaccounts_blobservices_blobcount_average_count\",job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "ResourceGroup",
    "query": "label_values({__name__=~\"azure_microsoft_storage_storageaccounts_blobservices_blobcount_average_count\",job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "SubscriptionName",
    "query": "label_values({__name__=~\"azure_microsoft_storage_storageaccounts_blobservices_blobcount_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   },
   {
    "name": "resourceName",
    "label": "Bucket Name",
    "query": "label_values({__name__=~\"azure_microsoft_storage_storageaccounts_blobservices_blobcount_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}, resourceName)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Bucket count",
   "type": "stat",
   "description": "Number of storage buckets.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "count(sum by (resourceName) (azure_microsoft_storage_storageaccounts_blobservices_containercount_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}))",
     "legendFormat": "{{resourceName}}: Bucket count"
    }
   ]
  },
  {
   "title": "Object count",
   "type": "stat",
   "description": "Number of objects stored.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(azure_microsoft_storage_storageaccounts_blobservices_blobcount_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{resourceName}}: Object count"
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "stat",
   "description": "Total bytes stored",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(azure_microsoft_storage_storageaccounts_blobservices_blobcapacity_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])) +\nsum(max_over_time(azure_microsoft_storage_storageaccounts_blobservices_indexcapacity_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range]))\n",
     "legendFormat": "{{resourceName}}: Total bytes"
    }
   ]
  },
  {
   "title": "Top 5 Buckets - Network Throughput",
   "type": "table",
   "description": "Total network throughput in bits for the selected timerange",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_ingress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range]))\n+ sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_egress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])))\n",
     "legendFormat": "{{resourceName}}: Network bits throughput"
    },
    {
     "expr": "sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_ingress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])) and topk(5, sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_ingress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range]))\n+ sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_egress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])))\n",
     "legendFormat": "{{resourceName}}: Network bits received"
    },
    {
     "expr": "sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_egress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])) and topk(5, sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_ingress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range]))\n+ sum by (job, resourceName) (sum_over_time(azure_microsoft_storage_storageaccounts_blobservices_egress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])))\n",
     "legendFormat": "{{resourceName}}: Network bits transmitted"
    }
   ]
  },
  {
   "title": "Top 5 Buckets - Object Count",
   "type": "table",
   "description": "Number of objects stored.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,resourceGroup,subscriptionName,resourceName) (\n  max_over_time(azure_microsoft_storage_storageaccounts_blobservices_blobcount_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])\n)\n)",
     "legendFormat": "{{resourceName}}: Top 5 buckets - object count"
    }
   ]
  },
  {
   "title": "Top 5 Buckets - Total Bytes",
   "type": "table",
   "description": "Total bytes stored",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,resourceGroup,subscriptionName,resourceName) (\n  max_over_time(azure_microsoft_storage_storageaccounts_blobservices_blobcapacity_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__range])\n)\n)",
     "legendFormat": "{{resourceName}}: Top 5 buckets - total bytes"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 15 } },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Percent availability by API request.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_storage_storageaccounts_blobservices_availability_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Availability"
    }
   ]
  },
  {
   "title": "API requests by type",
   "type": "timeseries",
   "description": "Count of all API requests",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (dimensionApiname) (azure_microsoft_storage_storageaccounts_blobservices_transactions_total_count{dimensionApiname!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})\nor\nsum by (dimension_ApiName) (azure_microsoft_storage_storageaccounts_blobservices_transactions_total_count{dimension_ApiName!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{dimensionApiname}}"
    }
   ]
  },
  {
   "title": "API error rate by type",
   "type": "timeseries",
   "description": "Percentage of api request failure by type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (dimensionApiname) (azure_microsoft_storage_storageaccounts_blobservices_transactions_total_count{dimensionApiname!=\"\",dimensionResponseType!=\"Success\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}) / sum by (dimensionApiname) (azure_microsoft_storage_storageaccounts_blobservices_transactions_total_count{dimensionApiname!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})\nor\nsum by (dimension_ApiName) (azure_microsoft_storage_storageaccounts_blobservices_transactions_total_count{dimension_ApiName!=\"\",dimension_responsetype!=\"Success\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}) / sum by (dimension_ApiName) (azure_microsoft_storage_storageaccounts_blobservices_transactions_total_count{dimension_ApiName!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{dimensionApiname}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 40 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "received (avg): Total bytes received over the network  \n\ntransmitted (avg): Total bytes sent over the network",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  rate(azure_microsoft_storage_storageaccounts_blobservices_ingress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__rate_interval])\n)",
     "legendFormat": "{{resourceName}}: received"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  rate(azure_microsoft_storage_storageaccounts_blobservices_egress_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__rate_interval])\n)",
     "legendFormat": "{{resourceName}}: transmitted"
    }
   ]
  }
 ]
}