{
 "title": "Azure Elastic pool",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_elasticpools_sessions_count_average_count\",job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "ResourceGroup",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_elasticpools_sessions_count_average_count\",job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "SubscriptionName",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_elasticpools_sessions_count_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   },
   {
    "name": "resourceName",
    "label": "ResourceName",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_elasticpools_sessions_count_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}, resourceName)"
   }
  ]
 },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Elastic pool storage",
   "type": "table",
   "description": "Storage overview per elasticpool.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_allocated_data_storage_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Allocated"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_storage_used_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Used"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_storage_limit_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Limit"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization per elastic pool.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_cpu_percent_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: CPU utilization"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Memory utilization per elastic pool.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_sql_instance_memory_percent_maximum_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Memory utilization"
    }
   ]
  },
  {
   "title": "eDTU utilization",
   "type": "timeseries",
   "description": "eDTU utilization per elastic pool.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_edtu_used_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: eDTU utilization"
    }
   ]
  },
  {
   "title": "Concurrent sessions",
   "type": "timeseries",
   "description": "Average sessions per elastic pool.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_sql_servers_elasticpools_sessions_count_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}: Concurrent sessions"
    }
   ]
  }
 ]
}