{
 "title": "Azure Virtual Machines",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count\",job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "Group",
    "query": "label_values({__name__=~\"azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count\",job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "Subscription",
    "query": "label_values({__name__=~\"azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   },
   {
    "name": "resourceName",
    "label": "Instance",
    "query": "label_values({__name__=~\"azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}, resourceName)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Instance count",
   "type": "stat",
   "description": "Number of VM instances",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by (resourceName) (azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}))"
    }
   ]
  },
  {
   "title": "VM Availability",
   "type": "table",
   "description": "VM Availability (avg): Measure of availability of virtual machines  \n",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_vmavailabilitymetric_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by CPU utilitization",
   "type": "table",
   "description": "Top 5 Instances by CPU utilitization (avg): Fractional utilization of allocated CPU on an instance  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_percentage_cpu_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by Less available memory",
   "type": "table",
   "description": "Top 5 Instances by Less available memory (avg): List of top 5 instances with less amount of physical memory immediately available for allocation.  \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bottomk(5,\n  avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_available_memory_bytes_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by Disk read bytes",
   "type": "table",
   "description": "Top 5 Instances by Disk read bytes (sum): List of top 5 instances by disk read bytes  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_read_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by Disk write bytes",
   "type": "table",
   "description": "Top 5 Instances by Disk write bytes (sum): List of top 5 instances by disk write bytes  \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_write_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "description": "CPU Utilization average (avg): The percentage of allocated compute units that are currently in use by the Virtual Machine(s)  \n\nAvailable memory (avg): Amount of physical memory, in bytes, immediately available for allocation to a process or for system use in the Virtual Machine  \n\nNetwork sent (sum): The number of bytes sent to all network interfaces by the Virtual Machine(s)  \n\nNetwork received (sum): The number of bytes received on all network interfaces by the Virtual Machine(s)  \n\nDisk read bytes (sum): Bytes read from disk during monitoring period  \n\nDisk write bytes (sum): Bytes written to disk during monitoring period",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_percentage_cpu_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}"
    },
    {
     "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_available_memory_bytes_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}"
    },
    {
     "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_network_out_total_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}"
    },
    {
     "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_network_in_total_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}"
    },
    {
     "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_read_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}"
    },
    {
     "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_write_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
     "legendFormat": "{{resourceName}}"
    }
   ]
  },
  {
   "title": "Disk read/write bytes",
   "type": "timeseries",
   "description": "Disk read/write bytes (sum): Bytes read/written from/to disk during monitoring period  \n\nDisk write bytes (sum): Bytes written to disk during monitoring period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  sum by (job,resourceGroup,subscriptionName) (\n  azure_microsoft_compute_virtualmachines_disk_read_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(\n  sum by (job,resourceGroup,subscriptionName) (\n  azure_microsoft_compute_virtualmachines_disk_write_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk read/write operations",
   "type": "timeseries",
   "description": "Disk read/write operations (avg): Disk read/write IOPS  \n\nDisk write operations (avg): Disk write IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(\n  avg by (job,resourceGroup,subscriptionName) (\n  azure_microsoft_compute_virtualmachines_disk_read_operations_sec_average_countpersecond{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(\n  avg by (job,resourceGroup,subscriptionName) (\n  azure_microsoft_compute_virtualmachines_disk_write_operations_sec_average_countpersecond{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network throughput sent/received",
   "type": "timeseries",
   "description": "Network throughput sent/received (sum): The number of bytes sent/received over the network.  \n\nNetwork throughput received (sum): The number of bytes received over the network.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  sum by (job,resourceGroup,subscriptionName) (\n  azure_microsoft_compute_virtualmachines_network_out_total_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(\n  sum by (job,resourceGroup,subscriptionName) (\n  azure_microsoft_compute_virtualmachines_network_in_total_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Flows",
   "type": "timeseries",
   "description": "Flows (sum): Number of current flows in the inbound/outbound direction  \n\nOutbound flows (sum): Number of current flows in the outbound direction",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(\n  sum by (job,resourceGroup,subscriptionName) (\n  rate(azure_microsoft_compute_virtualmachines_inbound_flows_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}[$__rate_interval])\n)\n)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(\n  sum by (job,resourceGroup,subscriptionName) (\n  rate(azure_microsoft_compute_virtualmachines_outbound_flows_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}[$__rate_interval])\n)\n)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
     "options": {
      "content": "Use this section to look at one instance at a time by picking a value in the *ResourceName* picker at the top of the dashboard."
     }
    },
    {
     "title": "CPU Utilization average",
     "type": "timeseries",
     "description": "The percentage of allocated compute units that are currently in use by the Virtual Machine(s)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_percentage_cpu_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Available memory",
     "type": "timeseries",
     "description": "Amount of physical memory, in bytes, immediately available for allocation to a process or for system use in the Virtual Machine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_available_memory_bytes_average_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "CPU Credits consumed",
     "type": "timeseries",
     "description": "Total number of credits consumed by the Virtual Machine.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  rate(azure_microsoft_compute_virtualmachines_cpu_credits_consumed_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__rate_interval])\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "CPU Credits remaining",
     "type": "timeseries",
     "description": "Total number of credits available to burst.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  rate(azure_microsoft_compute_virtualmachines_cpu_credits_remaining_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__rate_interval])\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "description": "The number of bytes received on all network interfaces by the Virtual Machine(s)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_network_in_total_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "description": "The number of bytes sent to all network interfaces by the Virtual Machine(s)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_network_out_total_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Disk read bytes",
     "type": "timeseries",
     "description": "Bytes read from disk during monitoring period",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_read_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Disk write bytes",
     "type": "timeseries",
     "description": "Bytes written to disk during monitoring period",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_write_bytes_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Disk read operations",
     "type": "timeseries",
     "description": "Disk read IOPS",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_read_operations_sec_average_countpersecond{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Disk write operations",
     "type": "timeseries",
     "description": "Disk write IOPS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "avg by (job,resourceGroup,subscriptionName,resourceName) (\n  azure_microsoft_compute_virtualmachines_disk_write_operations_sec_average_countpersecond{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Inbound flows",
     "type": "timeseries",
     "description": "The number of current flows in the inbound direction (traffic going into the VM).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  rate(azure_microsoft_compute_virtualmachines_inbound_flows_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__rate_interval])\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    },
    {
     "title": "Outbound flows",
     "type": "timeseries",
     "description": "Number of current flows in the outbound direction",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,resourceName) (\n  rate(azure_microsoft_compute_virtualmachines_outbound_flows_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__rate_interval])\n)",
       "legendFormat": "{{resourceName}}"
      }
     ]
    }
   ]
  }
 ]
}