{
 "title": "Azure Load Balancing",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"azure_microsoft_network_loadbalancers_bytecount_total_bytes\",job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "ResourceGroup",
    "query": "label_values({__name__=~\"azure_microsoft_network_loadbalancers_bytecount_total_bytes\",job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "SubscriptionName",
    "query": "label_values({__name__=~\"azure_microsoft_network_loadbalancers_bytecount_total_bytes\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   },
   {
    "name": "resourceName",
    "label": "ResourceName",
    "query": "label_values({__name__=~\"azure_microsoft_network_loadbalancers_bytecount_total_bytes\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}, resourceName)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Sync Packets",
   "type": "stat",
   "description": "Total number of SYN Packets transmitted",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(azure_microsoft_network_loadbalancers_syncount_total_count[$__range]))"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "stat",
   "description": "Total number of Packets transmitted",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(azure_microsoft_network_loadbalancers_packetcount_total_count[$__range]))"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "stat",
   "description": "Total number of Bytes transmitted",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(azure_microsoft_network_loadbalancers_bytecount_total_bytes[$__range]))"
    }
   ]
  },
  {
   "title": "SNAT connetions",
   "type": "stat",
   "description": "Total number of new SNAT connections created",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(azure_microsoft_network_loadbalancers_snatconnectioncount_total_count[$__range]))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 3 } },
  {
   "title": "Sync Packets",
   "type": "timeseries",
   "description": "Total number of SYN Packets transmitted within time period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (resourceGroup) (azure_microsoft_network_loadbalancers_syncount_total_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{resourceGroup}}"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "description": "Total number of Packets transmitted within time period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (resourceGroup) (azure_microsoft_network_loadbalancers_packetcount_total_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{resourceGroup}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "description": "Total number of Bytes transmitted within time period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (resourceGroup) (azure_microsoft_network_loadbalancers_bytecount_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{resourceGroup}}"
    }
   ]
  },
  {
   "title": "SNAT connections",
   "type": "timeseries",
   "description": "Total number of new SNAT connections created within time period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (resourceGroup) (azure_microsoft_network_loadbalancers_snatconnectioncount_total_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "{{resourceGroup}}"
    }
   ]
  },
  { "title": "SNAT Ports", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 20 } },
  {
   "title": "SNAT Ports",
   "type": "timeseries",
   "description": "SNAT Ports (avg): Total SNAT ports used and allocated within time period  \n\nAllocated SNAT Ports (avg): Total number of SNAT ports allocated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(azure_microsoft_network_loadbalancers_usedsnatports_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(azure_microsoft_network_loadbalancers_allocatedsnatports_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Currently used SNAT ports",
   "type": "gauge",
   "description": "Currently used SNAT ports (avg): Total SNAT ports used at the current time  \n\nAllocated SNAT Ports (avg): Total number of SNAT ports allocated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(azure_microsoft_network_loadbalancers_usedsnatports_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(azure_microsoft_network_loadbalancers_allocatedsnatports_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"})",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}