{
 "title": "Azure SQL database",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_databases_sessions_count_average_count\",job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "ResourceGroup",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_databases_sessions_count_average_count\",job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "SubscriptionName",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_databases_sessions_count_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   },
   {
    "name": "resourceName",
    "label": "ResourceName",
    "query": "label_values({__name__=~\"azure_microsoft_sql_servers_databases_sessions_count_average_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}, resourceName)"
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Successful connections by database",
   "type": "timeseries",
   "description": "Count of successful connections by database",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_connection_successful_total_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Deadlocks by database",
   "type": "timeseries",
   "description": "Count of deadlocks by database",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(max_over_time(azure_microsoft_sql_servers_databases_deadlock_total_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}[$__interval]), \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average sessions by database",
   "type": "timeseries",
   "description": "Average number of sessions by database",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_sessions_count_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "CPU utilization by database",
   "type": "timeseries",
   "description": "CPU utilization by database (avg): Percent of CPU utilization by database. If database uses vCores, the vCore percent utilization is shown  \n\nvCore utilization by database (avg): Percent of CPU utilization by database. If database uses vCores, the vCore percent utilization is shown",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_cpu_percent_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    },
    {
     "expr": "100 * (\n  label_replace(azure_microsoft_sql_servers_databases_cpu_used_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\") / label_replace(azure_microsoft_sql_servers_databases_cpu_limit_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")\n)",
     "legendFormat": "{{database}} vCore"
    }
   ]
  },
  {
   "title": "Storage utilization by database",
   "type": "timeseries",
   "description": "Bytes of storage by database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_storage_maximum_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Storage % of limit by database",
   "type": "timeseries",
   "description": "Percent used of storage limitby database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_storage_percent_maximum_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "description": "Average number of DTUs utilized by database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_dtu_used_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "DTU utilization and limits by database",
   "type": "table",
   "description": "DTU utilization and limits by database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_dtu_used_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    },
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_dtu_consumption_percent_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    },
    {
     "expr": "label_replace(azure_microsoft_sql_servers_databases_dtu_limit_average_count{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\",resourceName=~\"$resourceName\"}, \"database\", \"$1\", \"resourceID\", \".+/(.*)\")",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}