{
 "title": "Azure Front Door",
 "tags": [ "azure-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"azure_microsoft_cdn_profiles_requestcount_total_count\",job=\"integrations/azure\"}, job)"
   },
   {
    "name": "resourceGroup",
    "label": "Group",
    "query": "label_values({__name__=~\"azure_microsoft_cdn_profiles_requestcount_total_count\",job=\"integrations/azure\",job=~\"$job\"}, resourceGroup)"
   },
   {
    "name": "subscriptionName",
    "label": "Subscription",
    "query": "label_values({__name__=~\"azure_microsoft_cdn_profiles_requestcount_total_count\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\"}, subscriptionName)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Endpoints Count",
   "type": "stat",
   "description": "Number of endpoints",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  sum by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)\nor\ncount(\n  sum by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Endpoints by Errors",
   "type": "table",
   "description": "Top 5 Endpoints by Errors (avg): Top 5 Endpoints with higher percentage of client requests for which the response status code is 4XX or 5XX  \n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job, resourceGroup, subscriptionName, resourceName, dimensionClientCountry, dimensionClientRegion, dimension_ClientCountry, dimension_ClientRegion) (azure_microsoft_cdn_profiles_percentage4xx_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}) + avg by (job, resourceGroup, subscriptionName, resourceName, dimensionClientCountry, dimensionClientRegion, dimension_ClientCountry, dimension_ClientRegion) (azure_microsoft_cdn_profiles_percentage5xx_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"})\n)"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "The number of client requests served by the HTTP/S proxy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum(\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Requests by country",
   "type": "timeseries",
   "description": "The number of client requests served by the HTTP/S proxy grouped by country",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,resourceGroup,subscriptionName,dimensionClientCountry) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimensionClientCountry!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum by (job,resourceGroup,subscriptionName,dimension_ClientCountry) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimension_ClientCountry!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "{{dimensionClientCountry}} {{dimension_ClientCountry}}"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "description": "The number of client requests served by the HTTP/S proxy grouped by status group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,resourceGroup,subscriptionName,dimensionHttpStatusGroup) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimensionHttpStatusGroup!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum by (job,resourceGroup,subscriptionName,dimension_HttpStatusGroup) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimension_HttpStatusGroup!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "{{dimensionHttpStatusGroup}} {{dimension_HttpStatusGroup}}"
    }
   ]
  },
  {
   "title": "Request by Errors percentage",
   "type": "timeseries",
   "description": "4XX Errors percentage (avg):   \n\n5XX Errors percentage (avg): ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\n  azure_microsoft_cdn_profiles_percentage4xx_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "4xx"
    },
    {
     "expr": "avg(\n  azure_microsoft_cdn_profiles_percentage5xx_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request/Responses size",
   "type": "timeseries",
   "description": "Requests size (avg): The number of bytes sent as requests from clients to AFDX.  \n\nResponses size (avg): The number of bytes sent as responses from HTTP/S proxy to clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n  azure_microsoft_cdn_profiles_requestsize_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(\n  azure_microsoft_cdn_profiles_responsesize_total_bytes{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "Total latency",
   "type": "timeseries",
   "description": "The time calculated from when the client request was received by the HTTP/S proxy until the client acknowledged the last response byte from the HTTP/S proxy\tTotalLatency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  azure_microsoft_cdn_profiles_totallatency_average_milliseconds{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)"
    }
   ]
  },
  {
   "title": "Origin Health percentage",
   "type": "timeseries",
   "description": "The percentage of successful health probes from AFDX to backends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\n  azure_microsoft_cdn_profiles_originhealthpercentage_average_percent{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)"
    }
   ]
  },
  {
   "title": "Origin Latency average",
   "type": "timeseries",
   "description": "The time calculated from when the request was sent by AFDX edge to the backend until AFDX received the last response byte from the backend.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  azure_microsoft_cdn_profiles_originlatency_average_milliseconds{job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests",
     "type": "timeseries",
     "description": "Number of requests by endpoints.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_requestcount_total_count{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    },
    {
     "title": "Requests size",
     "type": "timeseries",
     "description": "The number of bytes sent as requests from clients to AFDX.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_requestsize_total_bytes{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_requestsize_total_bytes{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    },
    {
     "title": "Responses size",
     "type": "timeseries",
     "description": "The number of bytes sent as responses from HTTP/S proxy to clients.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_responsesize_total_bytes{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_responsesize_total_bytes{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    },
    {
     "title": "Total latency",
     "type": "timeseries",
     "description": "The time calculated from when the client request was received by the HTTP/S proxy until the client acknowledged the last response byte from the HTTP/S proxy\tTotalLatency",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_totallatency_average_milliseconds{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\navg by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_totallatency_average_milliseconds{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    },
    {
     "title": "Percentage of errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (job, resourceGroup, subscriptionName, dimensionEndpoint) (azure_microsoft_cdn_profiles_percentage4xx_average_percent{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}) + avg by (job, resourceGroup, subscriptionName, dimensionEndpoint) (azure_microsoft_cdn_profiles_percentage5xx_average_percent{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"})\nor\navg by (job, resourceGroup, subscriptionName, dimension_Endpoint) (azure_microsoft_cdn_profiles_percentage4xx_average_percent{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}) + avg by (job, resourceGroup, subscriptionName, dimension_Endpoint) (azure_microsoft_cdn_profiles_percentage5xx_average_percent{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"})",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    },
    {
     "title": "Origin Request count",
     "type": "timeseries",
     "description": "The number of requests sent from AFDX to origin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_originrequestcount_total_count{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\nsum by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_originrequestcount_total_count{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    },
    {
     "title": "Origin Latency average",
     "type": "timeseries",
     "description": "The time calculated from when the request was sent by AFDX edge to the backend until AFDX received the last response byte from the backend.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (job,resourceGroup,subscriptionName,dimensionEndpoint) (\n  azure_microsoft_cdn_profiles_originlatency_average_milliseconds{dimensionEndpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)\nor\navg by (job,resourceGroup,subscriptionName,dimension_Endpoint) (\n  azure_microsoft_cdn_profiles_originlatency_average_milliseconds{dimension_Endpoint!=\"\",job=\"integrations/azure\",job=~\"$job\",resourceGroup=~\"$resourceGroup\",subscriptionName=~\"$subscriptionName\"}\n)",
       "legendFormat": "{{dimensionEndpoint}} {{dimension_Endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}