{
 "title": "GCP Virtual private cloud",
 "tags": [ "gcp-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(stackdriver_networking_googleapis_com_location_networking_googleapis_com_fixed_standard_tier_usage{job=\"integrations/gcp\"}, job)"
   },
   {
    "name": "project_id",
    "label": "Project",
    "query": "label_values(stackdriver_networking_googleapis_com_location_networking_googleapis_com_fixed_standard_tier_usage{job=\"integrations/gcp\",job=~\"$job\"}, project_id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Total services in use",
   "type": "stat",
   "description": "Count of unique service names (including \"UNKNOWN\") with ingress or egress traffic.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (service_name) (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"} OR stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}))",
     "legendFormat": "{{job}}: Total services in use"
    }
   ]
  },
  {
   "title": "Total subnets in use",
   "type": "stat",
   "description": "Count of unique subnets (including the catch-all \"LOCAL_IS_EXTERNAL\") with ingress or egress traffic on services or a VPN tunnel.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (local_subnetwork) (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"} OR stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"} OR stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_egress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"} OR stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_ingress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}))",
     "legendFormat": "{{job}}: Total subnets in use"
    }
   ]
  },
  {
   "title": "Fixed standard tier network egress",
   "type": "timeseries",
   "description": "Rate in bytes of network egress on the fixed standard tier.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (job,traffic_source) (\n  stackdriver_networking_googleapis_com_location_networking_googleapis_com_fixed_standard_tier_usage{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}\n)",
     "legendFormat": "{{job}}: Fixed standard tier network egress ({{traffic_source}})"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "Top 5 services - Average throughput",
   "type": "table",
   "description": "Average throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,service_name) (\n  stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"} + stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}\n)\n)",
     "legendFormat": "{{job}}: Top 5 services by network throughput. ({{service_name}})"
    }
   ]
  },
  {
   "title": "Top 5 services - Average error rate",
   "type": "table",
   "description": "Average error rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,service_name) (\n  (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\", response_code_class=~\"500|400\"} + stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\", response_code_class=~\"500|400\"}) / (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"} + stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"})\n)\n)",
     "legendFormat": "{{job}}: Top 5 services by network error response code ({{service_name}})"
    }
   ]
  },
  {
   "title": "Total service network throughput",
   "type": "timeseries",
   "description": "received (sum):   \n\ntransmitted (sum): ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: received"
    },
    {
     "expr": "sum by (job) (\n  rate(stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: transmitted"
    }
   ]
  },
  {
   "title": "Service network throughput percent by service in error",
   "type": "timeseries",
   "description": "received (avg):   \n\ntransmitted (avg): ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (service_name) (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\", response_code_class=~\"500|400\"}) / sum by (service_name) (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"})",
     "legendFormat": "{{service_name}}: received"
    },
    {
     "expr": "sum by (service_name) (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\", response_code_class=~\"500|400\"}) / sum by (service_name) (stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"})",
     "legendFormat": "{{service_name}}: transmitted"
    }
   ]
  },
  {
   "title": "Service network throughput by service",
   "type": "timeseries",
   "description": "received (sum):   \n\ntransmitted (sum): ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,service_name) (\n  rate(stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: received ({{service_name}})"
    },
    {
     "expr": "sum by (job,service_name) (\n  rate(stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: transmitted ({{service_name}})"
    }
   ]
  },
  {
   "title": "Service network throughput by response code",
   "type": "timeseries",
   "description": "received (sum):   \n\ntransmitted (sum): ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,response_code_class) (\n  rate(stackdriver_google_service_gce_client_networking_googleapis_com_google_service_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: received ({{response_code_class}})"
    },
    {
     "expr": "sum by (job,response_code_class) (\n  rate(stackdriver_google_service_gce_client_networking_googleapis_com_google_service_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: transmitted ({{response_code_class}})"
    }
   ]
  },
  { "title": "VPN tunnels", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 42 } },
  {
   "title": "Total tunnel network throughput",
   "type": "timeseries",
   "description": "transmitted (avg):   \n\nreceived (avg): ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  rate(stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_egress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: transmitted"
    },
    {
     "expr": "avg by (job) (\n  rate(stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_ingress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: received"
    }
   ]
  },
  {
   "title": "Total tunnel network throughput by protocol",
   "type": "timeseries",
   "description": "transmitted (avg):   \n\nreceived (avg): ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (job,protocol) (\n  rate(stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_egress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: transmitted ({{protocol}})"
    },
    {
     "expr": "avg by (job,protocol) (\n  rate(stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_ingress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: received ({{protocol}})"
    }
   ]
  },
  {
   "title": "Total tunnel network throughput by resource type",
   "type": "timeseries",
   "description": "transmitted (avg):   \n\nreceived (avg): ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (job,local_resource_type) (\n  rate(stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_egress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: transmitted ({{local_resource_type}})"
    },
    {
     "expr": "avg by (job,local_resource_type) (\n  rate(stackdriver_vpn_tunnel_networking_googleapis_com_vpn_tunnel_ingress_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: received ({{local_resource_type}})"
    }
   ]
  }
 ]
}