{
 "title": "GCP Blob storage",
 "tags": [ "gcp-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{job=\"integrations/gcp\"}, job)"
   },
   {
    "name": "bucket_name",
    "label": "Bucket Name",
    "query": "label_values(stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{job=\"integrations/gcp\",job=~\"$job\"}, bucket_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Bucket count",
   "type": "stat",
   "description": "Number of storage buckets.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "count(sum by (bucket_name) (stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}))",
     "legendFormat": "{{bucket_name}}: Bucket count"
    }
   ]
  },
  {
   "title": "Object count",
   "type": "stat",
   "description": "Number of objects stored.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"})",
     "legendFormat": "{{bucket_name}}: Object count"
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "stat",
   "description": "Total bytes stored",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_storage_total_bytes{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"})",
     "legendFormat": "{{bucket_name}}: Total bytes"
    }
   ]
  },
  {
   "title": "Top 5 Buckets - Network Throughput",
   "type": "table",
   "description": "Total network throughput in bits for the selected timerange",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range]))\n+ sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])))\n",
     "legendFormat": "{{bucket_name}}: Network bits throughput"
    },
    {
     "expr": "sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])) and topk(5, sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range]))\n+ sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])))\n",
     "legendFormat": "{{bucket_name}}: Network bits received"
    },
    {
     "expr": "sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])) and topk(5, sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range]))\n+ sum by (job, bucket_name) (increase(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])))\n",
     "legendFormat": "{{bucket_name}}: Network bits transmitted"
    }
   ]
  },
  {
   "title": "Top 5 Buckets - Object Count",
   "type": "table",
   "description": "Number of objects stored.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,bucket_name) (\n  max_over_time(stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])\n)\n)",
     "legendFormat": "{{bucket_name}}: Top 5 buckets - object count"
    }
   ]
  },
  {
   "title": "Top 5 Buckets - Total Bytes",
   "type": "table",
   "description": "Total bytes stored",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg by (job,bucket_name) (\n  max_over_time(stackdriver_gcs_bucket_storage_googleapis_com_storage_total_bytes{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__range])\n)\n)",
     "legendFormat": "{{bucket_name}}: Top 5 buckets - total bytes"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 15 } },
  {
   "title": "API requests by type",
   "type": "timeseries",
   "description": "Count of all API requests",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (method) (rate(stackdriver_gcs_bucket_storage_googleapis_com_api_request_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API error rate by type",
   "type": "timeseries",
   "description": "Percentage of api request failure by type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(stackdriver_gcs_bucket_storage_googleapis_com_api_request_count{response_code!=\"OK\", job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__rate_interval])) / sum by (method) (rate(stackdriver_gcs_bucket_storage_googleapis_com_api_request_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 28 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "received (avg): Total bytes received over the network  \n\ntransmitted (avg): Total bytes sent over the network",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg by (job,bucket_name) (\n  rate(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__rate_interval])\n)",
     "legendFormat": "{{bucket_name}}: received"
    },
    {
     "expr": "avg by (job,bucket_name) (\n  rate(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count{job=\"integrations/gcp\",job=~\"$job\",bucket_name=~\"$bucket_name\"}[$__rate_interval])\n)",
     "legendFormat": "{{bucket_name}}: transmitted"
    }
   ]
  }
 ]
}