{
 "title": "GCP Load Balancing",
 "tags": [ "gcp-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\"}, job)"
   },
   {
    "name": "project_id",
    "label": "Project_id",
    "query": "label_values(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\"}, project_id)"
   },
   {
    "name": "client_country",
    "label": "Country",
    "query": "label_values(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\"}, client_country)"
   },
   {
    "name": "backend_target_name",
    "label": "Backend Target",
    "query": "label_values(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\"}, backend_target_name)"
   }
  ]
 },
 "panels": [
  { "title": "Load balancer requests", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Requests by status code",
   "type": "timeseries",
   "description": "Amount of requests sent by status code for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(sum by (response_code_class) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])),\"response_code_class\",\"${1}xx\",\"response_code_class\",\"([0-9])00\")",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Requests by country",
   "type": "timeseries",
   "description": "Amount of requests sent by country for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (backend_target_name, client_country) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "{{client_country}}"
    }
   ]
  },
  {
   "title": "Requests by cache results",
   "type": "timeseries",
   "description": "Amount of cache results for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (backend_target_name, cache_result) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "{{cache_result}}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "timeseries",
   "description": "Amount of requests by protocol for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (backend_target_name, protocol) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Error rate percentage",
   "type": "timeseries",
   "description": "Percentage of requests failing for the filters selected",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * (sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\", response_code_class!=\"200\", response_code_class!=\"0\"}) / sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}))",
     "legendFormat": "Error Rate visualization"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Total Response",
   "type": "timeseries",
   "description": "Total Response (avg): Latency of all responses for the filters selected  \n\nLatency 90 (avg): The total latency of responses  \n\nLatency 99 (avg): The total latency of responses  \n\nLatency Average (avg): Latency of return trip time for the frontend for the filters selected",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le) (stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_total_latencies_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}) > 0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_total_latencies_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}) > 0)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_total_latencies_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}) > 0)",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_total_latencies_sum{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}) / sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_total_latencies_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Frontend RTT",
   "type": "timeseries",
   "description": "Frontend RTT (avg): Latency of return trip time for the frontend for the filters selected  \n\nFrontend RTT Latency 90 (avg): Latency of return trip time for the frontend for the filters selected  \n\nFrontend RTT Latency 99 (avg): Latency of return trip time for the frontend for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum by (le) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_frontend_tcp_rtt_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])) > 0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90,sum by (le) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_frontend_tcp_rtt_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])) > 0)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_frontend_tcp_rtt_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])) > 0)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Backend Response",
   "type": "timeseries",
   "description": "Backend Response (avg): Latency of responses for the backend for the filters selected  \n\nBackend Response Latency 90 (avg): Latency of responses for the backend for the filters selected  \n\nBackend Response Latency 99 (avg): Latency of responses for the backend for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])) > 0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])) > 0)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval])) > 0)",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 45 } },
  {
   "title": "Total requests sent/received",
   "type": "timeseries",
   "description": "Total requests sent/received (avg): Total bytes sent/received by load balancer for the filters selected  \n\nTotal Requests received (avg): Total bytes received by load balancer for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",client_country=~\"$client_country\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Backend requests sent/received",
   "type": "timeseries",
   "description": "Backend requests sent/received (avg): Total bytes sent/received by backend for the filters selected  \n\nBackend Total Requests received (avg): Total bytes sent/received by backend for the filters selected",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_response_bytes_count{job=\"integrations/gcp\",job=~\"$job\",project_id=~\"$project_id\",backend_target_name=~\"$backend_target_name\"}[$__rate_interval]))",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}