{
 "title": "GCP Compute Engine",
 "tags": [ "gcp-cloud-provider" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\"}, job)"
   },
   {
    "name": "project_id",
    "label": "Project_id",
    "query": "label_values(stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\",job=~\"$job\"}, project_id)"
   },
   {
    "name": "instance_name",
    "label": "Instance_name",
    "query": "label_values(stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}, instance_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Instance count",
   "type": "stat",
   "description": "Number of VM instances",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  sum by (job,project_id,instance_name) (\n  stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}\n)\n)",
     "legendFormat": "Number of instances"
    }
   ]
  },
  {
   "title": "System problem count",
   "type": "stat",
   "description": "Number of errors fired on all instances.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(stackdriver_gce_instance_compute_googleapis_com_guest_system_problem_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__range]))",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "Top 5 Instances by CPU utilitization",
   "type": "table",
   "description": "Top 5 Instances by CPU utilitization (sum): Fractional utilization of allocated CPU on an instance  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(5, 100*\n  sum by (job,project_id,instance_name) (\n  stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by System problem",
   "type": "table",
   "description": "Top 5 Instances by System problem (sum): List of top 5 instances with system problems.  \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (job,project_id,instance_name) (\n  increase(stackdriver_gce_instance_compute_googleapis_com_guest_system_problem_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__range])\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by Disk read bytes",
   "type": "table",
   "description": "Top 5 Instances by Disk read bytes (sum): List of top 5 instances by disk read bytes  \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (job,project_id,instance_name) (\n  increase(stackdriver_gce_instance_compute_googleapis_com_instance_disk_read_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__range])\n)\n)"
    }
   ]
  },
  {
   "title": "Top 5 Instances by Disk write bytes",
   "type": "table",
   "description": "Top 5 Instances by Disk write bytes (sum): List of top 5 instances by disk write bytes  \n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (job,project_id,instance_name) (\n  increase(stackdriver_gce_instance_compute_googleapis_com_instance_disk_write_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__range])\n)\n)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "100 *\n  sum by (job,project_id,instance_name) (\n  stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}\n)\n"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  stackdriver_gce_instance_compute_googleapis_com_instance_uptime_total{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}\n)"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_packets_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[5m])\n)"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_received_packets_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[5m])\n)"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[5m])\n)"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_received_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[5m])\n)"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_read_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[5m])\n)"
    },
    {
     "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_write_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Memory utilization (avg): Memory utilization  \n\nMemory utilization2 (avg): Memory used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_compute_googleapis_com_instance_memory_balloon_ram_size{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}) + sum(stackdriver_gce_instance_compute_googleapis_com_guest_memory_bytes_used{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"})",
     "legendFormat": "Total Memory Capacity"
    },
    {
     "expr": "sum(stackdriver_gce_instance_compute_googleapis_com_instance_memory_balloon_ram_used{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}) + sum(stackdriver_gce_instance_compute_googleapis_com_guest_memory_bytes_used{job!=\"\",job=~\"$job\",project_id=~\"$project_id\", state!=\"free\"})",
     "legendFormat": "Total Memory Used"
    }
   ]
  },
  {
   "title": "Sent/received packets",
   "type": "timeseries",
   "description": "Sent/received packets (sum): Packets sent/received over the network. Sampled every 60 seconds  \n\nReceived packets (sum): Packets received over the network. Sampled every 60 seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by (job,project_id) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_packets_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum by (job,project_id) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_received_packets_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Network throughput sent/received",
   "type": "timeseries",
   "description": "Network throughput sent/received (avg): Count of bytes sent/received over the network. Sampled every 60 seconds  \n\nNetwork throughput received (avg): Count of bytes sent/received over the network. Sampled every 60 seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,project_id) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "Sent"
    },
    {
     "expr": "avg by (job,project_id) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_received_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Disk read/write bytes",
   "type": "timeseries",
   "description": "Disk read/write bytes (avg): Total count of bytes read/write from disk. Sampled every 60 seconds  \n\nDisk write bytes (avg): Total count of bytes read/write from disk. Sampled every 60 seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,project_id) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_read_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg by (job,project_id) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_write_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\"}[$__rate_interval])\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instances",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 58 },
     "options": {
      "content": "Use this section to look at one instance at a time by picking a value in the *Instance* picker at the top of the dashboard."
     }
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "description": "Fractional utilization of allocated CPU on this instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Cpu usage time",
     "type": "timeseries",
     "description": "CPU usage, in seconds. For Container-Optimized OS, or Ubuntu running GKE.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_cpu_usage_time{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Network received",
     "type": "timeseries",
     "description": "Bytes received from the network. Sampled every 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_received_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Network sent",
     "type": "timeseries",
     "description": "Bytes sent from the network. Sampled every 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Disk read bytes",
     "type": "timeseries",
     "description": "Bytes read from disk. Sampled every 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "\n  avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_read_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)\n> 0",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Disk write bytes",
     "type": "timeseries",
     "description": "Bytes written to disk. Sampled every 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_write_bytes_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Disk read operations",
     "type": "timeseries",
     "description": "Disk read IO operations. Sampled every 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_read_ops_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    },
    {
     "title": "Disk write operations",
     "type": "timeseries",
     "description": "Disk write IO operations. Sampled every 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,project_id,instance_name) (\n  rate(stackdriver_gce_instance_compute_googleapis_com_instance_disk_write_ops_count{job!=\"\",job=~\"$job\",project_id=~\"$project_id\",instance_name=~\"$instance_name\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance_name}}"
      }
     ]
    }
   ]
  }
 ]
}