{
 "title": "MongoDB cluster",
 "tags": [ "mongodb-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(mongodb_up,job)" } },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\"},mongodb_cluster)"
    }
   },
   {
    "name": "shard",
    "label": "shard",
    "query": {
     "query": "label_values(mongodb_mongos_db_collections_total{job=~\"$job\",mongodb_cluster=\"$cluster\"},shard)"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\",mongodb_cluster=\"$cluster\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of collections in shards",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (db,shard) (mongodb_mongos_db_collections_total{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"})",
     "legendFormat": "{{db}} | {{shard}} | Collections"
    }
   ]
  },
  {
   "title": "Size of collections in shards",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (db,shard) (mongodb_mongos_db_data_size_bytes{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"})"
    }
   ]
  },
  {
   "title": "# of shards",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_total{job=~\"$job\",mongodb_cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded DBs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{job=~\"$job\",mongodb_cluster=\"$cluster\", type=\"partitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Unsharded DBs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{job=~\"$job\",mongodb_cluster=\"$cluster\", type=\"unpartitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Draining shards",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_draining_total{job=~\"$job\",mongodb_cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded collections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_collections_total{job=~\"$job\",mongodb_cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sharding_chunks_total{job=~\"$job\",mongodb_cluster=\"$cluster\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Balancer enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_balancer_enabled{job=~\"$job\",mongodb_cluster=\"$cluster\"})",
     "legendFormat": "Cluster balanced"
    }
   ]
  },
  {
   "title": "Chuncks balanced",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(mongodb_mongos_sharding_chunks_is_balanced{job=~\"$job\",mongodb_cluster=\"$cluster\"})",
     "legendFormat": "Cluster balanced"
    }
   ]
  },
  {
   "title": "Shard services QPS - $shard",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "shard",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (service_name) (irate(mongodb_op_counters_total{job=~\"$job\",type!=\"command\"}[$__rate_interval]))) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\",set=~\"$shard\"}/ mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\",set=~\"$shard\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Config services QPS - ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (service_name) (irate(mongodb_op_counters_total{job=~\"$job\",type!=\"command\"}[$__rate_interval]))) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\",set!~\"$shard\"}/ mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\",set!~\"$shard\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Mongos services QPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (service_name) (rate(mongodb_op_counters_total{job=~\"$job\",type!=\"command\"}[$__rate_interval]))) * on (service_name) group_right avg by (service_name) (avg by (service_name) (mongodb_mongos_db_collections_total{job=~\"$job\",mongodb_cluster=\"$cluster\"}) / avg by (service_name) (mongodb_mongos_db_collections_total{job=~\"$job\",mongodb_cluster=\"$cluster\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Chunks in shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "# of chunks in shards",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "mongodb_mongos_sharding_shard_chunks_total{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Dynamic of chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_sharding_shard_chunks_total{job=~\"$job\",mongodb_cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Chunk split events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_sharding_changelog_10min_total{job=~\"$job\",mongodb_cluster=\"$cluster\", event=~\".*split.*\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Chunk move events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_sharding_changelog_10min_total{job=~\"$job\",mongodb_cluster=\"$cluster\", event=~\".*moveChunk.*\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Indexes in shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "# Indexes per shard",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "mongodb_mongos_db_indexes_total{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"}",
     "legendFormat": "{{db}} | {{shard}} | Collections"
    }
   ]
  },
  {
   "title": "Dynamic of indexes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_db_indexes_total{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"}[$__rate_interval])",
     "legendFormat": "{{shard}}-{{db}}"
    }
   ]
  },
  {
   "title": "Size of indexes per shard",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_mongos_db_index_size_bytes{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"}",
     "legendFormat": "{{db}} | {{shard}} | Collections"
    }
   ]
  },
  {
   "title": "Dynamic of indexes size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongos_db_index_size_bytes{job=~\"$job\",mongodb_cluster=\"$cluster\",db!~\"admin|config\"}[$__rate_interval])",
     "legendFormat": "{{shard}}-{{db}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Current connections per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{job=~\"$job\",mongodb_cluster=\"$cluster\",state=\"current\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Current connections per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{job=~\"$job\",mongodb_cluster=\"$cluster\",state=\"current\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Available connections per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{job=~\"$job\",mongodb_cluster=\"$cluster\",state=\"available\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Current connections per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum by (set) (avg by (service_name,set) (mongodb_connections{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"current\"}) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"}/ mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"}))",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Operattions per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum( sum( irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=\"$cluster\", type!=\"command\"}[$__rate_interval])) by (instance) * on (instance)  group_right mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Operations by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum by (type) (irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=\"$cluster\", type!=\"command\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Operations $service_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "repeat": "service_name",
   "targets": [
    {
     "expr": "sum by (type) (irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Cursors per shard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(sum(mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total\"} or mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total_open\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "MongoDB cursors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum by () (  max_over_time(mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total\"}[$__rate_interval]) or max_over_time(mongodb_mongos_metrics_cursor_open{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total\"}[$__rate_interval]) or max_over_time(mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total_open\"}[$__rate_interval]) or max_over_time(mongodb_mongos_cursors{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total_open\"}[$__rate_interval]) )",
     "legendFormat": "Cursors"
    }
   ]
  },
  {
   "title": "Cursors By instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by (service_name) (  max_over_time(mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total\"}[$__rate_interval]) or max_over_time(mongodb_mongos_metrics_cursor_open{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total\"}[$__rate_interval]) or max_over_time(mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total_open\"}[$__rate_interval]) or max_over_time(mongodb_mongos_cursors{job=~\"$job\",mongodb_cluster=\"$cluster\", state=\"total_open\"}[$__rate_interval]) )",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Additional info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Replication lag by set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "max by (set) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{job=~\"$job\",mongodb_cluster=\"$cluster\"}[$__rate_interval]) > 0) by (service_name,set) or max(max_over_time(mongodb_mongod_replset_member_replication_lag{job=~\"$job\",mongodb_cluster=\"$cluster\"}[$__rate_interval]) > 0) by (service_name,set))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Replication lag by set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp{job=~\"$job\",mongodb_cluster=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{job=~\"$job\",mongodb_cluster=\"$cluster\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  }
 ]
}