{
 "title": "MongoDB instance",
 "tags": [ "mongodb-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mongodb_up{}, job)"
   },
   {
    "name": "mongodb_cluster",
    "label": "MongoDB cluster",
    "query": "label_values(mongodb_up{job=~\"$job\"}, mongodb_cluster)"
   },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(mongodb_up{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}, service_name)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "table",
   "description": "Per-instance overview: uptime, QPS, replica set state and command latency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (instance) (mongodb_instance_uptime_seconds{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(mongodb_mongod_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!=\"command\"}[$__rate_interval]) or irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!=\"command\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max by (instance) (mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max by (instance) (irate(mongodb_mongod_op_latencies_latency_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type=\"command\"}[$__rate_interval]) / (irate(mongodb_mongod_op_latencies_ops_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type=\"command\"}[$__rate_interval]) > 0))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Service summary", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Operations by type",
   "type": "timeseries",
   "description": "Rate of operations by type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance, type) (\n  irate(mongodb_mongod_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!=\"command\"}[$__rate_interval])\n  or irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!=\"command\"}[$__rate_interval])\n)\nand\navg by (job,mongodb_cluster,service_name,instance, type) (\n  increase(mongodb_mongod_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!=\"command\"}[$__range])\n  or increase(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!=\"command\"}[$__range])\n) > 0\n",
     "legendFormat": "{{instance}} - {{type}}"
    },
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance, type) (\n  irate(mongodb_mongod_op_counters_repl_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$__rate_interval])\n  or irate(mongodb_mongos_op_counters_repl_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$__rate_interval])\n)\nand\navg by (job,mongodb_cluster,service_name,instance, type) (\n  increase(mongodb_mongod_op_counters_repl_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$__range])\n  or increase(mongodb_mongos_op_counters_repl_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$__range])\n) > 0\n",
     "legendFormat": "{{instance}} - {{type}}"
    },
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (\n  irate(mongodb_mongod_metrics_ttl_deleted_documents_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_mongos_metrics_ttl_deleted_documents_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{instance}} - TTL deleted"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of current connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (\n  mongodb_mongod_connections{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"current\"} or mongodb_mongos_connections{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"current\"} or mongodb_connections{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"current\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Document operations",
   "type": "timeseries",
   "description": "Rate of document operations by state.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance, state) (irate(mongodb_mongod_metrics_document_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval]))\nand\navg by (job,mongodb_cluster,service_name,instance, state) (increase(mongodb_mongod_metrics_document_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])) > 0\n",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Latency detail",
   "type": "timeseries",
   "description": "Average operation latency by type.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance, type) (irate(mongodb_mongod_op_latencies_latency_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval]) / (irate(mongodb_mongod_op_latencies_ops_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval]) > 0))",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Queued operations",
   "type": "timeseries",
   "description": "Number of operations queued due to a lock.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,type,instance) (mongodb_mongod_global_lock_current_queue{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"})\nand\navg by (job,mongodb_cluster,service_name,type,instance) (max_over_time(mongodb_mongod_global_lock_current_queue{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])) > 0\n",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "description": "Number of open cursors by state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,state,instance) (\n  mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}\n  or mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}\n  or mongodb_mongos_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}\n  or mongodb_mongos_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}\n)\nand\navg by (job,mongodb_cluster,service_name,state,instance) (\n  max_over_time(mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or max_over_time(mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or max_over_time(mongodb_mongos_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or max_over_time(mongodb_mongos_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n) > 0\n",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Scanned and moved objects",
   "type": "timeseries",
   "description": "Rate of scanned objects and record moves.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance, state) (irate(mongodb_mongod_metrics_query_executor_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval]))\nand\navg by (job,mongodb_cluster,service_name,instance, state) (increase(mongodb_mongod_metrics_query_executor_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])) > 0\n",
     "legendFormat": "{{instance}} - {{state}}"
    },
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (rate(mongodb_mongod_metrics_record_moves_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - moved"
    }
   ]
  },
  {
   "title": "getLastError write operations",
   "type": "timeseries",
   "description": "Rate of getLastError write operations and timeouts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (\n  irate(mongodb_mongod_metrics_get_last_error_wtime_num_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_mongos_metrics_get_last_error_wtime_num_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{instance}} - Total"
    },
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (\n  irate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{instance}} - Timeouts"
    }
   ]
  },
  {
   "title": "getLastError write time",
   "type": "timeseries",
   "description": "Rate of getLastError write wait time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (\n  irate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{instance}} - Write wait time"
    }
   ]
  },
  {
   "title": "Assert events",
   "type": "timeseries",
   "description": "Rate of assert events by type.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance, type) (\n  irate(mongodb_mongod_asserts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_mongos_asserts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_asserts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n)\nand\navg by (job,mongodb_cluster,service_name,instance, type) (\n  increase(mongodb_mongod_asserts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or increase(mongodb_mongos_asserts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or increase(mongodb_asserts_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n) > 0\n",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Query efficiency",
   "type": "timeseries",
   "description": "Query efficiency ratios (higher is better). Documents: fraction of scanned objects that were returned; Index: fraction of scanned objects reached via an index. Low values point to collection scans or missing indexes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(mongodb_mongod_metrics_document_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"returned\"}[$__rate_interval])) / sum(irate(mongodb_mongod_metrics_query_executor_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"scanned_objects\"}[$__rate_interval]))",
     "legendFormat": "Document"
    },
    {
     "expr": "sum(irate(mongodb_mongod_metrics_query_executor_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"scanned\"}[$__rate_interval])) / sum(irate(mongodb_mongod_metrics_query_executor_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", state=\"scanned_objects\"}[$__rate_interval]))",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "timeseries",
   "description": "Rate of page faults.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,service_name,instance) (\n  irate(mongodb_mongod_extra_info_page_faults_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_mongos_extra_info_page_faults_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n  or irate(mongodb_extra_info_page_faults_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__rate_interval])\n)\nand\navg by (job,mongodb_cluster,service_name,instance) (\n  increase(mongodb_mongod_extra_info_page_faults_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or increase(mongodb_mongos_extra_info_page_faults_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n  or increase(mongodb_extra_info_page_faults_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\"}[$__range])\n) > 0\n",
     "legendFormat": "{{instance}} - Faults"
    }
   ]
  }
 ]
}