{
 "title": "MongoDB cluster",
 "tags": [ "mongodb-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mongodb_up{}, job)"
   },
   {
    "name": "mongodb_cluster",
    "label": "MongoDB cluster",
    "query": "label_values(mongodb_up{job=~\"$job\"}, mongodb_cluster)"
   },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(mongodb_up{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}, service_name)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "shard",
    "label": "Shard",
    "query": "label_values(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\",service_name=~\"$service_name\", cl_role=\"shardsvr\"}, rs_nm)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Total shards",
   "type": "stat",
   "description": "Total number of shards.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_shards_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded DBs",
   "type": "stat",
   "description": "Number of sharded databases.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_databases_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", type=\"partitioned\"}\n)",
     "legendFormat": "Sharded DBs"
    }
   ]
  },
  {
   "title": "Unsharded DBs",
   "type": "stat",
   "description": "Number of unsharded databases.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_databases_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", type=\"unpartitioned\"}\n)",
     "legendFormat": "Unsharded DBs"
    }
   ]
  },
  {
   "title": "Draining shards",
   "type": "stat",
   "description": "Number of shards being drained.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_shards_draining_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)",
     "legendFormat": "Draining shards"
    }
   ]
  },
  {
   "title": "Sharded collections",
   "type": "stat",
   "description": "Total number of sharded collections.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_collections_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)",
     "legendFormat": "Sharded collections"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "stat",
   "description": "Total number of chunks.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_chunks_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Balancer enabled",
   "type": "stat",
   "description": "Whether the balancer is enabled.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_balancer_enabled{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)",
     "legendFormat": "Cluster balanced"
    }
   ]
  },
  {
   "title": "Balancer running",
   "type": "stat",
   "description": "Whether the balancer is currently running.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster) (\n  mongodb_mongos_sharding_chunks_is_balancer_running{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)",
     "legendFormat": "Balancer running"
    }
   ]
  },
  {
   "title": "Number of collections in shards",
   "type": "table",
   "description": "Number of collections per shard and database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster,db,shard) (\n  mongodb_mongos_db_collections_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}\n)",
     "legendFormat": "{{db}} | {{shard}}"
    }
   ]
  },
  {
   "title": "Size of collections in shards",
   "type": "table",
   "description": "Size of collections per shard and database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (job,mongodb_cluster,db,shard) (\n  mongodb_mongos_db_data_size_bytes{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}\n)",
     "legendFormat": "{{mongodb_cluster}}: Collection size in shards ({{db}} {{shard}})"
    }
   ]
  },
  {
   "title": "Shard services QPS - $shard",
   "type": "timeseries",
   "description": "Queries per second for shard services.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "repeat": "shard",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (rs_nm) (\n  irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", cl_role=\"shardsvr\", rs_nm=~\"$shard\", type!=\"command\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{rs_nm}}"
    }
   ]
  },
  {
   "title": "Config services QPS",
   "type": "timeseries",
   "description": "Queries per second for config services.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", cl_role=\"configsvr\", type!=\"command\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Mongos services QPS",
   "type": "timeseries",
   "description": "Queries per second for mongos services.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", cl_role=\"mongos\", type!=\"command\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Chunks in shards", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "Number of chunks per shard",
   "type": "table",
   "description": "Number of chunks per shard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,shard,db) (\n  mongodb_mongos_sharding_shard_chunks_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}\n)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Chunk count change rate",
   "type": "timeseries",
   "description": "Rate of change in chunk counts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_sharding_shard_chunks_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}[$__rate_interval])",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Chunk split events",
   "type": "timeseries",
   "description": "Rate of chunk split events.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_sharding_changelog_10min_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", event=~\".*split.*\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Chunk move events",
   "type": "timeseries",
   "description": "Rate of chunk move events.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_sharding_changelog_10min_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", event=~\".*moveChunk.*\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Indexes in shards", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 50 } },
  {
   "title": "Number of indexes per shard",
   "type": "table",
   "description": "Number of indexes per shard and database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,db,shard) (\n  mongodb_mongos_db_indexes_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}\n)",
     "legendFormat": "{{db}} | {{shard}}"
    }
   ]
  },
  {
   "title": "Index count change rate",
   "type": "timeseries",
   "description": "Rate of change in index counts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_mongos_db_indexes_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}[$__rate_interval])",
     "legendFormat": "{{shard}}-{{db}}"
    }
   ]
  },
  {
   "title": "Size of indexes per shard",
   "type": "table",
   "description": "Size of indexes per shard and database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,mongodb_cluster,db,shard) (\n  mongodb_mongos_db_index_size_bytes{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}\n)",
     "legendFormat": "{{db}} | {{shard}}"
    }
   ]
  },
  {
   "title": "Index size change rate",
   "type": "timeseries",
   "description": "Rate of change in index sizes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongos_db_index_size_bytes{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", db!~\"admin|config\"}[$__rate_interval])",
     "legendFormat": "{{shard}}-{{db}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 67 } },
  {
   "title": "Current connections per instance",
   "type": "timeseries",
   "description": "Current number of connections per instance.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"current\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Available connections per instance",
   "type": "timeseries",
   "description": "Available connections per instance.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service_name) (max_over_time(mongodb_connections{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"available\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Current connections per shard",
   "type": "timeseries",
   "description": "Current connections aggregated per shard.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (set) (\n  avg by (service_name, set) (mongodb_connections{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"current\"})\n  * on (service_name) group_right\n  avg by (service_name, set) (\n    mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n    / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n  )\n)\n",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 78 } },
  {
   "title": "Operations per shard",
   "type": "timeseries",
   "description": "Operations per second aggregated by shard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (set) (\n  sum by (instance) (\n    irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", type!=\"command\"}[$__rate_interval])\n  )\n  * on (instance) group_right\n  mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n  / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)\n",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Operations by type",
   "type": "timeseries",
   "description": "Operations per second by type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", type!=\"command\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Operations $service_name",
   "type": "timeseries",
   "description": "Operations per second for selected instance.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (type) (irate(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", type!=\"command\", service_name=~\"$service_name\"}[$__rate_interval]))\nand\nsum by (type) (increase(mongodb_op_counters_total{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", type!=\"command\", service_name=~\"$service_name\"}[$__range])) > 0\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 95 } },
  {
   "title": "Cursors per shard",
   "type": "timeseries",
   "description": "Total cursors aggregated by shard.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (set) (\n  sum by (service_name) (\n    mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total\"}\n    or mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total_open\"}\n  )\n  * on (service_name) group_right\n  mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n  / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)\n",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "MongoDB cursors",
   "type": "stat",
   "description": "Total number of open cursors across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max_over_time(mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total\"}[$__rate_interval])\n  or max_over_time(mongodb_mongos_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total\"}[$__rate_interval])\n  or max_over_time(mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total_open\"}[$__rate_interval])\n  or max_over_time(mongodb_mongos_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total_open\"}[$__rate_interval])\n)\n",
     "legendFormat": "Cursors"
    }
   ]
  },
  {
   "title": "Cursors by instance",
   "type": "timeseries",
   "description": "Cursors per instance.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  max_over_time(mongodb_mongod_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total\"}[$__rate_interval])\n  or max_over_time(mongodb_mongos_metrics_cursor_open{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total\"}[$__rate_interval])\n  or max_over_time(mongodb_mongod_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total_open\"}[$__rate_interval])\n  or max_over_time(mongodb_mongos_cursors{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\", state=\"total_open\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Replication lag and oplog window",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 112 }
  },
  {
   "title": "Replication lag by set",
   "type": "timeseries",
   "description": "Maximum replication lag per replica set.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (set) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}[$__rate_interval]) > 0) by (service_name, set))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Replication lag by set oplog window",
   "type": "timeseries",
   "description": "Oplog time window per replica set.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (set) (\n  max by (service_name) (\n    mongodb_mongod_replset_oplog_head_timestamp{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n    - mongodb_mongod_replset_oplog_tail_timestamp{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n  )\n  * on (service_name) group_right\n  mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n  / mongodb_mongod_replset_my_state{job=~\"$job\",mongodb_cluster=~\"$mongodb_cluster\"}\n)\n",
     "legendFormat": "{{set}}"
    }
   ]
  }
 ]
}