{
 "title": "Nomad Cluster",
 "description": "Nomad built-in telemetry https://github.com/dereknex/nomad-grafana",
 "tags": [
  "nomad",
  "host",
  "cluster"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=\"$datacenter\"}, instance)"
    }
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_cpu{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}/(nomad_client_unallocated_cpu{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}+nomad_client_allocated_cpu{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_memory{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}/(nomad_client_unallocated_memory{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}+nomad_client_allocated_memory{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"})"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_unallocated_disk{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}/(nomad_client_unallocated_disk{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}+nomad_client_allocated_disk{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"})"
    }
   ]
  },
  { "title": "Host Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_uptime{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 7 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nomad_client_host_cpu_idle{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}) / count(nomad_client_host_cpu_idle{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 7 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nomad_client_host_memory_free{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "nomad_client_host_memory_used{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nomad_client_host_memory_available{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 7 },
   "repeat": "host",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  {
   "title": "Disk Inodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 7 },
   "repeat": "host",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_inodes_percent{datacenter=\"$datacenter\", instance=\"$instance\", service=\"nomad-client\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}