{
 "title": "Nomad Jobs",
 "description": "Nomad Jobs metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "CPU Total Ticks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_ticks{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_rss{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_cache{instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}