{
 "title": "Cilium / Components / External HA FQDN Proxy",
 "description": "Dashboard for Cilium Enterprise v1.12 (https://cilium.io/) HA FQDN Proxy metrics",
 "tags": [ "cilium-agent" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(isovalent_external_dns_proxy_update_queue_size, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(isovalent_external_dns_proxy_update_queue_size{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(isovalent_external_dns_proxy_update_queue_size{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "External FQDN Update High Queue ",
   "type": "stat",
   "description": "This contains HA FQDN Pods that have a high queue of backed up requests to process. Extended periods of non-zero queue size likely indicate problems with the HA FQDN Proxy or with Cilium Enterprise itself. ",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Queued" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(isovalent_external_dns_proxy_update_queue_size{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External FQDN Proxy Update Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(isovalent_external_dns_proxy_update_errors_total{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])) by (error)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Top HA DNS Proxy Agent Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($k, sum(isovalent_external_dns_proxy_processing_duration_seconds{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (pod))",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Top External FQDN Update Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($k, sum(isovalent_external_dns_proxy_update_queue_size{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top HA DNS Proxy Agent Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(isovalent_external_dns_proxy_processing_duration_seconds{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "HA DNS Policy L7 Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(isovalent_external_dns_proxy_policy_l7_total{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval])) by (rule)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "P95 HA DNS Proxy Upstream Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, isovalent_external_dns_proxy_processing_duration_seconds{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "P95"
    },
    {
     "expr": "quantile(0.75, isovalent_external_dns_proxy_processing_duration_seconds{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "P75"
    },
    {
     "expr": "quantile(0.50, isovalent_external_dns_proxy_processing_duration_seconds{pod=~\"$pod\", namespace=~\"$namespace\", cluster=~\"$cluster\"})",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}