{
 "title": "WSO2 Siddhi Overall Statistics",
 "tags": [
  "wso2-streaming-integrator-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"},instance)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"},app)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"}, type)"
    }
   },
   {
    "name": "metrics",
    "label": "Metrics",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"}, metrics)"
    }
   },
   {
    "name": "element",
    "label": "Element",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"}, element)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"}, quantile)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"}, operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<b><h5> Server Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Servers Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=~\"integrations/wso2-streaming-integrator\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Siddhi Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count(count by (app,instance) (siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"})))"
    }
   ]
  },
  {
   "title": "Server Statistics Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{job=~\"$job\", instance=~\"$instance\",type=\"source\",operation!=\"inMemory\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_system_load_average{job=~\"$job\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_cpu_load_system{job=~\"$job\", instance=~\"$instance\"}) by (insance)"
    },
    {
     "expr": "sum(jvm_memory_heap_usage{job=~\"$job\", instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Overall Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{type=\"source\",operation!=\"inMemory\",job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "overall throughput{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_os_system_load_average{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "system load average{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jvm_os_cpu_load_process{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "cpu process load{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_heap_usage{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "memory heap usage{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_threads_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_threads_blocked_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_used{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "File Descriptors open",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_os_file_descriptor_open_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<b><h5> Stream Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stream Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stream Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<b><h5> Query Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(siddhi_query_memory{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_query_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(siddhi_query_memory{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "options": {
    "content": "<b><h5> Source & Source Mapper Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source Mapper Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(siddhi_sourcemapper_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation,operationType)"
    },
    {
     "expr": "sum(siddhi_source_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(siddhi_source_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "<b><h5> Sink Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sink Mapper Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(siddhi_sinkmapper_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation,operationType)"
    },
    {
     "expr": "sum(siddhi_sink_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sink Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(siddhi_sink_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "options": {
    "content": "<b><h5> Table Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(siddhi_table_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation)"
    },
    {
     "expr": "sum(siddhi_table_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element,operation)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(count by (element) (siddhi_table_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\",element!~\".*SECONDS|.*MINUTES|.*HOURS|.*DAYS|.*MONTHS|.*YEARS\"})))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "<b><h5> Aggregation Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aggregation Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(siddhi_aggregation_memory{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_aggregation_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    },
    {
     "expr": "sum(siddhi_aggregation_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app,element)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aggregation Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(count by (element) (siddhi_aggregation_throughput_total{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"})))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "options": {
    "content": "<b><h5> On-Demand Query Statistics</h5></b>\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "On-Demand Query Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(siddhi_ondemandquery_latency{job=~\"$job\", instance=~\"$instance\",app=~\"$application\"}) by (app)"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 76 },
   "targets": [
    {}
   ]
  }
 ]
}