{
 "title": "Istio overview",
 "tags": [ "istio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(istiod_uptime_seconds{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(istiod_uptime_seconds{job=~\"$job\"}, cluster)"
   },
   {
    "name": "istiod",
    "label": "Istiod",
    "query": "label_values(pilot_info{job=~\"$job\", cluster=~\"$cluster\"}, pod)"
   },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": "label_values(istio_agent_process_cpu_seconds_total{job=~\"$job\", cluster=~\"$cluster\", pod=~\"istio-egress.*|istio-ingress.*\"}, pod)"
   },
   {
    "name": "proxy",
    "label": "Proxy",
    "query": "label_values(istio_agent_process_cpu_seconds_total{job=~\"$job\", cluster=~\"$cluster\", pod!~\"istio-egress.*|istio-ingress.*\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Proxies",
   "type": "stat",
   "description": "Number of proxies in the Istio system.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (job,cluster) (\n  istio_build{job=~\"$job\",cluster=~\"$cluster\", component=\"proxy\"}\n)"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "stat",
   "description": "Number of gateways in the Istio system.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"Gateway\", event=\"add\"}) - (max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"Gateway\", event=\"delete\"}) or (max(up) * 0))"
    }
   ]
  },
  {
   "title": "Virtual services",
   "type": "stat",
   "description": "Number of virtual services in the Istio system.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"VirtualService\", event=\"add\"}) - (max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"VirtualService\", event=\"delete\"}) or (max(up) * 0))"
    }
   ]
  },
  { "title": "Istio alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 } },
  {
   "title": "Destination rules",
   "type": "stat",
   "description": "Number of destination rules in the Istio system.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"DestinationRule\", event=\"add\"}) - (max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"DestinationRule\", event=\"delete\"}) or (max(up) * 0))"
    }
   ]
  },
  {
   "title": "Service entries",
   "type": "stat",
   "description": "Number of service entries in the Istio system.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"ServiceEntry\", event=\"add\"}) - (max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"ServiceEntry\", event=\"delete\"}) or (max(up) * 0))"
    }
   ]
  },
  {
   "title": "Workload entries",
   "type": "stat",
   "description": "Number of workload entries in the Istio system.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"WorkloadEntry\", event=\"add\"}) - (max(pilot_k8s_cfg_events{job=~\"$job\",cluster=~\"$cluster\", type=\"WorkloadEntry\", event=\"delete\"}) or (max(up) * 0))"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors for various components of the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  process_open_fds{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}\n)",
     "legendFormat": "{{cluster}} - istiod"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_process_open_fds{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}\n)",
     "legendFormat": "{{cluster}} - gateway"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_process_open_fds{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}\n)",
     "legendFormat": "{{cluster}} - proxy"
    }
   ]
  },
  {
   "title": "vCPU usage",
   "type": "timeseries",
   "description": "vCPU usage for various components of the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  rate(process_cpu_seconds_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - istiod"
    },
    {
     "expr": "sum by (job,cluster) (\n  rate(istio_agent_process_cpu_seconds_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - gateway"
    },
    {
     "expr": "sum by (job,cluster) (\n  rate(istio_agent_process_cpu_seconds_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - proxy"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "timeseries",
   "description": "Heap memory information for the various components of the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  go_memstats_heap_alloc_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}\n)",
     "legendFormat": "{{cluster}} - istiod - alloc"
    },
    {
     "expr": "sum by (job,cluster) (\n  go_memstats_heap_inuse_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}\n)",
     "legendFormat": "{{cluster}} - istiod - inuse"
    },
    {
     "expr": "sum by (job,cluster) (\n  go_memstats_heap_sys_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}\n)",
     "legendFormat": "{{cluster}} - istiod - sys"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_go_memstats_heap_alloc_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}\n)",
     "legendFormat": "{{cluster}} - gateway - alloc"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_go_memstats_heap_inuse_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}\n)",
     "legendFormat": "{{cluster}} - gateway - inuse"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_go_memstats_heap_sys_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}\n)",
     "legendFormat": "{{cluster}} - gateway - sys"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_go_memstats_heap_alloc_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}\n)",
     "legendFormat": "{{cluster}} - proxy - alloc"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_go_memstats_heap_inuse_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}\n)",
     "legendFormat": "{{cluster}} - proxy - inuse"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_go_memstats_heap_sys_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}\n)",
     "legendFormat": "{{cluster}} - proxy - sys"
    }
   ]
  },
  {
   "title": "Virtual & resident memory",
   "type": "timeseries",
   "description": "Available virtual memory compared to the resident memory for the various components of the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  process_virtual_memory_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}\n)",
     "legendFormat": "{{cluster}} - istiod - virtual"
    },
    {
     "expr": "sum by (job,cluster) (\n  process_resident_memory_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}\n)",
     "legendFormat": "{{cluster}} - istiod - resident"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_process_virtual_memory_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}\n)",
     "legendFormat": "{{cluster}} - gateway - virtual"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_process_resident_memory_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\"}\n)",
     "legendFormat": "{{cluster}} - gateway - resident"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_process_virtual_memory_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}\n)",
     "legendFormat": "{{cluster}} - proxy - virtual"
    },
    {
     "expr": "sum by (job,cluster) (\n  istio_agent_process_resident_memory_bytes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\"}\n)",
     "legendFormat": "{{cluster}} - proxy - resident"
    }
   ]
  },
  {
   "title": "HTTP/GRPC requests",
   "type": "timeseries",
   "description": "HTTP/GRPC request rate for the components of the Istio system.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  rate(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - gateway"
    },
    {
     "expr": "sum by (job,cluster) (\n  rate(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - proxy"
    }
   ]
  },
  {
   "title": "HTTP response overview",
   "type": "piechart",
   "description": "Recent number of successful (1xx, 2xx, 3xx) vs error (4xx, 5xx) HTTP responses received by various components of the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[123].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - gateway - ok"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$gateway\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[45].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - gateway - error"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[123].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - proxy - ok"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$proxy\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[45].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - proxy - error"
    }
   ]
  },
  { "title": "Control plane", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 31 } },
  {
   "title": "xDS pushes",
   "type": "bargauge",
   "description": "Number of xDS pushes by Istiod over the entire time range for the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_pushes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\", type=\"cds\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - CDS"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_pushes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\", type=\"eds\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - EDS"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_pushes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\", type=\"lds\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - LDS"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_pushes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\", type=\"rds\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - RDS"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_pushes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\", type=\"sds\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - SDS"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_pushes{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\", type=\"nds\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - NDS"
    }
   ]
  },
  {
   "title": "xDS push delay (s)",
   "type": "histogram",
   "description": "The latency of xDS pushes by Istiod over the entire time range for the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le, job, cluster) (increase(pilot_proxy_convergence_time_bucket{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__range:]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Galley validations",
   "type": "bargauge",
   "description": "Number of galley validations over the entire time range for the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  increase(galley_validation_passed{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - passed"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(galley_validation_failed{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - failed"
    }
   ]
  },
  {
   "title": "xDS envoy throughput",
   "type": "timeseries",
   "description": "The send and receive data rates from all envoy proxies in the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  rate(envoy_cluster_upstream_cx_rx_bytes_total{job=~\"$job\",cluster=~\"$cluster\", cluster_name=\"xds-grpc\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - sent"
    },
    {
     "expr": "sum by (job,cluster) (\n  rate(envoy_cluster_upstream_cx_tx_bytes_total{job=~\"$job\",cluster=~\"$cluster\", cluster_name=\"xds-grpc\"}[$__rate_interval])\n)",
     "legendFormat": "{{cluster}} - received"
    }
   ]
  },
  {
   "title": "xDS errors / $__interval",
   "type": "timeseries",
   "description": "The xDS related errors across the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_cds_reject{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - CDS reject"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_eds_reject{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - EDS reject"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_rds_reject{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - RDS reject"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_lds_reject{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - LDS reject"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_xds_write_timeout{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - write timeout"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_total_xds_internal_errors{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - internal"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_total_xds_rejects{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - proxy rejects"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_conflict_inbound_listener{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - in listener conflict"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(pilot_conflict_outbound_listener_tcp_over_current_tcp{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - out listener tcp conflict"
    }
   ]
  },
  {
   "title": "Sidecar injections",
   "type": "bargauge",
   "description": "Number of sidecar injections over the entire time range for the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster) (\n  increase(sidecar_injection_success_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "sum by (job,cluster) (\n  increase(sidecar_injection_failure_total{job=~\"$job\",cluster=~\"$cluster\",pod=~\"$istiod\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{cluster}} - failure"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Services",
   "type": "table",
   "description": "Service details for the Istio system.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(job, cluster, service) (\n  label_replace(\n  rate(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"source\"}[$__rate_interval])\n, \"service\", \"$1\", \"source_canonical_service\", \"(.*)\")\n)"
    },
    {
     "expr": "sum by(job, cluster, service) (\n  label_replace(\n  rate(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"destination\"}[$__rate_interval])\n, \"service\", \"$1\", \"destination_canonical_service\", \"(.*)\")\n)"
    },
    {
     "expr": "sum by(job, cluster, service) (label_replace(increase(istio_request_duration_milliseconds_sum{job=~\"$job\",cluster=~\"$cluster\", reporter=\"source\"}[$__rate_interval]), \"service\", \"$1\", \"source_canonical_service\", \"(.*)\"))\n/\nclamp_min(sum by(job, cluster, service) (label_replace(increase(istio_request_duration_milliseconds_count{job=~\"$job\",cluster=~\"$cluster\", reporter=\"source\"}[$__rate_interval]), \"service\", \"$1\", \"source_canonical_service\", \"(.*)\")), 1)\n"
    },
    {
     "expr": "sum by(job, cluster, service) (label_replace(increase(istio_request_duration_milliseconds_sum{job=~\"$job\",cluster=~\"$cluster\", reporter=\"destination\"}[$__rate_interval]), \"service\", \"$1\", \"destination_canonical_service\", \"(.*)\"))\n/\nclamp_min(sum by(job, cluster, service) (label_replace(increase(istio_request_duration_milliseconds_count{job=~\"$job\",cluster=~\"$cluster\", reporter=\"destination\"}[$__rate_interval]), \"service\", \"$1\", \"destination_canonical_service\", \"(.*)\")), 1)\n"
    },
    {
     "expr": "100 * sum by(job, cluster, service) (label_replace(increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[123].+\"}[$__rate_interval]), \"service\", \"$1\", \"source_canonical_service\", \"(.*)\"))\n/\nclamp_min(sum by(job, cluster, service) (label_replace(increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"source\", request_protocol=\"http\"}[$__rate_interval]), \"service\", \"$1\", \"source_canonical_service\", \"(.*)\")), 1)\n"
    },
    {
     "expr": "100 * sum by(job, cluster, service) (label_replace(increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"[123].+\"}[$__rate_interval]), \"service\", \"$1\", \"destination_canonical_service\", \"(.*)\"))\n/\nclamp_min(sum by(job, cluster, service) (label_replace(increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"destination\", request_protocol=\"http\"}[$__rate_interval]), \"service\", \"$1\", \"destination_canonical_service\", \"(.*)\")), 1)\n"
    },
    {
     "expr": "sum by(job, cluster, service) (\n  label_replace(\n  rate(istio_tcp_received_bytes_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"source\"}[$__rate_interval])\n, \"service\", \"$1\", \"source_canonical_service\", \"(.*)\")\n)"
    },
    {
     "expr": "sum by(job, cluster, service) (\n  label_replace(\n  rate(istio_tcp_sent_bytes_total{job=~\"$job\",cluster=~\"$cluster\", reporter=\"destination\"}[$__rate_interval])\n, \"service\", \"$1\", \"destination_canonical_service\", \"(.*)\")\n)"
    }
   ]
  }
 ]
}