{
 "title": "Istio workloads overview",
 "tags": [ "istio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(istiod_uptime_seconds{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(istiod_uptime_seconds{job=~\"$job\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\"}) by (destination_workload_namespace, source_workload_namespace) or sum(istio_tcp_sent_bytes_total{job=~\"$job\", cluster=~\"$cluster\"}) by (destination_workload_namespace, source_workload_namespace))"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "query_result(sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", source_workload_namespace=~\"$namespace\"}) by (source_canonical_service) or sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\"}) by (destination_canonical_service) or sum(istio_tcp_sent_bytes_total{job=~\"$job\", cluster=~\"$cluster\", source_workload_namespace=~\"$namespace\"}) by (source_canonical_service) or sum(istio_tcp_sent_bytes_total{job=~\"$job\", cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\"}) by (destination_canonical_service))"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "query_result(sum by(source_workload) (istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", source_workload_namespace=~\"$namespace\", source_canonical_service=~\"$service\"}) or sum by(destination_workload) (istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\", destination_service_name=~\"$service\"}) or sum by(source_workload) (istio_tcp_sent_bytes_total{job=~\"$job\", cluster=~\"$cluster\", source_workload_namespace=~\"$namespace\", source_canonical_service=~\"$service\"}) or sum by(destination_workload) (istio_tcp_sent_bytes_total{job=~\"$job\", cluster=~\"$cluster\", destination_workload_namespace=~\"$namespace\", destination_service_name=~\"$service\"}))"
   },
   {
    "name": "client_workload",
    "label": "Client workload",
    "query": "query_result(sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", destination_workload=~\"$workload\"}) by (source_workload) or sum(istio_tcp_received_bytes_total{job=~\"$job\", cluster=~\"$cluster\", destination_workload=~\"$workload\"}) by (source_workload))"
   },
   {
    "name": "server_workload",
    "label": "Server workload",
    "query": "query_result(sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", source_workload=~\"$workload\"}) by (destination_workload) or sum(istio_tcp_received_bytes_total{job=~\"$job\", cluster=~\"$cluster\", source_workload=~\"$workload\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  { "title": "Client details", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "HTTP/GRPC requests sent",
   "type": "timeseries",
   "description": "Rate of HTTP/GRPC requests sent from this workload to server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{source_workload}} -> {{destination_workload}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC request delay",
   "type": "timeseries",
   "description": "Average latency of HTTP/GRPC requests sent from this workload to server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, source_workload, destination_workload) (increase(istio_request_duration_milliseconds_sum{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval]))\n/\nclamp_min(sum by(job, cluster, source_workload, destination_workload) (increase(istio_request_duration_milliseconds_count{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval])), 1)\n",
     "legendFormat": "{{source_workload}} -> {{destination_workload}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC request throughput",
   "type": "timeseries",
   "description": "Rate of HTTP/GRPC request data sent from this workload to server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_request_bytes_sum{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{source_workload}} -> {{destination_workload}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC response throughput",
   "type": "timeseries",
   "description": "Rate of HTTP/GRPC response data received by this workload from server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_response_bytes_sum{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}"
    }
   ]
  },
  {
   "title": "HTTP response overview",
   "type": "piechart",
   "description": "Overview of the types of HTTP responses received by this workload from server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[123].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (ok)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"[45].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (error)"
    }
   ]
  },
  {
   "title": "HTTP responses / $__interval",
   "type": "timeseries",
   "description": "The types of HTTP responses received by this workload from server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"1.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (1xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"2.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (2xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"3.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (3xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"4.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (4xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", request_protocol=\"http\", response_code=~\"5.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (5xx)"
    }
   ]
  },
  {
   "title": "GRPC response overview",
   "type": "piechart",
   "description": "Overview of the types of GRPC responses received by this workload from server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", grpc_response_status=\"0\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (ok)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", grpc_response_status=~\"[1-9]\\\\d*\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: (error)"
    }
   ]
  },
  {
   "title": "GRPC responses / $__interval",
   "type": "timeseries",
   "description": "The types of GRPC responses received by this workload from server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\", grpc_response_status=~\"[0-9]\\\\d*\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}: {{grpc_response_status}}"
    }
   ]
  },
  {
   "title": "TCP request throughput",
   "type": "timeseries",
   "description": "Rate of TCP request data sent from this workload to server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_tcp_received_bytes_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{source_workload}} -> {{destination_workload}}"
    }
   ]
  },
  {
   "title": "TCP response throughput",
   "type": "timeseries",
   "description": "Rate of TCP response data received by this workload from server workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_tcp_sent_bytes_total{job=~\"$job\",cluster=~\"$cluster\",source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",destination_workload=~\"$server_workload\", reporter=\"source\"}[$__rate_interval])\n)",
     "legendFormat": "{{source_workload}} <- {{destination_workload}}"
    }
   ]
  },
  { "title": "Server details", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 31 } },
  {
   "title": "HTTP/GRPC requests received",
   "type": "timeseries",
   "description": "Rate of HTTP/GRPC requests received by this workload from client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval])\n)",
     "legendFormat": "{{destination_workload}} <- {{source_workload}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC request delay",
   "type": "timeseries",
   "description": "Average latency of HTTP/GRPC requests received by this workload from client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, source_workload, destination_workload) (increase(istio_request_duration_milliseconds_sum{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval]))\n/\nclamp_min(sum by(job, cluster, source_workload, destination_workload) (increase(istio_request_duration_milliseconds_count{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval])), 1)\n",
     "legendFormat": "{{destination_workload}} <- {{source_workload}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC request throughput",
   "type": "timeseries",
   "description": "Rate of HTTP/GRPC request data received by this workload from client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_request_bytes_sum{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval])\n)",
     "legendFormat": "{{destination_workload}} <- {{source_workload}}"
    }
   ]
  },
  {
   "title": "HTTP/GRPC response throughput",
   "type": "timeseries",
   "description": "Rate of HTTP/GRPC response data sent from this workload to client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_response_bytes_sum{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval])\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}"
    }
   ]
  },
  {
   "title": "HTTP response overview",
   "type": "piechart",
   "description": "Overview of the types of HTTP responses sent from this workload to client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"[123].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (ok)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"[45].+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (error)"
    }
   ]
  },
  {
   "title": "HTTP responses / $__interval",
   "type": "timeseries",
   "description": "The types of HTTP responses sent from this workload to client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"1.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (1xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"2.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (2xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"3.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (3xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"4.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (4xx)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", request_protocol=\"http\", response_code=~\"5.+\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (5xx)"
    }
   ]
  },
  {
   "title": "GRPC response overview",
   "type": "piechart",
   "description": "Overview of the types of GRPC responses sent from this workload to client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", grpc_response_status=\"0\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (ok)"
    },
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", grpc_response_status=~\"[1-9]\\\\d*\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: (error)"
    }
   ]
  },
  {
   "title": "GRPC responses / $__interval",
   "type": "timeseries",
   "description": "The types of GRPC responses sent from this workload to client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  increase(istio_requests_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\", grpc_response_status=~\"[0-9]\\\\d*\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}: {{grpc_response_status}}"
    }
   ]
  },
  {
   "title": "TCP request throughput",
   "type": "timeseries",
   "description": "Rate of TCP request data received by this workload from client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_tcp_received_bytes_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval])\n)",
     "legendFormat": "{{destination_workload}} <- {{source_workload}}"
    }
   ]
  },
  {
   "title": "TCP response throughput",
   "type": "timeseries",
   "description": "Rate of TCP response data sent from this workload to client workloads in the Istio system.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,source_workload,destination_workload) (\n  rate(istio_tcp_sent_bytes_total{job=~\"$job\",cluster=~\"$cluster\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$workload\",source_workload=~\"$client_workload\", reporter=\"destination\"}[$__rate_interval])\n)",
     "legendFormat": "{{destination_workload}} -> {{source_workload}}"
    }
   ]
  }
 ]
}