{
 "title": "Docker overview",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_last_seen{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(container_last_seen{job=~\"$job\"}, instance)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(container_last_seen{ name!=\"\",job=~\"$job\",instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total number of running containers last seen by the exporter.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(container_last_seen{job=~\"$job\",instance=~\"$instance\", name!=\"\"})",
     "legendFormat": "{{instance}}: Containers"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "description": "Total number of distinct images found across running containers.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "count (sum by (image) (container_last_seen{job=~\"$job\",instance=~\"$instance\", name!=\"\"}))",
     "legendFormat": "{{instance}}: Images"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance, name) (rate(container_cpu_usage_seconds_total{job=~\"$job\",instance=~\"$instance\", name!=\"\"}[$__rate_interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory reserved",
   "type": "stat",
   "description": "Memory reserved by the containers on the machine.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  container_spec_memory_reservation_limit_bytes{job=~\"$job\",instance=~\"$instance\", name!=\"\"}\n  )\n/ \navg(\n    machine_memory_bytes{job=~\"$job\",instance=~\"$instance\"}\n) * 100\n",
     "legendFormat": "{{instance}}: Memory reserved"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "description": "Memory used by all containers out of machine total.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum by (instance) (container_memory_usage_bytes{job=~\"$job\",instance=~\"$instance\", name!=\"\"})\n  /\n  avg by (instance) (machine_memory_bytes{job=~\"$job\",instance=~\"$instance\"})\n) * 100\n",
     "legendFormat": "{{instance}}: Memory used"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 20, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU time consumed in seconds by container.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "100 *\n  rate(container_cpu_usage_seconds_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed by container.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 13 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Network traffic (bits per sec) measures data transmitted and received.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 *\n  rate(container_network_receive_bytes_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}/{{interface}} receive"
    },
    {
     "expr": "8 *\n  rate(container_network_transmit_bytes_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])\n",
     "legendFormat": "{{name}}/{{interface}} transmit"
    }
   ]
  },
  {
   "title": "Network errors and drops",
   "type": "timeseries",
   "description": "Network errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_dropped_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} rx drops"
    },
    {
     "expr": "rate(container_network_transmit_packets_dropped_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} tx drops"
    },
    {
     "expr": "rate(container_network_receive_errors_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} rx errors"
    },
    {
     "expr": "rate(container_network_transmit_errors_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{interface}} tx errors"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 21 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "Disk space usage is the amount of storage being used on a device's hard drive or storage medium, in bytes.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}}/{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "The number of I/O requests per second for the device/volume.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{device}} read"
    },
    {
     "expr": "rate(container_fs_writes_total{ name!=\"\",job=~\"$job\",instance=~\"$instance\",name=~\"$name\"}[$__rate_interval])",
     "legendFormat": "{{name}}/{{device}} write"
    }
   ]
  }
 ]
}