{
 "title": "vSphere overview",
 "tags": [ "vsphere" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{}, job)"
   },
   {
    "name": "vcenter_datacenter_name",
    "label": "Datacenter",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{,job=~\"$job\"}, vcenter_datacenter_name)"
   },
   {
    "name": "top_resource_count",
    "label": "Top resource count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "stat",
   "description": "The number of clusters in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vcenter_cluster_name) (\n  vcenter_cluster_vm_count{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)\n)"
    }
   ]
  },
  {
   "title": "ESXi hosts",
   "type": "stat",
   "description": "The number of ESXi hosts in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vcenter_host_name) (\n  vcenter_host_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Resource pools",
   "type": "stat",
   "description": "The number of resource pools in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vcenter_resource_pool_inventory_path) (\n  vcenter_resource_pool_cpu_shares{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)\n)"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "stat",
   "description": "The number of virtual machines in the datacenter.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (vcenter_resource_pool_inventory_path,vcenter_virtual_app_inventory_path,vcenter_vm_name) (\n  vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)\n)"
    }
   ]
  },
  {
   "title": "Clustered VMs on",
   "type": "stat",
   "description": "The number of virtual machines currently powered on that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name) (\n  vcenter_cluster_vm_count{power_state=\"on\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    }
   ]
  },
  {
   "title": "Clustered VMs off",
   "type": "stat",
   "description": "The number of virtual machines currently powered off that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name) (\n  vcenter_cluster_vm_count{power_state=\"off\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    }
   ]
  },
  {
   "title": "Clustered VMs suspended",
   "type": "stat",
   "description": "The number of virtual machines currently in a suspended state that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name) (\n  vcenter_cluster_vm_count{power_state=\"suspended\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    }
   ]
  },
  {
   "title": "Clustered VM templates",
   "type": "stat",
   "description": "The number of virtual machine templates that belong to a cluster in the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name) (\n  vcenter_cluster_vm_template_count{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    }
   ]
  },
  {
   "title": "Clustered active ESXi hosts",
   "type": "stat",
   "description": "The number of ESXi hosts that are currently running (responding and not in maintenance mode) that belong to a cluster within the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name) (\n  vcenter_cluster_host_count{effective=\"true\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    }
   ]
  },
  {
   "title": "Clustered inactive ESXi hosts",
   "type": "stat",
   "description": "The number of ESXi hosts that are currently not running (not responding or in maintenance mode) that belong to a cluster within the datacenter.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name) (\n  vcenter_cluster_host_count{effective=\"false\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    }
   ]
  },
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 } },
  {
   "title": "Top CPU utilization by cluster",
   "type": "timeseries",
   "description": "The clusters with the highest CPU utilization percentage in the datacenter.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, (100 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_cpu_usage_MHz{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_cpu_limit{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    }
   ]
  },
  {
   "title": "Top memory utilization by cluster",
   "type": "timeseries",
   "description": "The clusters with the highest memory utilization percentage in the datacenter.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, (104857600 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_memory_usage_mebibytes{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_memory_limit_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    }
   ]
  },
  {
   "title": "Clusters table",
   "type": "table",
   "description": "Information about the clusters in the vCenter environment.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "vcenter_cluster_cpu_limit{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "topk ($top_resource_count, (100 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_cpu_usage_MHz{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_cpu_limit{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "vcenter_cluster_memory_limit_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "topk ($top_resource_count, (104857600 * sum by (job, vcenter_datacenter_name, vcenter_cluster_name) (vcenter_host_memory_usage_mebibytes{vcenter_cluster_name!=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(vcenter_cluster_memory_limit_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"},1)))",
     "legendFormat": "{{vcenter_cluster_name}}"
    },
    {
     "expr": "vcenter_cluster_host_count{effective=\"true\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_host_count{effective=\"false\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_vm_count{power_state=\"on\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_vm_count{power_state=\"off\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_cluster_vm_count{power_state=\"suspended\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    }
   ]
  },
  { "title": "Resource pools", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 21 } },
  {
   "title": "Top CPU usage by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest CPU usage in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  vcenter_resource_pool_cpu_usage{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  {
   "title": "Top memory usage by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest memory usage in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  vcenter_resource_pool_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  {
   "title": "Top CPU shares by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest amount of CPU shares allocated in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  vcenter_resource_pool_cpu_shares{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  {
   "title": "Top memory shares by resource pools",
   "type": "timeseries",
   "description": "The resource pools with the highest amount of memory shares allocated in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "shares" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  vcenter_resource_pool_memory_shares{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}"
    }
   ]
  },
  { "title": "ESXi hosts", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 38 } },
  {
   "title": "Top CPU utilization by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest CPU utilization in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  vcenter_host_cpu_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Top memory utilization by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest memory utilization in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  vcenter_host_memory_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Top avg disk latency by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest average disk latency in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, \n  sum by (job,vcenter_datacenter_name,vcenter_cluster_name,vcenter_host_name) (\n  vcenter_host_disk_latency_avg_milliseconds{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)\n)",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  {
   "title": "Top packet errors by ESXi hosts",
   "type": "timeseries",
   "description": "The ESXi hosts with the highest percentage of packet errors in the datacenter.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk ($top_resource_count, sum by (job, vcenter_datacenter_name, vcenter_cluster_name, vcenter_host_name) (vcenter_host_network_packet_error_rate{object=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}) / clamp_min(sum by (job, vcenter_datacenter_name, vcenter_cluster_name, vcenter_host_name) (vcenter_host_network_packet_rate{object=\"\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}), 1))",
     "legendFormat": "{{vcenter_host_name}}"
    }
   ]
  },
  { "title": "Datastores", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 55 } },
  {
   "title": "Datastores table",
   "type": "table",
   "description": "Information about the datastores in the vCenter environment.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (job,vcenter_datacenter_name,vcenter_datastore_name) (\n  vcenter_datastore_disk_usage_bytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}\n)"
    },
    {
     "expr": "vcenter_datastore_disk_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    },
    {
     "expr": "vcenter_datastore_disk_usage_bytes{disk_state=\"available\",job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}"
    }
   ]
  }
 ]
}