{
 "title": "vSphere virtual machines",
 "tags": [ "vsphere" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{}, job)"
   },
   {
    "name": "vcenter_datacenter_name",
    "label": "Vcenter_datacenter_name",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{job=~\"$job\"}, vcenter_datacenter_name)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "vcenter_cluster_name",
    "label": "vSphere cluster",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\"}, vcenter_cluster_name)"
   },
   {
    "name": "vcenter_host_name",
    "label": "ESXi host",
    "query": "query_result(sum(vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\"}) by (vcenter_host_name))"
   },
   {
    "name": "vcenter_resource_pool_inventory_path",
    "label": "Resource pool",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\"}, vcenter_resource_pool_inventory_path)"
   },
   {
    "name": "vcenter_virtual_app_inventory_path",
    "label": "Virtual app",
    "query": "label_values(vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\"}, vcenter_virtual_app_inventory_path)"
   },
   {
    "name": "vcenter_vm_name",
    "label": "Virtual machine",
    "query": "query_result((sum(label_join(sgn(sum by(vcenter_resource_pool_inventory_path,vcenter_vm_name) (vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path\",vcenter_resource_pool_inventory_path!=\"\"})),\"vm_path\",\"/\",\"vcenter_resource_pool_inventory_path\",\"vcenter_vm_name\")) by (vm_path,vcenter_vm_name)) or (sum(label_join(sgn(sum by(vcenter_virtual_app_inventory_path,vcenter_vm_name) (vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path\",vcenter_virtual_app_inventory_path!=\"\"})),\"vm_path\",\"/\",\"vcenter_virtual_app_inventory_path\",\"vcenter_vm_name\")) by (vm_path,vcenter_vm_name)) or (sum(label_replace(sgn(sum by(vcenter_resource_pool_inventory_path,vcenter_virtual_app_inventory_path,vcenter_vm_name) (vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=\"\"})),\"vm_path\",\"$1\",\"vcenter_vm_name\",\"(.*)\")) by (vm_path,vcenter_vm_name)))"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The amount of CPU used by the VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "vcenter_vm_cpu_usage_MHz{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "The CPU utilization percentage of VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_cpu_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "The amount of memory used by the VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "vcenter_vm_memory_usage_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "The memory utilization percentage of the VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_memory_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Modified memory",
   "type": "timeseries",
   "description": "The amount of memory that has been swapped or ballooned on the VMs.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "vcenter_vm_memory_ballooned_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"} != 0",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}} - ballooned"
    },
    {
     "expr": "vcenter_vm_memory_swapped_mebibytes{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"} != 0",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}} - swapped"
    }
   ]
  },
  {
   "title": "Avg network throughput rate",
   "type": "timeseries",
   "description": "The 20s average rate of data transmitted or received over the network of the VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "vcenter_vm_network_throughput_bytes_per_sec{direction=\"received\", object=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}} - received"
    },
    {
     "expr": "vcenter_vm_network_throughput_bytes_per_sec{direction=\"transmitted\", object=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}} - transmitted"
    }
   ]
  },
  {
   "title": "Avg packet drops",
   "type": "timeseries",
   "description": "The 20s average of received or transmitted packets dropped over the VMs network compared to the overall packets received or transmitted.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_network_packet_drop_rate{direction=\"received\", object=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"} / clamp_min(vcenter_vm_network_packet_rate{direction=\"received\", object=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}, 1) != 0",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}} - received"
    },
    {
     "expr": "vcenter_vm_network_packet_drop_rate{direction=\"transmitted\", object=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"} / clamp_min(vcenter_vm_network_packet_rate{direction=\"transmitted\", object=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}, 1) != 0",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}} - transmitted"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The amount of disk space used by the VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vcenter_vm_disk_usage_bytes{disk_state=\"used\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "timeseries",
   "description": "The disk utilization percentage of VMs.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vcenter_vm_disk_utilization_percent{job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path|\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path|\",vcenter_vm_name=~\"$vcenter_vm_name\"}",
     "legendFormat": "{{vcenter_resource_pool_inventory_path}}{{vcenter_virtual_app_inventory_path}}/{{vcenter_vm_name}}"
    }
   ]
  },
  {
   "title": "Disks table",
   "type": "table",
   "description": "Information about the disks associated with the virtual machines.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "label_join(vcenter_vm_disk_throughput{direction=\"read\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_resource_pool_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_throughput{direction=\"read\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_virtual_app_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_throughput{direction=\"read\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_vm_name\",\"object\")"
    },
    {
     "expr": "label_join(vcenter_vm_disk_latency_avg_milliseconds{direction=\"read\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_resource_pool_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_latency_avg_milliseconds{direction=\"read\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_virtual_app_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_latency_avg_milliseconds{direction=\"read\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_vm_name\",\"object\")"
    },
    {
     "expr": "label_join(vcenter_vm_disk_throughput{direction=\"write\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_resource_pool_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_throughput{direction=\"write\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_virtual_app_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_throughput{direction=\"write\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_vm_name\",\"object\")"
    },
    {
     "expr": "label_join(vcenter_vm_disk_latency_avg_milliseconds{direction=\"write\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=~\"$vcenter_resource_pool_inventory_path\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_resource_pool_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_latency_avg_milliseconds{direction=\"write\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=~\"$vcenter_virtual_app_inventory_path\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_virtual_app_inventory_path\",\"vcenter_vm_name\",\"object\") or label_join(vcenter_vm_disk_latency_avg_milliseconds{direction=\"write\", object!=\"\", job=~\"$job\",vcenter_datacenter_name=~\"$vcenter_datacenter_name\",vcenter_cluster_name=~\"$vcenter_cluster_name|\",vcenter_host_name=~\"$vcenter_host_name\",vcenter_resource_pool_inventory_path=\"\",vcenter_virtual_app_inventory_path=\"\",vcenter_vm_name=~\"$vcenter_vm_name\"}, \"disk_path\", \"/\", \"vcenter_vm_name\",\"object\")"
    }
   ]
  }
 ]
}