{
 "title": "SNMP Overview",
 "tags": [ "snmp-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(snmp_scrape_duration_seconds, job_snmp)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(snmp_scrape_duration_seconds{job_snmp=~\"$job\"}, instance)"
   },
   {
    "name": "snmp_target",
    "label": "SNMP Target",
    "query": "label_values(snmp_scrape_duration_seconds{job_snmp=~\"$job\", instance=~\"$instance\"}, snmp_target)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "label_values(ifType_info{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\"}, ifDescr)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "description": "The time since the network management portion of the system was last re-initialized.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\"} * 10"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "description": "The maximum number of bytes transmitted out of all interfaces, including framing characters.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "description": "The maximum number of bytes transmitted into all interfaces, including framing characters.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "description": "The total number of bytes transmitted out of all interfaces, including framing characters.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "description": "The total number of bytes transmitted into all interfaces, including framing characters.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Interfaces Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Interface Operational Status",
   "type": "stat",
   "description": "Shows the current operational state of the interface.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Per Interface Traffic (Current)",
   "type": "timeseries",
   "description": "Current traffic per interface (In values are represented as negative).",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ifDescr}} Out"
    },
    {
     "expr": "-irate(ifHCInOctets{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}[$__rate_interval])",
     "legendFormat": "{{ifDescr}} In"
    }
   ]
  },
  {
   "title": "Interface Specific Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Device Interfaces Information",
   "type": "table",
   "description": "General information of all the interfaces of the target device.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by (ifDescr, ifType) (ifType_info{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"})"
    },
    {
     "expr": "max by (ifDescr) (ifHighSpeed{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"})"
    },
    {
     "expr": "count by (ifDescr, ifPhysAddress) (ifPhysAddress{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"})"
    },
    {
     "expr": "max by (ifDescr) (ifMtu{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"})"
    }
   ]
  },
  {
   "title": "Interfaces Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Errors Out",
   "type": "stat",
   "description": "The number of outbound packets that contained errors preventing them from being deliverable to a higher-layer protocol.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOutErrors{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Total Errors In",
   "type": "stat",
   "description": "the number of inbound packets that contained errors preventing them from being deliverable to a higher-layer protocol.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifInErrors{job_snmp=~\"$job\", instance=~\"$instance\", snmp_target=~\"$snmp_target\", ifDescr=~\"$interface\"}",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  }
 ]
}