{
 "title": "Discourse overview",
 "description": "Overview of Discourse application performance and traffic.",
 "tags": [ "discourse-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(discourse_page_views{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(discourse_page_views{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Traffic by response code",
   "type": "timeseries",
   "description": "Rate of HTTP traffic over time for the entire application. Grouped by response code.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job,status) (\n  rate(discourse_http_requests{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{ api }} - {{ verb }} - {{ status }}"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "description": "Active web requests for the entire application",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  discourse_active_app_reqs{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queued requests",
   "type": "timeseries",
   "description": "Queued web requests for the entire application.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  discourse_queued_app_reqs{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page views",
   "type": "timeseries",
   "description": "Rate of pageviews for the entire application. Grouped by type and service.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(discourse_page_views{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 } },
  {
   "title": "Latest median request time",
   "type": "timeseries",
   "description": "The median amount of time for \"latest\" page requests for the selected site.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  discourse_http_duration_seconds{job=~\"$job\",instance=~\"$instance\",quantile=\"0.5\",action=\"latest\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Topic show median request time",
   "type": "timeseries",
   "description": "The median amount of time for \"topics show\" requests for the selected site.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  discourse_http_duration_seconds{job=~\"$job\",instance=~\"$instance\",quantile=\"0.5\",controller=\"topics\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Latest request time percentiles",
   "type": "histogram",
   "description": "The percentiles for the amount of time for \"latest\" page requests for the selected site.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, job, quantile) (discourse_http_duration_seconds{job=~\"$job\",instance=~\"$instance\",action=\"latest\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Topic show request time percentiles",
   "type": "histogram",
   "description": "The percentiles for the amount of time for \"topics show\" requests for the selected site.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance, job, quantile) (discourse_http_duration_seconds{job=~\"$job\",instance=~\"$instance\",controller=\"topics\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}