{
 "title": "Discourse jobs processing",
 "description": "Discourse job processing, workers, and memory usage.",
 "tags": [ "discourse-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(discourse_page_views{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(discourse_page_views{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Job statistics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Sidekiq workers",
   "type": "stat",
   "description": "Current number of Sidekiq Workers.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(discourse_rss{type=\"sidekiq\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}}: Sidekiq worker count"
    }
   ]
  },
  {
   "title": "Web workers",
   "type": "stat",
   "description": "Current number of Web Workers.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(discourse_rss{type=\"web\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}}: Web worker count"
    }
   ]
  },
  {
   "title": "Sidekiq queued",
   "type": "stat",
   "description": "Current number of jobs in Sidekiq queue.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (job) (\n  discourse_sidekiq_jobs_enqueued{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Job counts", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 6 } },
  {
   "title": "Scheduled jobs",
   "type": "timeseries",
   "description": "The number of scheduled jobs ran over an interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(discourse_scheduled_job_count{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Sidekiq jobs",
   "type": "timeseries",
   "description": "The amount of sidekiq jobs ran over an interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  increase(discourse_sidekiq_job_count{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 } },
  {
   "title": "Scheduled job duration",
   "type": "timeseries",
   "description": "Time spent in scheduled jobs broken out by job name.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job,job_name) (\n  rate(discourse_scheduled_job_duration_seconds{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Sidekiq job duration",
   "type": "timeseries",
   "description": "Time spent in Sidekiq jobs broken out by job name.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job,job_name) (\n  rate(discourse_sidekiq_job_duration_seconds{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 20 } },
  {
   "title": "Used RSS memory",
   "type": "timeseries",
   "description": "Total RSS Memory used by process. Broken up by pid.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  discourse_rss{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "pid: {{pid}}"
    }
   ]
  },
  {
   "title": "V8 heap size",
   "type": "timeseries",
   "description": "Current heap size of V8 engine. Broken up by process type",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  discourse_v8_used_heap_size{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}