{
 "title": "Consumer Client Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "client_id", "query": { "query": "label_values(client_id)" } },
   { "name": "consumer_group", "label": "consumer_group", "query": { "query": "label_values(group)" } },
   { "name": "topic", "label": "topic", "query": { "query": "label_values(topic)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Disclaimer\n\n⚠️ This dashboard has some sample thresholds, this example is not meant to fit all use cases nor is it meant for production. Think of it as a learning tool to help you become comfortable with the metrics and thresholding.\n"
   }
  },
  {
   "title": "Commit rate",
   "type": "stat",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_failed_authentication_rate{job=\"consumer\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_rate_per_hour{job=\"consumer\", client_id=~\"$client_id\"} + kafka_consumer_consumer_coordinator_metrics_failed_rebalance_rate_per_hour{job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer group lag in records ",
   "type": "graph",
   "description": "Offset lag per consumer group, summed by topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_group_lag{group=~\"$consumer_group\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group lag in seconds ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) ((kafka_consumergroup_group_lag_seconds{group=~\"$consumer_group\"} > 0))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer Commit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Commit latency average",
   "type": "graph",
   "description": "The average time taken for a commit request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "graph",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Consumer Fetch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_fetch_total{job=\"consumer\", client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch size avg",
   "type": "graph",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{topic=~\"$topic\", job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "graph",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{job=\"consumer\", client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Bytes consumed rate",
   "type": "graph",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{job=\"consumer\", topic=~\"$topic\", client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{job=\"consumer\", topic=~\"$topic\", client_id=\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "graph",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{job=\"consumer\", topic!=\"\", client_id=\"$client_id\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "graph",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, instance) (rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{job=\"consumer\", topic!=\"\", client_id=\"$client_id\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}-{{topic}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"consumer\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"consumer\"})"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"producer\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Current connection count",
   "type": "graph",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_connection_count",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "graph",
   "description": "response rate per node\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_node_metrics_response_rate{job=\"consumer\", client_id=~\"$client_id\"}"
    }
   ]
  }
 ]
}