{
 "title": "ksqldb Overview",
 "tags": [ "kafka-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator{job=~\"integrations/kafka-ksqldb|integrations/kafka\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_server_kafkaserver_brokerstate{job=~\"$job\"}, cluster)"
   },
   {
    "name": "kafka_cluster",
    "label": "Kafka_cluster",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\"}, kafka_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "Average number of active queries per server.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_active_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "stat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_running_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Persisted Queries",
   "type": "stat",
   "description": "Num of persisted queries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_persistent_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "stat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries in Error State",
   "type": "stat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Idle Queries",
   "type": "stat",
   "description": "Num of idle queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_idle_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ksql_ksql_metrics_ksql_queries_query_status{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Stopped Queries",
   "type": "stat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Currently Shutting Down Queries",
   "type": "stat",
   "description": "Num of running queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_pending_shutdown_queries{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster liveness",
   "type": "timeseries",
   "description": "Cluster liveness",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_liveness_indicator{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message consumed/sec",
   "type": "timeseries",
   "description": "Message consumed/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_consumed_per_sec{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message produced/sec",
   "type": "timeseries",
   "description": "Message produced/sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ksql_ksql_engine_query_stats_messages_produced_per_sec{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{ job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Poll Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Poll Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Process Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Process Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Commit Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Commit Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "StateStore Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_rate{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put max latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate_rate{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent max latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_fetch_rate{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_fetch_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch max latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_rate{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete max latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_rate{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore max latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_latency_max{job=~\"integrations/kafka-ksqldb|integrations/kafka\",job=~\"$job\",cluster=~\"$cluster\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  }
 ]
}