{
 "title": "Producer Client Metrics",
 "description": "Java client metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "client_id",
    "query": {
     "query": "label_values(kafka_producer_app_info, client_id)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_producer_producer_topic_metrics_byte_total{job=\"producer\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Disclaimer\n\n⚠️ This dashboard has some sample thresholds, this example is not meant to fit all use cases nor is it meant for production. Think of it as a learning tool to help you become comfortable with the metrics and thresholding.\n"
   }
  },
  {
   "title": "Retry rate",
   "type": "stat",
   "description": "The average per-second number of retried record sends for a topic. An increase could signal connectivity problems from the application to the broker. ",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_retry_rate{job=\"producer\",client_id=~\"$client_id\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Record error rate",
   "type": "stat",
   "description": "The average per-second number of record sends that resulted in errors.\n",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_error_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Free buffer space",
   "type": "stat",
   "description": "he total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_buffer_available_bytes{job=\"producer\",client_id=~\"$client_id\"}",
     "legendFormat": "Buffer bytes available"
    }
   ]
  },
  {
   "title": "Produce request throttle average",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg{job=\"producer\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compression rate",
   "type": "stat",
   "description": "The average compression rate of record batches for a topic, defined as the average ratio of the compressed batch size over the uncompressed size.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_compression_rate_avg{job=\"producer\",client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "Produce request latency",
   "type": "graph",
   "description": "The average request latency in ms.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{job=\"producer\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Record queue time",
   "type": "graph",
   "description": "The average time in ms record batches spent in the send buffer.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_queue_time_avg{job=\"producer\",client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed authentication rate",
   "type": "graph",
   "description": "The rate of failed authentication per seconds\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_failed_authentication_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"producer\",env=\"$env\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "decbytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"producer\",env=\"$env\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "percentunit", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"producer\",env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Outgoing byte rate",
   "type": "graph",
   "description": "The average number of bytes sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_outgoing_byte_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing byte rate per topic",
   "type": "graph",
   "description": "The average number of bytes sent per second to the broker per topic.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_byte_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second per topic",
   "type": "graph",
   "description": "The average number of messages sent per second to the broker per topic.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_record_send_total{job=\"producer\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second",
   "type": "graph",
   "description": "The average number of messages sent per second to the broker.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_send_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch size average",
     "type": "graph",
     "description": "The average number of bytes sent per partition per-request.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_size_avg{job=\"producer\",client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Request in flight",
     "type": "graph",
     "description": "The current number of in-flight requests awaiting a response.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_requests_in_flight{job=\"producer\",client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Record size average",
     "type": "graph",
     "description": "The average record size",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_size_avg{job=\"producer\",client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Produce Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce request rate",
     "type": "graph",
     "description": "The average number of requests sent per second to the broker.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_producer_producer_metrics_request_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Produce request size average",
     "type": "graph",
     "description": "The average number of records per request.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_size_avg{job=\"producer\",client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Produce response rate",
     "type": "graph",
     "description": "The average number of response received per second to the broker.\n",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_producer_producer_metrics_response_total{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection rate",
     "type": "graph",
     "description": "The current number of active connections.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_producer_producer_metrics_connection_count{job=\"producer\",client_id=~\"$client_id\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Connection creation rate",
     "type": "graph",
     "description": "New connections established per second in the window.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_creation_rate{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    },
    {
     "title": "Connection close rate",
     "type": "graph",
     "description": "Connections closed per second in the window.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_close_rate{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent doing I/O.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_ratio{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    },
    {
     "title": "IO Wait time average",
     "type": "graph",
     "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.\n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_wait_time_ns_avg{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    },
    {
     "title": "IO Time average",
     "type": "graph",
     "description": "The average length of time for I/O per select call in nanoseconds.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_time_ns_avg{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    },
    {
     "title": "IO Wait Ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent waiting.\n",
     "gridPos": { "h": 7, "w": 8, "x": 4, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_wait_ratio{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    },
    {
     "title": "Select Rate",
     "type": "graph",
     "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_select_rate{job=\"producer\",client_id=~\"$client_id\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Version",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 34 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_producer_app_info{job=\"producer\",client_id=~\"$client_id\",version!=\"\"}",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Metadata max age",
     "type": "graph",
     "description": "The age in seconds of the current producer metadata being used.",
     "gridPos": { "h": 9, "w": 12, "x": 7, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_metadata_age{job=\"producer\",client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}