{
 "title": "Zookeeper overview",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(zookeeper_outstandingrequests, job)"
    }
   },
   {
    "name": "kafka_cluster",
    "label": "Kafka Cluster",
    "query": {
     "query": "label_values(zookeeper_outstandingrequests{job=~\"$job\"}, kafka_cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(zookeeper_outstandingrequests{kafka_cluster=~\"kafka_cluster\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeeper nodes online",
   "type": "stat",
   "description": "Quorum size of zookeeper ensemble or number of nodes online for single instance deployments",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# kafka operator case\ncount(zookeeper_quorumsize{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"})\n# kafka grafana cloud integration case\nor count(zookeeper_status_quorumsize{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"})\n# or single instance case (non-cluster)\nor count(up{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"} == 1)"
    }
   ]
  },
  {
   "title": "Alive connections",
   "type": "stat",
   "description": "Number of alive connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "timeseries",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of watchers",
   "type": "stat",
   "description": "Number of watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "# for strimzi operator: remove kafka container java metrics \nirate(process_cpu_seconds_total{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\", container!=\"kafka\"}[$__rate_interval])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\", container!=\"kafka\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\",area=\"heap\", container!=\"kafka\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "# for strimzi operator: remove kafka container java metrics\nsum without(gc)(rate(jvm_gc_collection_seconds_sum{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\", container!=\"kafka\" }[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request latency - min",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"} * ignoring (minrequestlatency,ticktime)zookeeper_ticktime{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  },
  {
   "title": "Request latency - average",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"} * ignoring (avgrequestlatency,ticktime) zookeeper_ticktime{instance=~\"$instance\",kafka_cluster=~\"kafka_cluster\", job=~\"$job\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  },
  {
   "title": "Request latency - max",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\"} * ignoring (maxrequestlatency,ticktime)\n zookeeper_ticktime{kafka_cluster=~\"kafka_cluster\", job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  }
 ]
}