{
 "title": "OpenStack Neutron",
 "tags": [ "openstack" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(openstack_identity_up{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(openstack_identity_up{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Neutron service", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Neutron status",
   "type": "stat",
   "description": "Reports the status of the Neutron networking service.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_neutron_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "timeseries",
   "description": "The number of networks managed by Neutron.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_neutron_networks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Subnets",
   "type": "timeseries",
   "description": "The number of networks managed by Neutron.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_neutron_subnets{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "timeseries",
   "description": "The number of routers managed by Neutron.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "openstack_neutron_routers{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - total"
    },
    {
     "expr": "openstack_neutron_routers_not_active{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - inactive"
    }
   ]
  },
  {
   "title": "Router details",
   "type": "table",
   "description": "Detailed view of the routers managed by Neutron.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "openstack_neutron_router{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "timeseries",
   "description": "The number of routers managed by Neutron.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "openstack_neutron_ports{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - total"
    },
    {
     "expr": "openstack_neutron_ports_lb_not_active{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - load balancer inactive"
    },
    {
     "expr": "openstack_neutron_ports_no_ips{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - no IPs"
    }
   ]
  },
  {
   "title": "Port details",
   "type": "table",
   "description": "Detailed view of the ports managed by Neutron.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "openstack_neutron_port{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{mac_address}}"
    }
   ]
  },
  {
   "title": "Floating IPs",
   "type": "timeseries",
   "description": "The number of public IP addresses managed by Neutron.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "openstack_neutron_floating_ips{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - total"
    },
    {
     "expr": "openstack_neutron_floating_ips_associated_not_active{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - associated inactive"
    }
   ]
  },
  {
   "title": "IPs used",
   "type": "timeseries",
   "description": "The usage of available IP addresses broken down by subnet.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, instance, ip_version, subnet_name) (openstack_neutron_network_ip_availabilities_used{job=~\"$job\",instance=~\"$instance\"}) / sum by (job, instance, ip_version, subnet_name)(openstack_neutron_network_ip_availabilities_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{subnet_name}}"
    }
   ]
  },
  {
   "title": "Security groups",
   "type": "timeseries",
   "description": "The number of network security groups managed by Neutron.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_neutron_security_groups{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "table",
   "description": "Details for the agents for OpenStack Neutron.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "openstack_neutron_agent_state{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{service}} - {{hostname}}"
    }
   ]
  }
 ]
}