{
 "title": "OpenStack overview",
 "tags": [ "openstack" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(openstack_identity_up{job=\"integrations/openstack\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(openstack_identity_up{job=\"integrations/openstack\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Placement status",
   "type": "stat",
   "description": "Reports the status of the Placement resource-scheduling service.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_placement_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keystone status",
   "type": "stat",
   "description": "Reports the status of the Keystone identity service.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_identity_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nova status",
   "type": "stat",
   "description": "Reports the status of the Nova compute service.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_nova_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Neutron status",
   "type": "stat",
   "description": "Reports the status of the Neutron networking service.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_neutron_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cinder status",
   "type": "stat",
   "description": "Reports the status of the Cinder block storage service.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_cinder_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Glance status",
   "type": "stat",
   "description": "Reports the status of the Glance image service.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_glance_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "description": "Panel to report on the status of firing alerts.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 }
  },
  {
   "title": "Total resources",
   "type": "table",
   "description": "Summary of the hardware resources available and used by OpenStack.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\", resourcetype=\"DISK_GB\"}",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\", resourcetype=\"DISK_GB\"}",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\", resourcetype=\"MEMORY_MB\"}",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\", resourcetype=\"MEMORY_MB\"}",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\", resourcetype=\"VCPU\"}",
     "legendFormat": "{{instance}} - {{hostname}}"
    },
    {
     "expr": "openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\", resourcetype=\"VCPU\"}",
     "legendFormat": "{{instance}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "vCPU used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100*sum(openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\",resourcetype=\"VCPU\"}))/sum(openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\",resourcetype=\"VCPU\"})",
     "legendFormat": "vCPU used %"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100*sum(openstack_placement_resource_usage{job=~\"$job\",instance=~\"$instance\",resourcetype=\"MEMORY_MB\"}))/sum(openstack_placement_resource_total{job=~\"$job\",instance=~\"$instance\",resourcetype=\"MEMORY_MB\"})",
     "legendFormat": "Memory used %"
    }
   ]
  },
  {
   "title": "Free IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "openstack_neutron_network_ip_availabilities_total{job=~\"$job\",instance=~\"$instance\",network_name=~\".+\"}-openstack_neutron_network_ip_availabilities_used{job=~\"$job\",instance=~\"$instance\",network_name=~\".+\"}",
     "legendFormat": "{{network_name}}"
    }
   ]
  },
  { "title": "Keystone service", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 21 } },
  {
   "title": "Domains",
   "type": "stat",
   "description": "The number of domains for the OpenStack cloud.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_domains{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "description": "The number of projects for the OpenStack cloud.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_projects{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "stat",
   "description": "The number of regions for the OpenStack cloud.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_regions{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "description": "The number of users for the OpenStack cloud.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "openstack_identity_users{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Project details",
   "type": "table",
   "description": "Details for the projects in the OpenStack cloud.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "openstack_identity_project_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  { "title": "Glance service", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 38 } },
  {
   "title": "Glance status",
   "type": "stat",
   "description": "Reports the status of the Glance image service.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_glance_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Image count",
   "type": "timeseries",
   "description": "The number of images present in Glance.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 39 },
   "targets": [
    {
     "expr": "openstack_glance_images{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "table",
   "description": "Details for the images in Glance.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "openstack_glance_image_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  }
 ]
}