{
 "title": "Collector overview",
 "tags": [
  "opentelemetry",
  "collector"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(otelcol_process_uptime_seconds_total{service_name!=\"\"}, service_name)"
   },
   {
    "name": "service_instance_id",
    "label": "Service instance id",
    "query": "label_values(otelcol_process_uptime_seconds_total{service_name!=\"\",service_name=~\"$service_name\"}, service_instance_id)"
   },
   { "name": "adhoc", "label": "Extra filters" }
  ]
 },
 "panels": [
  { "title": "Collector overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Fleet overview",
   "type": "table",
   "description": "List of collectors and their queue saturation",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "otelcol_process_uptime_seconds_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}",
     "legendFormat": "{{service_instance_id}}: Uptime"
    },
    {
     "expr": "(max(otelcol_exporter_queue_size{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"} / otelcol_exporter_queue_capacity{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}) by (service_instance_id)) * 100",
     "legendFormat": "{{ service_instance_id }} saturation"
    }
   ]
  },
  { "title": "OpenTelemetry collector alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Receiver count",
   "type": "stat",
   "description": "Total number of receivers",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (receiver) ({__name__=~\"otelcol_receiver_(accepted|refused)_(log_records|metric_points|spans)_total\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}))\n",
     "legendFormat": "Receivers"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Total rate of metrics received (incl. failed)",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum (rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+ sum (rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Proportion of successfully ingested metrics against total received metrics",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n/\n(\nsum(rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)) * 100\n",
     "legendFormat": "Metricsuccess rate"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Total rate of logs received (incl. failed)",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum (rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+ sum (rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Proportion of successfully ingested logs against total received metrics",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n/\n(\nsum(rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)) * 100\n",
     "legendFormat": "Logsuccess rate"
    }
   ]
  },
  {
   "title": "Spans",
   "type": "stat",
   "description": "Total rate of spans received (incl. failed)",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum (rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+ sum (rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n",
     "legendFormat": "Spans"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Proportion of successfully ingested spans against total received metrics",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n/\n(\nsum(rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+\nsum(rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)) * 100\n",
     "legendFormat": "Spansuccess rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-around; width: 100%; font-size: 2em; font-weight: bold\">\n  <span>↓</span>\n  <span>↓</span>\n  <span>↓</span>\n  <span>↓</span>\n  <span>↓</span>\n</div>\n"
   }
  },
  {
   "title": "Processor count",
   "type": "stat",
   "description": "Total number of processors",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (processor) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",__name__=~\"otelcol_processor_(incoming|outgoing)_items_total\"}))\n",
     "legendFormat": "Processors"
    }
   ]
  },
  {
   "title": "Incoming metrics",
   "type": "timeseries",
   "description": "Rate of incoming metrics",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"metrics\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Incoming logs",
   "type": "timeseries",
   "description": "Rate of incoming logs",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"logs\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Incoming traces",
   "type": "timeseries",
   "description": "Rate of incoming traces",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"traces\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-around; width: 100%; font-size: 2em; font-weight: bold\">\n  <span>↓</span>\n  <span>↓</span>\n  <span>↓</span>\n  <span>↓</span>\n  <span>↓</span>\n</div>\n"
   }
  },
  {
   "title": "Exporter count",
   "type": "stat",
   "description": "Total number of exporters",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count by (exporter) (otelcol_exporter_queue_size{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}))\n",
     "legendFormat": "Exporters"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Total rate of metrics exported",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_exporter_sent_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Proportion of successfully exported metrics against total metrics",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(otelcol_exporter_sent_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  /\n  (\n  sum(rate(otelcol_exporter_sent_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  +\n  (sum(rate(otelcol_exporter_send_failed_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])) or vector(0))\n  )\n) * 100\n",
     "legendFormat": "Metricsuccess rate"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "description": "Total rate of logs exported",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_exporter_sent_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Proportion of successfully exported logs against total logs",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(otelcol_exporter_sent_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  /\n  (\n  sum(rate(otelcol_exporter_sent_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  +\n  (sum(rate(otelcol_exporter_send_failed_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])) or vector(0))\n  )\n) * 100\n",
     "legendFormat": "Logsuccess rate"
    }
   ]
  },
  {
   "title": "Spans",
   "type": "stat",
   "description": "Total rate of spans exported",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_exporter_sent_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)",
     "legendFormat": "Spans"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "description": "Proportion of successfully exported spans against total spans",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(otelcol_exporter_sent_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  /\n  (\n  sum(rate(otelcol_exporter_sent_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  +\n  (sum(rate(otelcol_exporter_send_failed_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])) or vector(0))\n  )\n) * 100\n",
     "legendFormat": "Spansuccess rate"
    }
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Ingestion statistics",
   "type": "stat",
   "description": "Per-signal rates of incoming data",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum (rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+ sum (rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n",
     "legendFormat": "Metrics"
    },
    {
     "expr": "sum (rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+ sum (rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n",
     "legendFormat": "Logs"
    },
    {
     "expr": "sum (rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n+ sum (rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n",
     "legendFormat": "Spans"
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "table",
   "description": "Ingested metrics (avg): Total rate of metrics received per receiver  \n\nMetrics refusal rate (avg): Rate of metrics refused  \n\nIngested logs (avg): Total rate of logs received per receiver  \n\nLogs refusal rate (avg): Rate of logs refused  \n\nIngested spans (avg): Total rate of spans received per receiver  \n\nSpans refusal rate (avg): Rate of spans refused",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(\n  sum by (receiver) (rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  + sum by (receiver) (rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  sum by (receiver) (rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  unless sum by (receiver) (rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  sum by (receiver) (rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  unless sum by (receiver) (rate(otelcol_receiver_accepted_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  count by (receiver) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",receiver!=\"\"}) * 0\n)\n",
     "legendFormat": "{{ receiver }} metrics"
    },
    {
     "expr": "sum by (receiver) (rate(otelcol_receiver_refused_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))or\n(\n  count by (receiver) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",receiver!=\"\"}) * 0\n)\n",
     "legendFormat": "{{service_name}}: Metrics refusal rate ({{receiver}})"
    },
    {
     "expr": "(\n  sum by (receiver) (rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  + sum by (receiver) (rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  sum by (receiver) (rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  unless sum by (receiver) (rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  sum by (receiver) (rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  unless sum by (receiver) (rate(otelcol_receiver_accepted_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  count by (receiver) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",receiver!=\"\"}) * 0\n)\n",
     "legendFormat": "{{ receiver }} logs"
    },
    {
     "expr": "sum by (receiver) (rate(otelcol_receiver_refused_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))or\n(\n  count by (receiver) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",receiver!=\"\"}) * 0\n)\n",
     "legendFormat": "{{service_name}}: Logs refusal rate ({{receiver}})"
    },
    {
     "expr": "(\n  sum by (receiver) (rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  + sum by (receiver) (rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  sum by (receiver) (rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  unless sum by (receiver) (rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  sum by (receiver) (rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n  unless sum by (receiver) (rate(otelcol_receiver_accepted_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))\n)\nor\n(\n  count by (receiver) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",receiver!=\"\"}) * 0\n)\n",
     "legendFormat": "{{ receiver }} spans"
    },
    {
     "expr": "sum by (receiver) (rate(otelcol_receiver_refused_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]))or\n(\n  count by (receiver) ({service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\",receiver!=\"\"}) * 0\n)\n",
     "legendFormat": "{{service_name}}: Spans refusal rate ({{receiver}})"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Processing rate",
   "type": "stat",
   "description": "Per-signal rates of incoming data",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"metrics\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}\n[$__rate_interval])\n)",
     "legendFormat": "Metrics"
    },
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"logs\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}\n[$__rate_interval])\n)",
     "legendFormat": "Logs"
    },
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"traces\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}\n[$__rate_interval])\n)",
     "legendFormat": "Spans"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "table",
   "description": "Processing rate breakdown by receiver",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"metrics\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"logs\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_incoming_items_total{otel_signal=\"traces\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_outgoing_items_total{otel_signal=\"metrics\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_outgoing_items_total{otel_signal=\"logs\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "\n  sum by (service_name,processor) (\n  rate(otelcol_processor_outgoing_items_total{otel_signal=\"traces\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (service_name,processor) ({processor!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 61 } },
  {
   "title": "Exporting rate",
   "type": "stat",
   "description": "Per-signal rates of incoming data",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_exporter_sent_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)",
     "legendFormat": "Metrics"
    },
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_exporter_sent_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)",
     "legendFormat": "Logs"
    },
    {
     "expr": "sum by (service_name) (\n  rate(otelcol_exporter_sent_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)",
     "legendFormat": "Spans"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "table",
   "description": "Exporting rate breakdown by exporter",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_sent_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Exported metrics ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_send_failed_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Metrics export failure rate ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_sent_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Exported logs ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_send_failed_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Logs export failure rate ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_sent_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Exported spans ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_send_failed_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Spans export failure rate ({{exporter}})"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "table",
   "description": "**Note: This table only makes sense when selecting a single collector as queue sizes may differ**\nShows metrics of the internal [sending queue](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md) per exporter\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service_name,exporter) (\n  otelcol_exporter_queue_size{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}\n)",
     "legendFormat": "{{service_name}}: Queue size by exporter ({{exporter}})"
    },
    {
     "expr": "avg by (service_name,exporter) (\n  otelcol_exporter_queue_capacity{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}\n)",
     "legendFormat": "{{service_name}}: Queue capacity by exporter ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_enqueue_failed_metric_points_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Metrics enqueue failures ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_enqueue_failed_log_records_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Logs enqueue failures ({{exporter}})"
    },
    {
     "expr": "\n  sum by (service_name,exporter) (\n  rate(otelcol_exporter_enqueue_failed_spans_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval])\n)\nor (count by (exporter) ({exporter!=\"\",service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*0)",
     "legendFormat": "{{service_name}}: Spans enqueue failures ({{exporter}})"
    }
   ]
  },
  {
   "title": "Process overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Process uptime.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "otelcol_process_uptime_seconds_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}",
       "legendFormat": "{{service_instance_id}}: Uptime"
      }
     ]
    },
    {
     "title": "Process start time",
     "type": "stat",
     "description": "Process start time.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (service_name,service_instance_id) (\n  (time()-otelcol_process_uptime_seconds_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"})*1000\n)",
       "legendFormat": "{{service_instance_id}}: Process start time"
      }
     ]
    },
    {
     "title": "CPU usage (process)",
     "type": "timeseries",
     "description": "Process CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (service_name,service_instance_id) (\n  rate(otelcol_process_cpu_seconds_total{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}[$__rate_interval]) * 100\n)",
       "legendFormat": "{{service_instance_id}}: CPU usage (process)"
      }
     ]
    },
    {
     "title": "Process memory used (rss)",
     "type": "timeseries",
     "description": "Process resident memory size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (service_name,service_instance_id) (\n  otelcol_process_memory_rss_bytes{service_name!=\"\",service_name=~\"$service_name\",service_instance_id=~\"$service_instance_id\"}\n)",
       "legendFormat": "{{service_instance_id}}: Process memory used (rss)"
      }
     ]
    }
   ]
  }
 ]
}