{
 "title": "Nomad cluster",
 "tags": [ "nomad-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nomad_client_uptime, job)"
    }
   },
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=\"$datacenter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Allocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU allocated",
   "type": "gauge",
   "description": "CPU allocated on $instance",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocated_cpu{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_cpu{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_cpu{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "gauge",
   "description": "Memory allocated on $instance",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocated_memory{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_memory{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_memory{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Disk allocated",
   "type": "gauge",
   "description": "Disk allocated on $instance",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_allocated_disk{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}/(nomad_client_unallocated_disk{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}+nomad_client_allocated_disk{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "allocs" } },
   "targets": [
    {
     "expr": "sum by (datacenter) (nomad_client_allocations_migrating{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})",
     "legendFormat": "Migrating"
    },
    {
     "expr": "sum by (datacenter) (nomad_client_allocations_blocked{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum by (datacenter) (nomad_client_allocations_pending{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum by (datacenter)  (nomad_client_allocations_running{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum by (datacenter)  (nomad_client_allocations_terminal{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})",
     "legendFormat": "Terminal"
    }
   ]
  },
  {
   "title": "Nomad clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_client_uptime{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-sum(nomad_client_host_cpu_idle{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}) / count(nomad_client_host_cpu_idle{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "nomad_client_host_memory_free{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "nomad_client_host_memory_used{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "nomad_client_host_memory_available{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(nomad_client_host_disk_size{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Total - {{disk}}"
    },
    {
     "expr": "avg(nomad_client_host_disk_available{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "Available - {{disk}}"
    }
   ]
  },
  {
   "title": "Disk inodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nomad_client_host_disk_inodes_percent{job=~\"$job\", datacenter=~\"$datacenter\", instance=~\"$instance\"}) by (disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}