groups:
    - name: CephClusterAlerts
      rules:
        - alert: CephUnhealthyWarning
          annotations:
            description: The Ceph cluster has warning level issues. Run the ceph -s command on any Ceph node to identify the reason and resolve the issue depending on the output.
            summary: The Ceph cluster has warning level issues.
          expr: ceph_health_status == 1
          for: 5m
          labels:
            severity: warning
        - alert: CephUnhealthyCritical
          annotations:
            description: The Ceph cluster has critical issues. Run the ceph -s command on any Ceph node to identify the reason and resolve the issue depending on the output.
            summary: The Ceph cluster has critical issues.
          expr: ceph_health_status == 2
          for: 5m
          labels:
            severity: critical
        - alert: CephDiskLessThan15Left
          annotations:
            description: The Ceph cluster has less than 15% storage space left
            summary: The Ceph cluster has less than 15% storage space left.
          expr: (ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes < 0.15
          for: 5m
          labels:
            severity: warning
        - alert: CephDiskLessThan5Left
          annotations:
            description: The Ceph cluster has less than 5% storage space left
            summary: The Ceph cluster has less than 5% storage space left.
          expr: (ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes < 0.05
          for: 5m
          labels:
            severity: critical
        - alert: OSDNodeDown
          annotations:
            description: The OSD node is down, you won`t have access to the physical disks mounted in this node
            summary: The OSD node is down.
          expr: ceph_osd_up == 0
          for: 5m
          labels:
            severity: warning
        - alert: MDSDown
          annotations:
            description: There's no MDS node available.
            summary: All MDS nodes down.
          expr: count(ceph_mds_metadata == 1) == 0
          for: 5m
          labels:
            severity: warning
