{
 "title": "GitLab Overview",
 "description": "Overview of a GitLab instance.",
 "tags": [ "gitlab-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(gitlab_rails_boot_time_seconds{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(gitlab_rails_boot_time_seconds{job=~\"$job\"}, instance)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(gitlab_rails_boot_time_seconds{job=~\"$job\"}, cluster)"
   },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic by Response Code",
   "type": "timeseries",
   "description": "Rate of HTTP traffic over time, grouped by status.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "User Sessions",
   "type": "timeseries",
   "description": "The rate of user logins.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sessions/s" } },
   "targets": [
    {
     "expr": "rate(user_session_logins_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "description": "Average latency of inbound HTTP requests.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Types",
   "type": "table",
   "description": "Top 5 types of requests to the server.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (feature_category) (rate(http_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "description": "The GitLab rails error logs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/gitlab/gitlab-rails/exceptions_json.log\", job=~\"$job\", instance=~\"$instance\"} | json | line_format \"{{.severity}} {{.exception_class}} - {{.exception_message}}\""
    }
   ]
  },
  { "title": "Pipeline Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Job Activations",
   "type": "timeseries",
   "description": "The number of jobs activated per second.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "activations/s" } },
   "targets": [
    {
     "expr": "rate(gitlab_ci_active_jobs_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{plan}}"
    }
   ]
  },
  {
   "title": "Pipelines Created",
   "type": "timeseries",
   "description": "Rate of pipeline instances created.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pipelines/s" } },
   "targets": [
    {
     "expr": "rate(pipelines_created_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Pipeline Builds Created",
   "type": "timeseries",
   "description": "The number of builds created within a pipeline per second, grouped by source.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "builds/s" } },
   "targets": [
    {
     "expr": "sum by (source) (rate(gitlab_ci_pipeline_size_builds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Build Trace Operations",
   "type": "timeseries",
   "description": "The rate of build trace operations performed, grouped by source.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(gitlab_ci_trace_operations_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}