{
 "title": "OpenTelemetry Collector Health",
 "description": "A dashboard for monitoring the health of OpenTelemetry Collector instances using their internal metrics.",
 "tags": [ "otelcol" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"otelcol_process_uptime.*\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"otelcol_process_uptime.*\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({__name__=~\"otelcol_process_uptime.*\"}, namespace)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"otelcol_process_uptime.*\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Running Collectors",
   "type": "stat",
   "description": "Running Collectors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"otelcol_process_uptime(_seconds_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "Collector uptime",
   "type": "table",
   "description": "Collector uptime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{__name__=~\"otelcol_process_uptime(_seconds_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}\n"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 9 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job, cluster, namespace, instance) (\n    rate(\n        {\n            __name__=~\"otelcol_process_cpu_seconds(_total)?\",\n            job=~\"$job\",\n            cluster=~\"$cluster\",\n            namespace=~\"$namespace\",\n            instance=~\"$instance\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}\n"
    }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "description": "Memory (RSS)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job, cluster, namespace, instance) (\n  {__name__=~\"otelcol_process_memory_rss(_bytes)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}\n)\n",
     "legendFormat": "RSS - {{cluster}} - {{namespace}} - {{instance}}\n"
    }
   ]
  },
  {
   "title": "Memory (Heap Alloc)",
   "type": "timeseries",
   "description": "Memory (Heap Alloc)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job, cluster, namespace, instance) (\n  {__name__=~\"otelcol_process_runtime_total_sys_memory_bytes(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}\n)\n",
     "legendFormat": "RSS - {{cluster}} - {{namespace}} - {{instance}}\n"
    }
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 18 } },
  {
   "title": "Accepted metric points",
   "type": "timeseries",
   "description": "Accepted metric points",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_receiver_accepted_metric_points(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Accepted log records",
   "type": "timeseries",
   "description": "Accepted log records",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_receiver_accepted_log_records(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Accepted spans",
   "type": "timeseries",
   "description": "Accepted spans",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_receiver_accepted_spans(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total incoming items",
   "type": "timeseries",
   "description": "Total incoming items",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_processor_incoming_items(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Refused metric points",
   "type": "timeseries",
   "description": "Refused metric points",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_receiver_refused_metric_points(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Refused log records",
   "type": "timeseries",
   "description": "Refused log records",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_receiver_refused_log_records(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Refused spans",
   "type": "timeseries",
   "description": "Refused spans",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_receiver_refused_spans(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total outgoing items",
   "type": "timeseries",
   "description": "Total outgoing items",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_processor_outgoing_items(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 35 } },
  {
   "title": "Number of units in the batch",
   "type": "heatmap",
   "description": "Number of units in the batch",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (job, cluster, namespace, instance, le) (increase({__name__=~\"otelcol_processor_batch_batch_send_size_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}} - {{le}}"
    }
   ]
  },
  {
   "title": "Batch cardinality",
   "type": "timeseries",
   "description": "Batch cardinality",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) ({__name__=~\"otelcol_processor_batch_metadata_cardinality(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Queue current size vs capacity",
   "type": "timeseries",
   "description": "Queue current size vs capacity",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) ({__name__=~\"otelcol_exporter_queue_size(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}} queue current size"
    },
    {
     "expr": "sum by(job, cluster, namespace, instance) ({__name__=~\"otelcol_exporter_queue_capacity(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"})\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}} queue capacity"
    }
   ]
  },
  {
   "title": "Batch size send trigger",
   "type": "timeseries",
   "description": "Batch size send trigger",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_processor_batch_timeout_trigger_send(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Batch timeout send trigger",
   "type": "timeseries",
   "description": "Batch timeout send trigger",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_processor_batch_timeout_trigger_send(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 52 } },
  {
   "title": "Exported metrics",
   "type": "timeseries",
   "description": "Exported metrics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_sent_metric_points(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Exported logs",
   "type": "timeseries",
   "description": "Exported logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_sent_log_records(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Exported spans",
   "type": "timeseries",
   "description": "Exported spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_sent_spans(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed metrics",
   "type": "timeseries",
   "description": "Failed metrics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_send_failed_metric_points(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed logs",
   "type": "timeseries",
   "description": "Failed logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_send_failed_log_records(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed spans",
   "type": "timeseries",
   "description": "Failed spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_send_failed_spans(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Enqueue failed metrics",
   "type": "timeseries",
   "description": "Enqueue failed metrics",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_enqueue_failed_metric_points(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Enqueue failed logs",
   "type": "timeseries",
   "description": "Enqueue failed logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_enqueue_failed_log_records(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Enqueue failed spans",
   "type": "timeseries",
   "description": "Enqueue failed spans",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, cluster, namespace, instance) (rate({__name__=~\"otelcol_exporter_enqueue_failed_spans(_total)?\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  { "title": "Network traffic", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 77 } },
  {
   "title": "Inbound gRPC request duration percentiles",
   "type": "timeseries",
   "description": "Inbound gRPC request duration percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_server_duration_milliseconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound HTTP request duration percentiles",
   "type": "timeseries",
   "description": "Inbound HTTP request duration percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound gRPC request size percentiles",
   "type": "timeseries",
   "description": "Inbound gRPC request size percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_server_request_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Inbound HTTP request size percentiles",
   "type": "timeseries",
   "description": "Inbound HTTP request size percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_server_request_body_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing gRPC request duration percentiles",
   "type": "timeseries",
   "description": "Outgoing gRPC request duration percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_client_duration_milliseconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing HTTP request duration percentiles",
   "type": "timeseries",
   "description": "Outgoing HTTP request duration percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_client_request_duration_seconds_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing gRPC request size percentiles",
   "type": "timeseries",
   "description": "Outgoing gRPC request size percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"rpc_client_request_size(_bytes_?)_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing HTTP request size percentiles",
   "type": "timeseries",
   "description": "Outgoing HTTP request size percentiles",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p50 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p90 - {{cluster}} - {{namespace}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, cluster, namespace, instance, le) (rate({__name__=~\"http_client_request_body_size_bytes_bucket\", job=~\"$job\", cluster=~\"$cluster\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])))\n",
     "legendFormat": "p99 - {{cluster}} - {{namespace}} - {{instance}}"
    }
   ]
  }
 ]
}