{
 "title": "AWX",
 "tags": [ "awx-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(awx_system_info, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(awx_system_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster List",
   "type": "table",
   "description": "List of available clusters with counts of cluster level objects. Selectable by the \"instance\" variable.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "awx_organizations_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Orgs"
    },
    {
     "expr": "awx_teams_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Teams"
    },
    {
     "expr": "awx_users_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "awx_inventories_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Inventories"
    },
    {
     "expr": "awx_projects_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Projects"
    },
    {
     "expr": "awx_schedules_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Schedules"
    }
   ]
  },
  {
   "title": "Tower Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_system_info{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tower Base URL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "License Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "License Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Licenses Free/Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "awx_license_instance_free{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "awx_license_instance_total{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Cluster Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "awx_instance_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (hostname) (awx_instance_cpu{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (hostname) (awx_instance_memory{job=~\"$job\", instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (hostname) (awx_instance_consumed_capacity{job=~\"$job\", instance=~\"$instance\"}) / sum by (hostname) (awx_instance_capacity{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_hosts_total{type=\"active\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "awx_hosts_total{type=\"total\", job=~\"$job\", instance=~\"$instance\"} - awx_hosts_total{type=\"active\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (awx_sessions_total{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Templates by Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_job_templates_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Job"
    },
    {
     "expr": "awx_workflow_job_templates_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Workflow Job"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Jobs by State",
   "type": "timeseries",
   "description": "Total number of jobs in the Running or Pending state, on all AWX instances in the cluster.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "awx_running_jobs_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "awx_running_jobs_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Job Rate by Launch Type",
   "type": "timeseries",
   "description": "Rate of new jobs being started, by Launch Type.",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (launch_type) (irate(awx_instance_launch_type_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{launch_type}}"
    }
   ]
  },
  {
   "title": "Jobs by Launch Type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (launch_type) (awx_instance_launch_type_total{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{launch_type}}"
    }
   ]
  },
  {
   "title": "Job Completion Status Rate",
   "type": "timeseries",
   "description": "Rate of job completion status, on all AWX instances in the cluster.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(awx_status_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Job Rate by Node and Completion Status",
   "type": "timeseries",
   "description": "Rate of new jobs being completed, by their Node and Completion Status.",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status, node) (irate(awx_instance_status_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}} - {{node}}"
    }
   ]
  },
  {
   "title": "Jobs by Completion Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (awx_instance_status_total{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}