groups:
    - name: consul
      rules:
        - alert: ConsulUp
          annotations:
            description: Consul '{{ $labels.job }}' is not up.
            summary: Consul is not up.
          expr: |
            consul_up != 1
          for: 1m
          labels:
            severity: critical
        - alert: ConsulMaster
          annotations:
            description: Consul '{{ $labels.job }}' has no master.
            summary: Consul has no master.
          expr: |
            consul_raft_leader != 1
          for: 1m
          labels:
            severity: critical
        - alert: ConsulPeers
          annotations:
            description: Consul '{{ $labels.job }}' does not have 3 peers.
            summary: Consul does not have peers.
          expr: |
            consul_raft_peers != 3
          for: 10m
          labels:
            severity: critical
