{
 "title": "OpenSearch search and index overview",
 "tags": [ "opensearch-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opensearch_index_search_fetch_count{opensearch_cluster!=\"\"}, job)"
   },
   {
    "name": "opensearch_cluster",
    "label": "Opensearch_cluster",
    "query": "label_values(opensearch_index_search_fetch_count{opensearch_cluster!=\"\",job=~\"$job\"}, opensearch_cluster)"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "label_values(opensearch_index_search_fetch_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}, index)"
   }
  ]
 },
 "panels": [
  { "title": "Request performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Rate of fetch, scroll, and query requests by selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster,index) (opensearch_index_search_query_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=~\"total\"})",
     "legendFormat": "{{index}} - query"
    },
    {
     "expr": "avg by (job,opensearch_cluster,index) (opensearch_index_search_fetch_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=~\"total\"})",
     "legendFormat": "{{index}} - fetch"
    },
    {
     "expr": "avg by (job,opensearch_cluster,index) (opensearch_index_search_scroll_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=~\"total\"})",
     "legendFormat": "{{index}} - scroll"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "Latency of fetch, scroll, and query requests by selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster,index) (increase(opensearch_index_search_query_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\"}[$__interval:]) / clamp_min(increase(opensearch_index_search_query_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]), 1))",
     "legendFormat": "{{index}} - query"
    },
    {
     "expr": "avg by (job,opensearch_cluster,index) (increase(opensearch_index_search_fetch_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]) / clamp_min(increase(opensearch_index_search_fetch_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]), 1))",
     "legendFormat": "{{index}} - fetch"
    },
    {
     "expr": "avg by (job,opensearch_cluster,index) (increase(opensearch_index_search_scroll_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]) / clamp_min(increase(opensearch_index_search_scroll_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]), 1))",
     "legendFormat": "{{index}} - scroll"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "Ratio of query cache and request cache hits and misses.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (100 * (opensearch_index_requestcache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}) / clamp_min(opensearch_index_requestcache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"} + opensearch_index_requestcache_miss_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}, 1))",
     "legendFormat": "{{index}} - request"
    },
    {
     "expr": "avg by(job,opensearch_cluster,index) (100 * (opensearch_index_querycache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}) / clamp_min(opensearch_index_querycache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"} + opensearch_index_querycache_miss_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}, 1))",
     "legendFormat": "{{index}} - query"
    }
   ]
  },
  {
   "title": "Evictions",
   "type": "timeseries",
   "description": "Total evictions count by cache type for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "evictions" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_querycache_evictions_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]))",
     "legendFormat": "{{index}} - query cache"
    },
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_requestcache_evictions_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]))",
     "legendFormat": "{{index}} - request cache"
    },
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_fielddata_evictions_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]))",
     "legendFormat": "{{index}} - field data"
    }
   ]
  },
  { "title": "Index performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Index rate",
   "type": "timeseries",
   "description": "Rate of indexed documents for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "documents/s" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_indexing_index_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Index latency",
   "type": "timeseries",
   "description": "Document indexing latency for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_indexing_index_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=~\"total\"}[$__interval:]) / clamp_min(increase(opensearch_index_indexing_index_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=~\"total\"}[$__interval:]),1))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Index failures",
   "type": "timeseries",
   "description": "Number of indexing failures for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "failures" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_indexing_index_failed_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Flush latency",
   "type": "timeseries",
   "description": "Index flush latency for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_flush_total_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]) / clamp_min(increase(opensearch_index_flush_total_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]),1))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Merge time",
   "type": "timeseries",
   "description": "Index merge time for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_merges_total_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:])) > 0",
     "legendFormat": "{{index}} - total"
    },
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_merges_total_stopped_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:])) > 0",
     "legendFormat": "{{index}} - stopped"
    },
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_merges_total_throttled_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:])) > 0",
     "legendFormat": "{{index}} - throttled"
    }
   ]
  },
  {
   "title": "Refresh latency",
   "type": "timeseries",
   "description": "Index refresh latency for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_refresh_total_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]) / clamp_min(increase(opensearch_index_refresh_total_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:]),1))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Translog operations",
   "type": "timeseries",
   "description": "Current number of translog operations for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_translog_operations_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Docs deleted",
   "type": "timeseries",
   "description": "Rate of documents deleted for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "documents/s" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster,index) (opensearch_index_indexing_delete_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Index capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Documents indexed",
   "type": "timeseries",
   "description": "Number of indexed documents for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "documents" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster,index) (opensearch_index_indexing_index_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Segment count",
   "type": "timeseries",
   "description": "Current number of segments for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "segments" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_segments_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Merge count",
   "type": "timeseries",
   "description": "Number of merge operations for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "merges" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (increase(opensearch_index_merges_total_docs_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}[$__interval:])) > 0",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "description": "Size of query cache and request cache.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_querycache_memory_size_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}} - query"
    },
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_requestcache_memory_size_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}} - request"
    }
   ]
  },
  {
   "title": "Store size",
   "type": "timeseries",
   "description": "Size of the store in bytes for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_store_size_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Segment size",
   "type": "timeseries",
   "description": "Memory used by segments for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_segments_memory_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Merge size",
   "type": "timeseries",
   "description": "Size of merge operations in bytes for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(job,opensearch_cluster,index) (opensearch_index_merges_current_size_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", context=\"total\"}) > 0",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Shard count",
   "type": "timeseries",
   "description": "The number of index shards for the selected index.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "targets": [
    {
     "expr": "sum by (index) (avg by(job,opensearch_cluster,index) (opensearch_index_shards_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",index=~\"$index\", type=~\"active|active_primary\"}))",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}