local g = import './g.libsonnet';
local var = g.dashboard.variable;
local commonlib = import 'common-lib/common/main.libsonnet';

// Dashboard variables are generated by commonlib.variables. Two instances are needed:
//
//   instanceScoped - job, pgbouncer_cluster, instance, database. Drives the overview
//                    dashboard and supplies queriesSelector/queriesSelectorGroupOnly.
//   groupScoped    - job, pgbouncer_cluster only (instanceLabels=[]), for the
//                    cluster overview, which aggregates across instances.
//
// Only the top_database_count variable is pgbouncer-specific; everything else comes
// from the library. The overview's single-select instance is patched in mixin.libsonnet.
{
  new(this, varMetric):
    local config = this.config;

    local instanceScoped = commonlib.variables.new(
      filteringSelector=config.filteringSelector,
      groupLabels=config.groupLabels,
      instanceLabels=config.instanceLabels,
      varMetric=varMetric,
      enableLokiLogs=config.enableLokiLogs,
      customAllValue=config.customAllValue,
    );

    // enableLokiLogs stays false so the cluster overview does not pick up the Loki
    // datasource, but the Prometheus datasource variable must keep the name the
    // signals layer renders into panel targets.
    local groupScoped = commonlib.variables.new(
      filteringSelector=config.filteringSelector,
      groupLabels=config.groupLabels,
      instanceLabels=[],
      varMetric=varMetric,
      customAllValue=config.customAllValue,
      prometheusDatasourceName='prometheus_datasource',
      prometheusDatasourceLabel='Prometheus data source',
    );

    local topDatabaseCount =
      var.custom.new(
        'top_database_count',
        values=[2, 4, 6, 8, 10],
      )
      + var.custom.generalOptions.withDescription(
        'This variable allows for modification of top database value.'
      )
      + var.custom.generalOptions.withLabel('Top database count');

    instanceScoped {
      // Cluster overview dashboard: job, pgbouncer_cluster, top database count.
      clusterVariables: groupScoped.multiInstance + [topDatabaseCount],
      // Alert list filter on the cluster overview uses advanced (multi-value) syntax.
      queriesGroupSelectorAdvanced: groupScoped.queriesSelectorAdvancedSyntax,
    },
}
