{
 "title": "IBM MQ - cluster overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{}, job)"
   },
   {
    "name": "qmgr",
    "label": "Qmgr",
    "query": "label_values(ibmmq_qmgr_commit_count{job=~\"$job\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Cluster overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Clusters",
     "type": "stat",
     "description": "The unique number of clusters being reported.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(ibmmq_qmgr_commit_count{}) by (mq_cluster))",
       "legendFormat": "{{job}} - {{mq_cluster}}"
      }
     ]
    },
    {
     "title": "Queue managers",
     "type": "stat",
     "description": "The unique number of queue managers in the cluster being reported.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(ibmmq_qmgr_commit_count{}) by (qmgr, mq_cluster))"
      }
     ]
    },
    {
     "title": "Topics",
     "type": "stat",
     "description": "The unique number of topics in the cluster.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(ibmmq_topic_messages_received{}) by (topic, qmgr))"
      }
     ]
    },
    {
     "title": "Queues",
     "type": "stat",
     "description": "The unique number of queues in the cluster.",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(ibmmq_queue_depth{}) by (queue, mq_cluster, qmgr))"
      }
     ]
    },
    {
     "title": "Queue operations",
     "type": "piechart",
     "description": "The number of queue operations of the cluster. ",
     "gridPos": { "h": 15, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "operations" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqinq_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQINQ"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqget_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQGET"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqopen_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQOPEN"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqput_mqput1_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQPUT/MQPUT1"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 16 },
   "panels": [
    {
     "title": "Cluster status",
     "type": "table",
     "description": "The status of the cluster.",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (job) (\n  ibmmq_cluster_suspend{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{mq_cluster}}"
      }
     ]
    },
    {
     "title": "Queue manager status",
     "type": "table",
     "description": "The status of the queue manager (-1=N/A, 0=Stopped, 1=Starting, 2=Running, 3=Quiescing, 4=Stopping, 5=Standby).",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_status{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 },
   "panels": [
    {
     "title": "Transmission queue time",
     "type": "timeseries",
     "description": "The time taken for messages to be transmitted over sender channels.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_channel_xmitq_time_short{type=\"SENDER\",job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{channel}} - short"
      },
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_channel_xmitq_time_long{type=~\"SENDER\",job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{channel}} - long"
      }
     ]
    }
   ]
  }
 ]
}