{
 "title": "IBM MQ topics overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\"}, mq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\"}, instance)"
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(ibmmq_topic_subscriber_count{qmgr=~\"$qmgr\",topic!~\"SYSTEM.*|\\\\$SYS.*|\"}, topic)"
   },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(ibmmq_subscription_messsages_received{qmgr=~\"$qmgr\",subscription!~\"SYSTEM.*|\"}, subscription)"
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Topic messages received",
   "type": "timeseries",
   "description": "Received messages per topic.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_topic_messages_received{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Time since last message",
   "type": "bargauge",
   "description": "The time since the topic last received a message.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_topic_time_since_msg_received{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Topic subscribers",
   "type": "timeseries",
   "description": "The number of subscribers per topic.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_topic_subscriber_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Topic publishers",
   "type": "timeseries",
   "description": "The number of publishers per topic.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_topic_publisher_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{topic}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 } },
  {
   "title": "Subscription messages received",
   "type": "timeseries",
   "description": "The number of messages a subscription receives.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_subscription_messsages_received{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{subscription}}"
    }
   ]
  },
  {
   "title": "Subscription status",
   "type": "table",
   "description": "A table for at a glance information about a subscription.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_subscription_time_since_message_published{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}