{
 "title": "IBM MQ - queue overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{}, job)"
   },
   {
    "name": "qmgr",
    "label": "Qmgr",
    "query": "label_values(ibmmq_qmgr_commit_count{job=~\"$job\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(ibmmq_queue_depth{,queue!~\"SYSTEM.*|AMQ.*\"}, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Average queue time",
     "type": "timeseries",
     "description": "The average amount of time a message spends in the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_queue_average_queue_time_seconds{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Expired messages",
     "type": "timeseries",
     "description": "The rate of expired messages in the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_expired_messages{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Depth",
     "type": "timeseries",
     "description": "The number of active messages in the queue.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_queue_depth{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Operation throughput",
     "type": "timeseries",
     "description": "The throughput of operations on the queue.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqget_bytes{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQGET"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqput_bytes{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQPUT"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "timeseries",
     "description": "The rate of operations on the queue.",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "operations" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqset_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQSET"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqinq_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQINQ"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqget_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQGET"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqopen_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQOPEN"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqclose_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQCLOSE"
      },
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_queue_mqput_mqput1_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{queue}} - MQPUT/MQPUT1"
      }
     ]
    }
   ]
  }
 ]
}