{
 "title": "IBM MQ - queue manager overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{}, job)"
   },
   {
    "name": "qmgr",
    "label": "Qmgr",
    "query": "label_values(ibmmq_qmgr_commit_count{job=~\"$job\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Active listeners",
     "type": "stat",
     "description": "The number of active listeners for the queue manager.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_active_listeners{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "stat",
     "description": "The number of active connections for the queue manager.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_connection_count{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Queues",
     "type": "stat",
     "description": "The unique number of queues being managed by the queue manager.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(ibmmq_queue_depth{}) by (queue, mq_cluster, qmgr))"
      }
     ]
    },
    {
     "title": "Estimated memory utilization",
     "type": "timeseries",
     "description": "The estimated memory usage of the queue managers.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(ibmmq_qmgr_ram_total_estimate_for_queue_manager_bytes{job=~\"$job\",qmgr=~\"$qmgr\"}/ibmmq_qmgr_ram_total_bytes{job=~\"$job\",qmgr=~\"$qmgr\"})",
       "legendFormat": "{{qmgr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 8 },
   "panels": [
    {
     "title": "Queue manager status",
     "type": "table",
     "description": "The status of the queue manager (-1=N/A, 0=Stopped, 1=Starting, 2=Running, 3=Quiescing, 4=Stopping, 5=Standby).",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_status{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "The CPU usage of the queue managers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_user_cpu_time_percentage{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}} - user"
      },
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_system_cpu_time_percentage{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}} - system"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "timeseries",
     "description": "The disk allocated to the queue manager that is being used.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_queue_manager_file_system_in_use_bytes{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 16 },
   "panels": [
    {
     "title": "Free disk space",
     "type": "timeseries",
     "description": "The percentage of free disk space available for the queue manager.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_queue_manager_file_system_free_space_percentage{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Commit rate",
     "type": "timeseries",
     "description": "The rate of commits by the queue manager.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_qmgr_commit_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Published bytes",
     "type": "timeseries",
     "description": "The rate of data being pushed from the queue manager to subscribers.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_qmgr_published_to_subscribers_bytes{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Published messages",
     "type": "timeseries",
     "description": "The rate of messages being published by the queue manager.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_qmgr_published_to_subscribers_message_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Expired messages",
     "type": "timeseries",
     "description": "The rate of expired messages for the queue manager.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_qmgr_expired_message_count{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 },
   "panels": [
    {
     "title": "Log write latency",
     "type": "timeseries",
     "description": "The recent latency of log writes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_log_write_latency_seconds{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    },
    {
     "title": "Log usage",
     "type": "timeseries",
     "description": "The amount of data on the filesystem occupied by queue manager logs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_qmgr_log_in_use_bytes{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{qmgr}}"
      }
     ]
    }
   ]
  }
 ]
}