{
 "title": "IBM MQ - topics overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{}, job)"
   },
   {
    "name": "qmgr",
    "label": "Qmgr",
    "query": "label_values(ibmmq_qmgr_commit_count{job=~\"$job\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(ibmmq_topic_subscriber_count{,topic!~\"SYSTEM.*|\\\\$SYS.*|\"}, topic)"
   },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": "label_values(ibmmq_subscription_messsages_received{,subscription!~\"SYSTEM.*|\"}, subscription)"
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Topic messages received",
     "type": "timeseries",
     "description": "Received messages per topic.",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_topic_messages_received{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Time since last message",
     "type": "bargauge",
     "description": "The time since the topic last received a message.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_topic_time_since_msg_received{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic subscribers",
     "type": "timeseries",
     "description": "The number of subscribers per topic.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_topic_subscriber_count{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic publishers",
     "type": "timeseries",
     "description": "The number of publishers per topic.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_topic_publisher_count{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 },
   "panels": [
    {
     "title": "Subscription messages received",
     "type": "timeseries",
     "description": "The rate of messages a subscription receives.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  rate(ibmmq_subscription_messsages_received{job=~\"$job\",qmgr=~\"$qmgr\"}[$__rate_interval])\n)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Subscription status",
     "type": "table",
     "description": "The time since a message was published to the subscription.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (job,qmgr) (\n  ibmmq_subscription_time_since_message_published{job=~\"$job\",qmgr=~\"$qmgr\"}\n)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  }
 ]
}