function(this)
  {
    datasource: 'prometheus_datasource',
    filteringSelector: this.filteringSelector,
    groupLabels: this.groupLabels,
    instanceLabels: this.instanceLabels,
    aggLevel: 'none',
    aggFunction: 'avg',
    discoveryMetric: {
      prometheus: 'solr_metrics_jetty_requests_total',
    },
    signals: {
      requests: {
        name: 'Requests  / $__interval',
        nameShort: 'Requests',
        type: 'counter',
        description: 'Total number of requests received by Jetty.',
        unit: 'none',
        aggLevel: 'group',
        aggFunction: 'avg',
        sources: {
          prometheus: {
            expr: 'solr_metrics_jetty_requests_total{%(queriesSelector)s}',
            rangeFunction: 'increase',
            aggKeepLabels: ['solr_cluster', 'base_url', 'method'],
            exprWrappers: [['', ' > 0']],
            legendCustomTemplate: '{{base_url}} - {{method}}',
          },
        },
      },
      responses: {
        name: 'Responses  / $__interval',
        nameShort: 'Responses',
        type: 'counter',
        description: 'Total number of responses generated by Jetty.',
        unit: 'none',
        aggLevel: 'group',
        aggFunction: 'avg',
        sources: {
          prometheus: {
            expr: 'solr_metrics_jetty_response_total{%(queriesSelector)s}',
            rangeFunction: 'increase',
            aggKeepLabels: ['solr_cluster', 'base_url', 'status'],
            exprWrappers: [['', ' > 0']],
            legendCustomTemplate: '{{base_url}} - {{status}}',
          },
        },
      },
      dispatches: {
        name: 'Dispatches  / $__interval',
        nameShort: 'Dispatches',
        type: 'counter',
        description: 'Total count of dispatches handled by Jetty.',
        unit: 'none',
        aggLevel: 'group',
        aggFunction: 'avg',
        sources: {
          prometheus: {
            expr: 'solr_metrics_jetty_dispatches_total{%(queriesSelector)s}',
            rangeFunction: 'increase',
            aggKeepLabels: ['solr_cluster', 'base_url'],
            exprWrappers: [['', ' > 0']],
            legendCustomTemplate: '{{base_url}}',
          },
        },
      },
    },
  }
