{
 "title": "WSO2 API Metrics",
 "description": "This Dashboard provides an overview of API services deployed in Enterprise Integrator Cluster.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service Name",
    "query": {
     "query": "label_values(wso2_integration_service_up{service_type=\"api\"}, service_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(wso2_integration_service_up{service_type=\"api\", service_name=~\"$service\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(wso2_integration_service_up{service_name=~\"$service\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "All Request Count",
   "type": "stat",
   "description": "Displays all time request count served by this API service. This will also include the error requests.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))- (min_over_time(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Successful Request Count",
   "type": "stat",
   "description": "Displays approximate request count received by this API service within the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum((max_over_time(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))- (min_over_time(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))))-(sum((max_over_time(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))- (min_over_time(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "Displays all time error count occurred within this API service",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))-(min_over_time(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "stat",
   "description": "Displays number of error requests occurred during the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))-(min_over_time(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range])))/sum((max_over_time(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range]))-(min_over_time(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Deployed Node Count",
   "type": "stat",
   "description": "Displays number of nodes this API service is deployed.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(wso2_integration_service_up{service_name=~\"$service\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Displays the request rate for this API service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wso2_integration_api_request_count_total{service_name=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "Displays error rate of this API service.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wso2_integration_api_request_count_error_total{service_name=~\"$service\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "description": "Displays the response time of all requests served by this API service in a heat map. Each tile will represent number of requests which fell in to the pre-defined time bucket during the bucket time span. If you seen any anomalies  please use the below link to view tracing information related to $service",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le)(increase(wso2_integration_api_latency_seconds{service_name=~\"$service\", instance=~\"$instance\", le=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}