{
 "title": "SAP HANA system overview",
 "description": "SAP HANA system overview",
 "tags": [ "sap-hana-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hanadb_cpu_busy_percent{job=\"integrations/sap-hana\"}, job)"
   },
   {
    "name": "sid",
    "label": "SAP HANA system",
    "query": "label_values(hanadb_cpu_busy_percent{job=\"integrations/sap-hana\",job=~\"$job\"}, sid)"
   },
   {
    "name": "host",
    "label": "SAP HANA instance",
    "query": "label_values(hanadb_cpu_busy_percent{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\"}, host)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Replica status",
   "type": "stat",
   "description": "State of the replicas in the SAP HANA system",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hanadb_sr_replication{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}",
     "legendFormat": "{{secondary_site_name}}"
    }
   ]
  },
  {
   "title": "Average replication ship delay",
   "type": "timeseries",
   "description": "Average system replication log shipping delay in the SAP HANA system",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job,sid,host, secondary_site_name) (hanadb_sr_ship_delay{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{secondary_site_name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage percentage of the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job,sid,host, core) (hanadb_cpu_busy_percent{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}} - core {{core}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "Disk utilization percentage of the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,sid,host) (hanadb_disk_total_used_size_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}) / sum by (job,sid,host) (hanadb_disk_total_size_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Physical memory usage",
   "type": "timeseries",
   "description": "Physical memory utilization percentage of the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,sid,host) (hanadb_host_memory_resident_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}) / sum by (job,sid,host) (hanadb_host_memory_physical_total_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}} - resident"
    },
    {
     "expr": "100 * sum by (job,sid,host) (hanadb_host_memory_swap_used_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}) / clamp_min(sum by (job,sid,host) (hanadb_host_memory_swap_used_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"} + hanadb_host_memory_swap_free_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}), 1)",
     "legendFormat": "{{host}} - swap"
    }
   ]
  },
  {
   "title": "SAP HANA memory usage",
   "type": "timeseries",
   "description": "Total amount of used memory by processes in the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,sid,host) (hanadb_host_memory_used_total_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}) / sum by (job,sid,host) (hanadb_host_memory_alloc_limit_mb{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 20 } },
  {
   "title": "Network I/O throughput",
   "type": "timeseries",
   "description": "Network I/O throughput in the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by (job,sid,host) (hanadb_network_receive_rate_kb_per_seconds{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}} - receive"
    },
    {
     "expr": "sum by (job,sid,host, interface) (hanadb_network_transmission_rate_kb_per_seconds{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}} - transmit"
    }
   ]
  },
  {
   "title": "Disk I/O throughput",
   "type": "timeseries",
   "description": "Disk throughput for the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by (job,sid,host) (hanadb_disk_io_throughput_kb_second{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Average query execution time",
   "type": "timeseries",
   "description": "Average elapsed time per execution across the SAP HANA system",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (job,sid,host, service, sql_type) (hanadb_sql_service_elap_per_exec_avg_ms{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}} - service: {{service}} - type: {{sql_type}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "Number of connections in active states across the SAP HANA system",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,sid,host) (hanadb_connections_total_count{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\", connection_status=~\"RUNNING|QUEUING\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "stat",
   "description": "Number of connections in the idle state across the SAP HANA system",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,sid,host) (hanadb_connections_total_count{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\", connection_status=~\"IDLE\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 34 } },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Count of the SAP HANA current alerts in the SAP HANA system",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,sid,host) (hanadb_alerts_current_rating{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Recent alerts",
   "type": "table",
   "description": "Table of the recent SAP HANA current alerts in the SAP HANA system",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "hanadb_alerts_current_rating{job=\"integrations/sap-hana\",job=~\"$job\",sid=~\"$sid\",host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}