{
 "title": "Beanstalkd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "TubeName", "label": "Name of Tube", "query": "tube_current_jobs_ready" },
   {
    "name": "Instance",
    "label": "which beanstalkd instance to display",
    "query": "cmd_put"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics for Exported Instance $Instance ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Instance"
  },
  {
   "title": "$Instance Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cmd_put{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Jobs Put for $Instance"
    },
    {
     "expr": "rate(cmd_reserve{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Jobs Reserved for $Instance"
    },
    {
     "expr": "rate(cmd_reserve_with_timeout{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Jobs Reserved with timeout for $Instance"
    },
    {
     "expr": "rate(cmd_delete{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Jobs Deleted for $Instance"
    },
    {
     "expr": "rate(cmd_bury{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Jobs burried for $Instance"
    },
    {
     "expr": "rate(cmd_kick{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Jobs kicked for $Instance"
    }
   ]
  },
  {
   "title": "$Instance Jobs created per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_jobs{exported_instance=\"$Instance\"}[5m])",
     "legendFormat": "Total jobs for $Instance"
    }
   ]
  },
  {
   "title": "$Instance Workers and Waiters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "current_workers{exported_instance=\"$Instance\"}",
     "legendFormat": "Active Instance Workers"
    },
    {
     "expr": "current_waiting{exported_instance=\"$Instance\"}",
     "legendFormat": "Active Instance Waiters"
    }
   ]
  },
  {
   "title": "$Instance current active tubes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "current_tubes", "legendFormat": "Active Tubes" }
   ]
  },
  {
   "title": "Beanstalk Metrics for tube \"$TubeName\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "repeat": "TubeName"
  },
  {
   "title": "Jobs in State for tube \"$TubeName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tube_current_jobs_ready{tube=\"$TubeName\"}",
     "legendFormat": "Jobs Ready for $TubeName"
    },
    {
     "expr": "tube_current_jobs_reserved{tube=\"$TubeName\"}",
     "legendFormat": "Jobs Reserved for $TubeName"
    },
    {
     "expr": "tube_current_jobs_buried{tube=\"$TubeName\"}",
     "legendFormat": "Jobs Buried for $TubeName"
    },
    {
     "expr": "tube_current_jobs_delayed{tube=\"$TubeName\"}",
     "legendFormat": "Jobs Delayed for $TubeName"
    },
    {
     "expr": "tube_current_jobs_urgent{tube=\"$TubeName\"}",
     "legendFormat": "Jobs Urgent for $TubeName"
    }
   ]
  },
  {
   "title": "Users and Watchers for tube \"$TubeName\" ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tube_current_using{tube=\"$TubeName\"}",
     "legendFormat": "\"$TubeName\" Users"
    },
    {
     "expr": "tube_current_waiting{tube=\"$TubeName\"}",
     "legendFormat": "\"$TubeName\" Waiting"
    },
    {
     "expr": "tube_current_watching{tube=\"$TubeName\"}",
     "legendFormat": "\"$TubeName\" Watching"
    }
   ]
  },
  {
   "title": "Jobs created per second for tube \"$TubeName\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tube_total_jobs{tube=\"$TubeName\"}[5m])",
     "legendFormat": "Jobs per Second"
    }
   ]
  }
 ]
}