{
 "title": "JVM overview",
 "tags": [
  "java",
  "jvm"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"jvm_memory_used_bytes|jvm_memory_bytes_max|process_runtime_jvm_memory_usage|process_runtime_jvm_memory_usage_bytes|java_lang_memory_heapmemoryusage_used\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"jvm_memory_used_bytes|jvm_memory_bytes_max|process_runtime_jvm_memory_usage|process_runtime_jvm_memory_usage_bytes|java_lang_memory_heapmemoryusage_used\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Memory used(heap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  java_lang_memory_heapmemoryusage_used{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_used{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage_bytes{type=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage{type=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  java_lang_memory_heapmemoryusage_max{job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_max{area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit_bytes{type=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit{type=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    }
   ]
  },
  {
   "title": "Memory used(nonheap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  java_lang_memory_nonheapmemoryusage_used{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_used{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage_bytes{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  java_lang_memory_nonheapmemoryusage_max{job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_max{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit_bytes{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job) (\n  java_lang_threading_threadcount{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_current{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_live_threads{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (daemon) (process_runtime_jvm_threads_count{job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: Threads"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "stat",
   "description": "The number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job) (\n  java_lang_classloading_loadedclasscount{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_classes_loaded_classes{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_classes_loaded{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_classes_loaded_total{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_classes_loaded{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Classes loaded"
    }
   ]
  },
  { "title": "Process overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "\n  java_lang_runtime_uptime{job=~\"$job\",instance=~\"$instance\"}\n/1000\nor\nprocess_uptime_seconds{job=~\"$job\",instance=~\"$instance\"}\nor\nprocess_uptime{job=~\"$job\",instance=~\"$instance\"}\nor\nruntime_uptime_milliseconds_total{job=~\"$job\",instance=~\"$instance\"}\nor\ntime()-process_start_time_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Process start time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  java_lang_runtime_starttime{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_start_time_seconds{job=~\"$job\",instance=~\"$instance\"} * 1000\n)\nor\navg by (job,instance) (\n  process_start_time{job=~\"$job\",instance=~\"$instance\"} * 1000\n)",
     "legendFormat": "{{instance}}: Process start time"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "System's load average.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  java_lang_operatingsystem_systemloadaverage{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_jvm_system_cpu_load_1m{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  system_load_average_1m{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Load average"
    },
    {
     "expr": "avg by (job,instance) (\n  system_cpu_count{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: CPU count"
    }
   ]
  },
  {
   "title": "CPU usage (process)",
   "type": "timeseries",
   "description": "Process CPU usage.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n  avg by (job,instance) (\n  rate(java_lang_operatingsystem_processcputime{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n/1000000000 * 100\nor\navg by (job,instance) (\n  process_cpu_usage{job=~\"$job\",instance=~\"$instance\"} * 100\n)\nor\navg by (job,instance) (\n  process_runtime_jvm_cpu_utilization_ratio{job=~\"$job\",instance=~\"$instance\"} * 100\n)\nor\navg by (job,instance) (\n  process_runtime_jvm_cpu_utilization{job=~\"$job\",instance=~\"$instance\"} * 100\n)\nor\navg by (job,instance) (\n  rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (process)"
    },
    {
     "expr": "\n  avg by (job,instance) (\n  java_lang_operatingsystem_cpuload{job=~\"$job\",instance=~\"$instance\"}\n)\n* 100\nor\navg by (job,instance) (\n  process_runtime_jvm_system_cpu_utilization_ratio{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_jvm_system_cpu_utilization{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  system_cpu_usage{job=~\"$job\",instance=~\"$instance\"} * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (system)"
    }
   ]
  },
  {
   "title": "Process memory used (rss)",
   "type": "timeseries",
   "description": "Process resident memory size in bytes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  java_lang_memory_heapmemoryusage_used{job=~\"$job\",instance=~\"$instance\"} + java_lang_memory_nonheapmemoryusage_used{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process memory used (rss)"
    }
   ]
  },
  {
   "title": "Process files open",
   "type": "timeseries",
   "description": "Process files opened.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_files_open_files{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_files_open{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_open_fds{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files open"
    },
    {
     "expr": "avg by (job,instance) (\n  process_files_max_files{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_files_max{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_max_fds{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files max"
    }
   ]
  },
  { "title": "JVM memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "JVM memory used(heap)",
   "type": "timeseries",
   "description": "The used space is the amount of memory that is currently occupied by Java objects.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  java_lang_memory_heapmemoryusage_used{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_used{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage_bytes{type=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage{type=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    },
    {
     "expr": "avg by (job) (\n  java_lang_memory_heapmemoryusage_max{job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_max{area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit_bytes{type=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit{type=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(heap)"
    },
    {
     "expr": "avg by (job) (\n  java_lang_memory_heapmemoryusage_committed{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_committed{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_committed_bytes{area=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_committed_bytes{type=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_committed{type=\"heap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(heap)"
    }
   ]
  },
  {
   "title": "JVM memory used(nonheap)",
   "type": "timeseries",
   "description": "The amount of memory that is currently in non-heap.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  java_lang_memory_nonheapmemoryusage_used{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_used{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage_bytes{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_usage{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  java_lang_memory_nonheapmemoryusage_max{job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_max{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit_bytes{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_limit{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  java_lang_memory_nonheapmemoryusage_committed{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_bytes_committed{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (id) (jvm_memory_committed_bytes{area=\"nonheap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_committed_bytes{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"})\n)\nor\navg by (job) (\n  sum without (pool) (process_runtime_jvm_memory_committed{type=\"non_heap\", job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(nonheap)"
    }
   ]
  },
  { "title": "JVM garbage collection", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Eden Space (used)",
   "type": "timeseries",
   "description": "Memory used for G1 Eden Space Collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_bytes_used{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_used_bytes{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_used_bytes{id=~\"(G1 |PS )?Eden Space\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_usage_bytes{type=\"heap\", pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_usage{type=\"heap\", pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_max_bytes{id=~\"(G1 )?Eden Space\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\n\n  avg by (job) (\n  process_runtime_jvm_memory_limit_bytes{pool=~\"(G1 |PS )?Eden Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\n\n  avg by (job) (\n  process_runtime_jvm_memory_limit{pool=~\"(G1 |PS )?Eden Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\navg by (job) (\n  jvm_memory_pool_bytes_max{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_max_bytes{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed_bytes{id=~\"(G1 |PS )?Eden Space\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_bytes_committed{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_committed_bytes{pool=~\"(G1 |PS )?Eden Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_committed_bytes{pool=~\"(G1 |PS )?Eden Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_committed{pool=~\"(G1 |PS )?Eden Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (committed)"
    }
   ]
  },
  {
   "title": "Survival space (used)",
   "type": "timeseries",
   "description": "Memory used for Survival collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_bytes_used{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_used_bytes{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_used_bytes{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_usage_bytes{type=\"heap\", pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_usage{type=\"heap\", pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (used)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_max_bytes{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  jvm_memory_pool_bytes_max{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  jvm_memory_pool_max_bytes{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_limit_bytes{pool=~\"(G1 |PS )?Survivor Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_limit{pool=~\"(G1 |PS )?Survivor Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"} != -1\n)",
     "legendFormat": "{{job}}: Survival space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed_bytes{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_bytes_committed{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_committed_bytes{pool=~\"(G1 |PS )?Survivor Space\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_committed_bytes{pool=~\"(G1 |PS )?Survivor Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_committed{pool=~\"(G1 |PS )?Survivor Space\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (committed)"
    }
   ]
  },
  {
   "title": "Tenured space (used)",
   "type": "timeseries",
   "description": "Memory used for Tenured(Old Gen) collection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_used_bytes{pool=\"PS Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_used_bytes{id=\"Tenured Gen\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_usage_bytes{type=\"heap\", pool=~\"G1 Old Gen|Tenured Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_usage{type=\"heap\", pool=~\"G1 Old Gen|Tenured Gen\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_max_bytes{id=\"Tenured Gen\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\n\n  avg by (job) (\n  jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\n\n  avg by (job) (\n  jvm_memory_pool_used_bytes{pool=\"PS Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\n\n  avg by (job) (\n  process_runtime_jvm_memory_limit_bytes{pool=~\"G1 Old Gen|Tenured Gen\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1\nor\n\n  avg by (job) (\n  process_runtime_jvm_memory_limit{pool=~\"G1 Old Gen|Tenured Gen\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\n != -1",
     "legendFormat": "{{job}}: Tenured space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed_bytes{id=\"Tenured Gen\", area=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_bytes_committed{pool=\"G1 Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_memory_pool_committed_bytes{pool=\"PS Old Gen\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_committed_bytes{pool=~\"G1 Old Gen|Tenured Gen\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_memory_committed{pool=~\"G1 Old Gen|Tenured Gen\", type=\"heap\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (committed)"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg by (job,gc) (\n  rate(jvm_gc_collection_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\nor\nlabel_replace(\n  avg by (job,action,cause) (\n  rate(jvm_gc_pause_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n, \"action\", \"$1\", \"action\", \"end of (.+)\")\nor\nlabel_replace(\n  avg by (job,gc,action) (\n  rate(process_runtime_jvm_gc_duration_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n, \"action\", \"$1\", \"action\", \"end of (.+)\")\nor\nlabel_replace(\n  avg by (job,gc,action) (\n  rate(process_runtime_jvm_gc_duration_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "avg by (job, gc) (\n  rate(jvm_gc_collection_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n  /\n  rate(jvm_gc_collection_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n\nor\nlabel_replace(\n  avg by (job, action, cause) (\n  rate(jvm_gc_pause_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n  /\n  rate(jvm_gc_pause_seconds_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{ job }}: {{ action }} ({{ cause }}) (avg)"
    },
    {
     "expr": "label_replace(\n  avg by (action,cause, job) (rate(jvm_gc_pause_seconds_max{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{ job }}: {{ action }} ({{ cause }}) (max)"
    },
    {
     "expr": "label_replace(\n  histogram_quantile(0.95, sum(rate(process_runtime_jvm_gc_duration_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le,job,action,gc))\n\n, \"action\", \"$1\", \"action\", \"end of (.+)\")\nor\nlabel_replace(\n  histogram_quantile(0.95, sum(rate(process_runtime_jvm_gc_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (le,job,action,gc))\n\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{ job }}: {{ action }} ({{ gc }}) (p95)"
    }
   ]
  },
  {
   "title": "Allocated/promoted",
   "type": "timeseries",
   "description": "'Allocated' is the size increase of the young generation memory pool after one GC and before the next. It reflects minor GC.\n'Promoted' is the size increase of the old generation memory pool after GC. It reflects full GC.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  rate(jvm_gc_memory_allocated_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\nor\navg by (job) (\n  rate(jvm_memory_pool_allocated_bytes_total{pool=~\"(G1 |PS )?Eden Space\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Allocated (bytes)"
    },
    {
     "expr": "topk(10,\n  avg by (job, arena, thread_name) (rate(process_runtime_jvm_memory_allocation_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n)\n",
     "legendFormat": "{{ job }}: Allocated ({{ thread_name }}, {{ arena }})"
    },
    {
     "expr": "avg by (job) (\n  rate(jvm_gc_memory_promoted_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Promoted"
    }
   ]
  },
  { "title": "JVM threads", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg by (job) (\n  java_lang_threading_threadcount{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_current{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_live_threads{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  sum without (daemon) (process_runtime_jvm_threads_count{job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: Threads"
    },
    {
     "expr": "avg by (job) (\n  java_lang_threading_daemonthreadcount{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_daemon_threads{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_daemon{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_threads_count{daemon=\"true\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (daemon)"
    },
    {
     "expr": "avg by (job) (\n  java_lang_threading_peakthreadcount{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_peak_threads{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_threads_peak{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (peak)"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_deadlocked{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (deadlocked)"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "timeseries",
   "description": "Threads by current state.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by (state, job) (jvm_threads_states_threads{job=~\"$job\",instance=~\"$instance\"})\nor\nsum by (state, job) (jvm_threads_state{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "JVM buffers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 53 } },
  {
   "title": "Direct buffer used bytes",
   "type": "timeseries",
   "description": "Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_memory_used_bytes{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_buffer_pool_used_bytes{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_usage_bytes{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_usage{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer used bytes"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_pool_capacity_bytes{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_buffer_total_capacity_bytes{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_limit_bytes{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_limit{pool=\"direct\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer capacity"
    }
   ]
  },
  {
   "title": "Mapped buffer used",
   "type": "timeseries",
   "description": "The mapped buffer pool is used for its FileChannel instances.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_memory_used_bytes{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_buffer_pool_used_bytes{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_usage_bytes{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_usage{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer used"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_pool_capacity_bytes{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  jvm_buffer_total_capacity_bytes{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_limit_bytes{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job) (\n  process_runtime_jvm_buffer_limit{pool=\"mapped\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer capacity"
    }
   ]
  }
 ]
}