{
 "title": "Microsoft IIS overview",
 "description": "Dashboard providing an overview of Microsoft IIS performance.",
 "tags": [ "microsoft-iis-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_iis_requests_total{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_iis_requests_total{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "site",
    "label": "Site",
    "query": "label_values(windows_iis_requests_total{job=~\"$job\", instance=~\"$instance\"}, site)"
   }
  ]
 },
 "panels": [
  { "title": "Requests and errors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The request rate split by HTTP Method for an IIS site",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_requests_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{site}} - {{method}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "description": "Requests that have resulted in errors for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errors/sec" } },
   "targets": [
    {
     "expr": "rate(windows_iis_locked_errors_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{site}} - locked"
    },
    {
     "expr": "rate(windows_iis_not_found_errors_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{site}} - not found"
    }
   ]
  },
  { "title": "Async I/O", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Blocked async I/O requests",
   "type": "timeseries",
   "description": "Number of async I/O requests that are currently queued for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(windows_iis_blocked_async_io_requests_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Rejected async I/O requests",
   "type": "timeseries",
   "description": "Number of async I/O requests that have been rejected for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(windows_iis_rejected_async_io_requests_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "Traffic sent",
   "type": "timeseries",
   "description": "The traffic sent by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_sent_bytes_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Traffic received",
   "type": "timeseries",
   "description": "The traffic received by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_received_bytes_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Files sent",
   "type": "timeseries",
   "description": "The files sent by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "targets": [
    {
     "expr": "increase(windows_iis_files_sent_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Files received",
   "type": "timeseries",
   "description": "The files received by an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "targets": [
    {
     "expr": "increase(windows_iis_files_received_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 35 } },
  {
   "title": "Current connections",
   "type": "timeseries",
   "description": "The number of current connections to an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "windows_iis_current_connections{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  {
   "title": "Attempted connections",
   "type": "timeseries",
   "description": "The number of attempted connections to an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(windows_iis_connection_attempts_all_instances_total{job=~\"$job\",instance=~\"$instance\", site=~\"$site\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{site}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "File cache hit ratio",
   "type": "timeseries",
   "description": "The current file cache hit ratio for an IIS server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(windows_iis_server_file_cache_hits_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval) / clamp_min(increase(windows_iis_server_file_cache_queries_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval),1) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "URI cache hit ratio",
   "type": "timeseries",
   "description": "The current URI cache hit ratio for an IIS server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance, job) (increase(windows_iis_server_uri_cache_hits_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval) / clamp_min(increase(windows_iis_server_uri_cache_queries_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval),1)) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Metadata cache hit ratio",
   "type": "timeseries",
   "description": "The current metadata cache hit ratio for an IIS server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(windows_iis_server_metadata_cache_hits_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval) / clamp_min(increase(windows_iis_server_metadata_cache_queries_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval),1) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Output cache hit ratio",
   "type": "timeseries",
   "description": "The current output cache hit ratio for an IIS site.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(windows_iis_server_output_cache_hits_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval) / clamp_min(increase(windows_iis_server_output_cache_queries_total{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset $__interval), 1) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  }
 ]
}