{
 "title": "Apache ActiveMQ instance overview",
 "tags": [ "apache-activemq" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(activemq_memory_usage_ratio{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\"}, cluster)"
   },
   {
    "name": "activemq_cluster",
    "label": "ActiveMQ cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\"}, activemq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Average broker memory usage",
   "type": "gauge",
   "description": "The percentage of memory used by both topics and queues across brokers.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Average store memory usage",
   "type": "gauge",
   "description": "The percentage of store memory used by both topics and queues across brokers.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(activemq_store_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Average temporary memory usage",
   "type": "gauge",
   "description": "The percentage of temporary memory used by both topics and queues across brokers.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(activemq_temp_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Unacknowledged messages / $__interval",
   "type": "stat",
   "description": "Recent number of unacknowledged messages on the broker.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (increase(activemq_message_total{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    }
   ]
  },
  {
   "title": "ActiveMQ alerts",
   "type": "alertlist",
   "description": "Firing alerts for Apache ActiveMQ environment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 }
  },
  {
   "title": "Producers",
   "type": "stat",
   "description": "The number of producers attached to destinations.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(activemq_queue_producer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}) + sum(activemq_topic_producer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "description": "The number of consumers subscribed to destinations on the broker.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(activemq_queue_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}) + sum(activemq_topic_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "timeseries",
   "description": "Number of messages on queue destinations, including any that have been dispatched but not yet acknowledged.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (instance, activemq_cluster, job) (activemq_queue_queue_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    }
   ]
  },
  {
   "title": "Destination memory usage",
   "type": "timeseries",
   "description": "The percentage of memory being used by topic and queue destinations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance, activemq_cluster, job) (activemq_queue_memory_percent_usage{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"^ActiveMQ.Advisory.+\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    },
    {
     "expr": "sum by (instance, activemq_cluster, job) (activemq_topic_memory_percent_usage{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"^ActiveMQ.Advisory.+\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - topic"
    }
   ]
  },
  {
   "title": "Enqueue / $__interval",
   "type": "timeseries",
   "description": "Number of messages that have been sent to destinations in a cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (activemq_cluster, job) (increase(activemq_queue_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}[$__interval] offset $__interval)) + sum by (activemq_cluster, job) (increase(activemq_topic_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  },
  {
   "title": "Dequeue / $__interval",
   "type": "timeseries",
   "description": "Number of messages that have been acknowledged (and removed) from destinations in a cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (activemq_cluster, job) (increase(activemq_queue_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}[$__interval] offset $__interval)) + sum by (activemq_cluster, job) (increase(activemq_topic_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  },
  {
   "title": "Average enqueue time",
   "type": "timeseries",
   "description": "Average time a message was held across all destinations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (instance, activemq_cluster, job) (activemq_queue_average_enqueue_time{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    },
    {
     "expr": "sum by (instance, activemq_cluster, job) (activemq_topic_average_enqueue_time{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"^ActiveMQ.Advisory.+\"})",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - topic"
    }
   ]
  },
  {
   "title": "Expired messages / $__interval",
   "type": "timeseries",
   "description": "Number of messages across destinations that are expired.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, activemq_cluster, job) (increase(activemq_queue_expired_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - queue"
    },
    {
     "expr": "sum by (instance, activemq_cluster, job) (increase(activemq_topic_expired_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"^ActiveMQ.Advisory.+\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }} - topic"
    }
   ]
  },
  { "title": "JVM resources", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 41 } },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "description": "The time spent performing recent garbage collections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_duration_seconds{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Garbage collection count / $__interval",
   "type": "timeseries",
   "description": "The recent increase in the number of garbage collection events for the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", name=\"G1 Young Generation\"}[$__interval] offset $__interval)",
     "legendFormat": "{{ activemq_cluster }} - {{ instance }}"
    }
   ]
  }
 ]
}