{
 "title": "Apache ActiveMQ topic overview",
 "tags": [ "apache-activemq" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(activemq_memory_usage_ratio{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\"}, cluster)"
   },
   {
    "name": "activemq_cluster",
    "label": "ActiveMQ cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\"}, activemq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "k_selector",
    "label": "Top topic count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   },
   { "name": "name", "label": "Topic by name" }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Topic count",
   "type": "stat",
   "description": "Number of active topics (excluding advisory topics).",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count (activemq_topic_queue_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "stat",
   "description": "Total number of topic producers.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_topic_producer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "description": "Total number of topic consumers.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_topic_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Average consumers per topic",
   "type": "stat",
   "description": "Average number of consumers per topic.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "avg (activemq_topic_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Top topics by enqueue rate",
   "type": "timeseries",
   "description": "Rate of messages being enqueued to topics.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "topk by (instance, activemq_cluster, job) ($k_selector, rate(activemq_topic_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}[$__rate_interval]))",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Top topics by dequeue rate",
   "type": "timeseries",
   "description": "Rate of messages being dequeued from topics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "topk by (instance, activemq_cluster, job) ($k_selector, rate(activemq_topic_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}[$__rate_interval]))",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Top topics by average enqueue time",
   "type": "timeseries",
   "description": "Average time to enqueue messages to topics.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk by (instance, activemq_cluster, job) ($k_selector, activemq_topic_average_enqueue_time{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Top topics by expired rate",
   "type": "timeseries",
   "description": "Rate of messages expiring in topics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "topk by (instance, activemq_cluster, job) ($k_selector, activemq_topic_expired_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Top topics by consumers",
   "type": "timeseries",
   "description": "Top topics by consumers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk by (instance, activemq_cluster, job) ($k_selector, activemq_topic_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\", destination=~\".*$name.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Topic average message size",
   "type": "timeseries",
   "description": "Average size of messages in topics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "activemq_topic_average_message_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Topic summary",
   "type": "table",
   "description": "Summary of topics showing topic name, enqueue and dequeue rate, average enqueue time, and average message size.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(activemq_topic_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\", destination=~\".*$name.*\"}[$__rate_interval])",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    },
    {
     "expr": "rate(activemq_topic_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\", destination=~\".*$name.*\"}[$__rate_interval])",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    },
    {
     "expr": "activemq_topic_average_enqueue_time{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\", destination=~\".*$name.*\"}",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    },
    {
     "expr": "activemq_topic_average_message_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\", destination=~\".*$name.*\"}",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  }
 ]
}