{
 "title": "Hubble / Timescape",
 "tags": [ "hubble" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(timescape_ingestor_ingest_running, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(timescape_ingestor_ingest_running{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(timescape_ingestor_ingest_running{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Timescape Ingestor Instances Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Instances" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(timescape_ingestor_ingest_running{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Duration Seconds Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(timescape_clickhouse_queries_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(timescape_clickhouse_queries_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(timescape_clickhouse_queries_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Ingestor Ingest Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(timescape_ingestor_ingest_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(timescape_ingestor_ingest_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(timescape_ingestor_ingest_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Flows Ingested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingestor_flows_ingested_total{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Queries Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(timescape_clickhouse_queries_results_sum{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]) / rate(timescape_clickhouse_queries_results_count{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingest filter Filtered Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingestor_ingestfilter_filtered_errors_total{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingest Filter Batch Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(timescape_ingestor_ingestfilter_batch_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(timescape_ingestor_ingestfilter_batch_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(timescape_ingestor_ingestfilter_batch_duration_seconds_bucket{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Ingestor Ingest Filter Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingestor_ingestfilter_filtered_total{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingest Filter Skipped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingestor_ingestfilter_filtered_skipped_total{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestor GetInfo Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(timescape_ingestor_ingestlog_getinfo_queries{pod=~\"$pod\", cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}