{
 "title": "MongoDB Atlas elections overview",
 "description": "Overview of MongoDB Atlas election metrics.",
 "tags": [ "mongodb-atlas-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mongodb_network_bytesIn{}, job)"
   },
   {
    "name": "cl_name",
    "label": "Atlas cluster",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\"}, cl_name)"
   },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\"}, instance)"
   },
   {
    "name": "rs_nm",
    "label": "Replica set",
    "query": "label_values(mongodb_network_bytesIn, rs_nm)"
   }
  ]
 },
 "panels": [
  { "title": "Elections", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Step-up elections / $__interval",
   "type": "timeseries",
   "description": "The number of elections called and elections won by the node when the primary stepped down.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_stepUpCmd_called{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - called"
    },
    {
     "expr": "increase(mongodb_electionMetrics_stepUpCmd_successful{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - successful"
    }
   ]
  },
  {
   "title": "Priority elections / $__interval",
   "type": "timeseries",
   "description": "The number of elections called and elections won by the node when it had a higher priority than the primary node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_priorityTakeover_called{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - called"
    },
    {
     "expr": "increase(mongodb_electionMetrics_priorityTakeover_successful{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - successful"
    }
   ]
  },
  {
   "title": "Takeover elections / $__interval",
   "type": "timeseries",
   "description": "The number of elections called and elections won by the node when it was more current than the primary node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_catchUpTakeover_called{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - called"
    },
    {
     "expr": "increase(mongodb_electionMetrics_catchUpTakeover_successful{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - successful"
    }
   ]
  },
  {
   "title": "Timeout elections / $__interval",
   "type": "timeseries",
   "description": "The number of elections called and elections won by the node when the time it took to reach the primary node exceeded the election timeout limit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_electionTimeout_called{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - called"
    },
    {
     "expr": "increase(mongodb_electionMetrics_electionTimeout_successful{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - successful"
    }
   ]
  },
  { "title": "Catch-ups", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "Catch-ups / $__interval",
   "type": "timeseries",
   "description": "The number of times the node had to catch up to the highest known oplog entry.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_numCatchUps{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Catch-ups skipped / $__interval",
   "type": "timeseries",
   "description": "The number of times the node skipped the catch up process when it was the newly elected primary.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_numCatchUpsSkipped{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Catch-ups succeeded / $__interval",
   "type": "timeseries",
   "description": "The number of times the node succeeded in catching up when it was the newly elected primary.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_numCatchUpsSucceeded{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Catch-ups failed / $__interval",
   "type": "timeseries",
   "description": "The number of times the node failed in catching up when it was the newly elected primary.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_numCatchUpsFailedWithError{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Catch-up timeouts / $__interval",
   "type": "timeseries",
   "description": "The number of times the node timed out during the catch-up process when it was the newly elected primary.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mongodb_electionMetrics_numCatchUpsTimedOut{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average catch-up operations",
   "type": "timeseries",
   "description": "The average number of operations done during the catch-up process when this node is the newly elected primary.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_electionMetrics_averageCatchUpOps{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}