{
 "title": "MongoDB Atlas cluster overview",
 "description": "Overview of MongoDB Atlas cluster metrics.",
 "tags": [ "mongodb-atlas-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mongodb_network_bytesIn{}, job)"
   },
   {
    "name": "cl_name",
    "label": "Atlas cluster",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\"}, cl_name)"
   },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\"}, instance)"
   },
   {
    "name": "rs_nm",
    "label": "Replica set",
    "query": "label_values(mongodb_network_bytesIn, rs_nm)"
   }
  ]
 },
 "panels": [
  { "title": "Shard", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Shard nodes",
   "type": "table",
   "description": "An inventory table for shard nodes in the environment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\", cl_role=\"shardsvr\"}"
    }
   ]
  },
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Config nodes",
   "type": "table",
   "description": "An inventory table for config nodes in the environment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\", cl_role=\"configsvr\"}"
    }
   ]
  },
  { "title": "mongos", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "mongos nodes",
   "type": "table",
   "description": "An inventory table for mongos nodes in the environment.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\", cl_role=\"mongos\"}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Hardware I/O",
   "type": "timeseries",
   "description": "The number of read and write I/O's processed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(hardware_disk_metrics_read_count{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\",cl_name=~\"$cl_name\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - reads"
    },
    {
     "expr": "sum(rate(hardware_disk_metrics_write_count{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\",cl_name=~\"$cl_name\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - writes"
    }
   ]
  },
  {
   "title": "Hardware I/O wait time / $__interval",
   "type": "timeseries",
   "description": "The amount of time spent waiting for I/O requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(hardware_disk_metrics_read_time_milliseconds{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\",cl_name=~\"$cl_name\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - reads"
    },
    {
     "expr": "sum(increase(hardware_disk_metrics_write_time_milliseconds{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\",cl_name=~\"$cl_name\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - writes"
    }
   ]
  },
  {
   "title": "Hardware CPU interrupt service time / $__interval",
   "type": "timeseries",
   "description": "The amount of time spent servicing CPU interrupts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(hardware_system_cpu_irq_milliseconds{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\",cl_name=~\"$cl_name\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "The amount of RAM and virtual memory being used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(mongodb_mem_resident{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}) by (cl_name)",
     "legendFormat": "{{cl_name}} - RAM"
    },
    {
     "expr": "sum(mongodb_mem_virtual{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}) by (cl_name)",
     "legendFormat": "{{cl_name}} - virtual"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "description": "The percentage of hardware space used.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum (hardware_disk_metrics_disk_space_used_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) by (cl_name)) / clamp_min((sum (hardware_disk_metrics_disk_space_used_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) by (cl_name)) + (sum (hardware_disk_metrics_disk_space_free_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) by (cl_name)), 1)",
     "legendFormat": "{{cl_name}}"
    }
   ]
  },
  {
   "title": "Network requests",
   "type": "timeseries",
   "description": "The number of distinct requests that the server has received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_network_numRequests{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}}"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "timeseries",
   "description": "The number of bytes sent and received over network connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - received"
    },
    {
     "expr": "sum(rate(mongodb_network_bytesOut{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - sent"
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "timeseries",
   "description": "The rate of DNS and SSL operations that took longer than 1 second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_network_numSlowDNSOperations{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - DNS"
    },
    {
     "expr": "sum(rate(mongodb_network_numSlowSSLOperations{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - SSL"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 68 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The rate of incoming connections to the cluster created.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_connections_totalCreated{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}}"
    }
   ]
  },
  {
   "title": "Read/Write operations",
   "type": "timeseries",
   "description": "The number of read and write operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_opLatencies_reads_ops{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - reads"
    },
    {
     "expr": "sum(rate(mongodb_opLatencies_writes_ops{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])) by (cl_name)",
     "legendFormat": "{{cl_name}} - writes"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "piechart",
   "description": "The number of insert, query, update, and delete operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_opcounters_insert{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - insert"
    },
    {
     "expr": "sum(increase(mongodb_opcounters_query{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - query"
    },
    {
     "expr": "sum(increase(mongodb_opcounters_update{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - update"
    },
    {
     "expr": "sum(increase(mongodb_opcounters_delete{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - delete"
    }
   ]
  },
  {
   "title": "Read/Write latency / $__interval",
   "type": "timeseries",
   "description": "The latency for read and write operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_opLatencies_reads_latency{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - reads"
    },
    {
     "expr": "increase(mongodb_opLatencies_writes_latency{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{cl_name}} - writes"
    }
   ]
  },
  { "title": "Locks", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 93 } },
  {
   "title": "Current queue",
   "type": "timeseries",
   "description": "The number of reads and writes queued because of a lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(mongodb_globalLock_currentQueue_readers{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}) by (cl_name)",
     "legendFormat": "{{cl_name}} - reads"
    },
    {
     "expr": "sum(mongodb_globalLock_currentQueue_writers{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}) by (cl_name)",
     "legendFormat": "{{cl_name}} - writes"
    }
   ]
  },
  {
   "title": "Active client operations",
   "type": "timeseries",
   "description": "The number of reads and writes being actively performed by connected clients.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum(mongodb_globalLock_activeClients_readers{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) by (cl_name)",
     "legendFormat": "{{cl_name}} - reads"
    },
    {
     "expr": "sum(mongodb_globalLock_activeClients_writers{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) by (cl_name)",
     "legendFormat": "{{cl_name}} - writes"
    }
   ]
  },
  {
   "title": "Database deadlocks / $__interval",
   "type": "timeseries",
   "description": "The number of deadlocks for database level locks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum(increase(mongodb_locks_Database_deadlockCount_W{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - exclusive"
    },
    {
     "expr": "sum(increase(mongodb_locks_Database_deadlockCount_w{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - intent exclusive"
    },
    {
     "expr": "sum(increase(mongodb_locks_Database_deadlockCount_R{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - shared"
    },
    {
     "expr": "sum(increase(mongodb_locks_Database_deadlockCount_r{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - intent shared"
    }
   ]
  },
  {
   "title": "Database waits acquiring lock / $__interval",
   "type": "timeseries",
   "description": "The number of times lock acquisitions encounter waits for database level locks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum(increase(mongodb_locks_Database_acquireWaitCount_W{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - exclusive"
    },
    {
     "expr": "sum(increase(mongodb_locks_Database_acquireWaitCount_w{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - intent exclusive"
    },
    {
     "expr": "sum(increase(mongodb_locks_Database_acquireWaitCount_R{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - shared"
    },
    {
     "expr": "sum(increase(mongodb_locks_Database_acquireWaitCount_r{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)) by (cl_name)",
     "legendFormat": "{{cl_name}} - intent shared"
    }
   ]
  }
 ]
}