{
 "title": "F5 BIG-IP pool overview",
 "tags": [ "f5-bigip-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "bigip_pool",
    "label": "BIG-IP pool",
    "query": "label_values(bigip_pool_status_availability_state{}, pool)"
   },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_pool_status_availability_state{, pool=~\"$bigip_pool\"}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Pool overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Availability status",
   "type": "table",
   "description": "The availability status of the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_pool_status_availability_state{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests / $__interval",
   "type": "timeseries",
   "description": "The number of requests made to the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_tot_requests{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "timeseries",
   "description": "The number of active and minimum required members within the pool.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_pool_active_member_cnt{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    },
    {
     "expr": "bigip_pool_min_active_members{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The current and maximum number of node connections within the pool.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_pool_serverside_cur_conns{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}} - current"
    },
    {
     "expr": "bigip_pool_serverside_max_conns{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}} - max"
    }
   ]
  },
  {
   "title": "Connection queue depth",
   "type": "timeseries",
   "description": "The depth of connection queues within the pool, including the current depth.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_pool_connq_depth{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connection queue serviced / $__interval",
   "type": "timeseries",
   "description": "The number of connections that have been serviced within the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_connq_serviced{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic inbound",
   "type": "timeseries",
   "description": "The rate of data received from virtual servers by the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_pool_serverside_bytes_in{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic outbound",
   "type": "timeseries",
   "description": "The rate of data sent from virtual servers by the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_pool_serverside_bytes_out{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets inbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets received from virtual servers by the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_serverside_pkts_in{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets outbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets sent from virtual servers by the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_pool_serverside_pkts_out{job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  }
 ]
}