{
 "title": "F5 BIG-IP virtual server overview",
 "description": "Detailed view of F5 BIG-IP virtual server metrics and status.",
 "tags": [ "f5-bigip-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "bigip_virtual_server",
    "label": "BIG-IP virtual server",
    "query": "label_values(bigip_vs_status_availability_state{job=~\"$job\", instance=~\"$instance\"}, virtual_server)"
   },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_vs_status_availability_state{job=~\"$job\", instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\"}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Availability status",
   "type": "table",
   "description": "The availability status of the virtual server.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_vs_status_availability_state{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  { "title": "Clientside Metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 10 } },
  {
   "title": "Clientside current connections",
   "type": "timeseries",
   "description": "The number of current clientside connections on the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_vs_clientside_cur_conns{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests / $__interval",
   "type": "timeseries",
   "description": "The number of requests made to the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_vs_tot_requests{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Clientside bytes in / $__interval",
   "type": "timeseries",
   "description": "The number of bytes received on the clientside.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_vs_clientside_bytes_in{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Clientside bytes out / $__interval",
   "type": "timeseries",
   "description": "The number of bytes sent on the clientside.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_vs_clientside_bytes_out{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Mean connection duration",
   "type": "timeseries",
   "description": "The mean connection duration on the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_vs_cs_mean_conn_dur{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  { "title": "Ephemeral Metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 35 } },
  {
   "title": "Ephemeral current connections",
   "type": "timeseries",
   "description": "The number of current ephemeral connections on the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_vs_ephemeral_cur_conns{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral bytes in / $__interval",
   "type": "timeseries",
   "description": "The number of ephemeral bytes received.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_vs_ephemeral_bytes_in{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral bytes out / $__interval",
   "type": "timeseries",
   "description": "The number of ephemeral bytes sent.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_vs_ephemeral_bytes_out{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", virtual_server=~\"$bigip_virtual_server\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{virtual_server}} - {{instance}}"
    }
   ]
  }
 ]
}