{
 "title": "F5 BIG-IP pool overview",
 "description": "Detailed view of F5 BIG-IP pool metrics and status.",
 "tags": [ "f5-bigip-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\", instance=~\"$instance\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "bigip_pool",
    "label": "BIG-IP pool",
    "query": "label_values(bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\"}, pool)"
   },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\", pool=~\"$bigip_pool\"}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Availability status",
   "type": "table",
   "description": "The availability status of the pool.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_pool_status_availability_state{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 10 } },
  {
   "title": "Active member count",
   "type": "timeseries",
   "description": "The number of active members in the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_pool_active_member_cnt{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connection queue depth",
   "type": "timeseries",
   "description": "The depth of the connection queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_pool_connq_depth{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests / $__interval",
   "type": "timeseries",
   "description": "The number of requests made to the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_pool_tot_requests{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Serverside bytes in / $__interval",
   "type": "timeseries",
   "description": "The number of bytes received on the serverside.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_pool_serverside_bytes_in{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Serverside bytes out / $__interval",
   "type": "timeseries",
   "description": "The number of bytes sent on the serverside.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(bigip_pool_serverside_bytes_out{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}[$__rate_interval])\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Serverside current connections",
   "type": "timeseries",
   "description": "The number of current serverside connections on the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  bigip_pool_serverside_cur_conns{job=~\"$job\", instance=~\"$instance\",job=~\"$job\",instance=~\"$instance\", pool=~\"$bigip_pool\", partition=~\"$bigip_partition\"}\n)",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  }
 ]
}