{
 "title": "process overview",
 "tags": [ "proc" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(runtime_uptime{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(runtime_uptime{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Process overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "process_uptime{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Process start time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_start_time{job=~\"$job\",instance=~\"$instance\"} * 1000\n)",
     "legendFormat": "{{instance}}: Process start time"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "System's load average.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_runtime_jvm_system_cpu_load_1m{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Load average"
    }
   ]
  },
  {
   "title": "CPU usage (process)",
   "type": "timeseries",
   "description": "CPU usage (process) (avg): Process CPU usage.  \n\nCPU usage (system) (avg): CPU Usage of host system.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_runtime_jvm_cpu_utilization{job=~\"$job\",instance=~\"$instance\"} * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (process)"
    },
    {
     "expr": "avg by (job,instance) (\n  process_runtime_jvm_system_cpu_utilization{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: CPU usage (system)"
    }
   ]
  },
  {
   "title": "Process memory used (rss)",
   "type": "timeseries",
   "description": "Process resident memory size in bytes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process memory used (rss)"
    }
   ]
  },
  {
   "title": "Process files open",
   "type": "timeseries",
   "description": "Process files open (avg): Process files opened.  \n\nProcess files max (avg): Process files opened limit.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_files_open{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files open"
    },
    {
     "expr": "avg by (job,instance) (\n  process_files_max{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files max"
    }
   ]
  }
 ]
}