{
 "title": "Apache CouchDB nodes",
 "tags": [ "apache-couchdb-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(couchdb_database_reads_total{}, job)"
   },
   {
    "name": "couchdb_cluster",
    "label": "CouchDB cluster",
    "query": "label_values(couchdb_database_reads_total{job=~\"$job\"}, couchdb_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(couchdb_database_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(couchdb_database_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Erlang memory usage",
   "type": "timeseries",
   "description": "The amount of memory used by a node's Erlang Virtual Machine.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "couchdb_erlang_memory_bytes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", memory_type=\"total\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open OS files",
   "type": "timeseries",
   "description": "The total number of file descriptors open on a node.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "couchdb_open_os_files_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}\nor\ncouchdb_open_os_files{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open databases",
   "type": "timeseries",
   "description": "The total number of open databases on a node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "couchdb_open_databases_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}\nor\ncouchdb_open_databases{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database writes",
   "type": "timeseries",
   "description": "The total number of database writes on a node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(couchdb_database_writes_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database reads",
   "type": "timeseries",
   "description": "The total number of database reads on a node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(couchdb_database_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "View reads",
   "type": "timeseries",
   "description": "The total number of view reads on a node.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_view_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "View timeouts",
   "type": "timeseries",
   "description": "The total number of view requests that timed out on a node.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_view_timeouts_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temporary view reads",
   "type": "timeseries",
   "description": "The total number of temporary view reads on a node.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_temporary_view_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 23 } },
  {
   "title": "Bulk requests",
   "type": "timeseries",
   "description": "The total number of bulk requests on a node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_bulk_requests_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request latency quantiles",
   "type": "histogram",
   "description": "The average request latency for a node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster, instance, quantile) (couchdb_request_time_seconds{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Request methods",
   "type": "timeseries",
   "description": "The request rate split by HTTP Method for a node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_request_methods{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - {{method}}"
    }
   ]
  },
  {
   "title": "Response status overview",
   "type": "piechart",
   "description": "Responses grouped by HTTP status type (2xx, 3xx, 4xx, 5xx). Filter by instance to see specific node data.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster, instance) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"2.*\"}[$__interval:] offset -$__interval)) != 0",
     "legendFormat": "{{instance}} - 2xx"
    },
    {
     "expr": "sum by(job, couchdb_cluster, cluster, instance) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"3.*\"}[$__interval:] offset -$__interval)) != 0",
     "legendFormat": "{{instance}} - 3xx"
    },
    {
     "expr": "sum by(job, couchdb_cluster, cluster, instance) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"4.*\"}[$__interval:] offset -$__interval)) != 0",
     "legendFormat": "{{instance}} - 4xx"
    },
    {
     "expr": "sum by(job, couchdb_cluster, cluster, instance) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"5.*\"}[$__interval:] offset -$__interval)) != 0",
     "legendFormat": "{{instance}} - 5xx"
    }
   ]
  },
  {
   "title": "Good response statuses",
   "type": "timeseries",
   "description": "The total number of good response (HTTP 2xx-3xx) statuses on a node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"[23].*\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - {{code}}"
    }
   ]
  },
  {
   "title": "Error response statuses",
   "type": "timeseries",
   "description": "The total number of error response (HTTP 4xx-5xx) statuses on a node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"[45].*\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - {{code}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 48 } },
  {
   "title": "Log types",
   "type": "timeseries",
   "description": "The number of logged messages for a node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(couchdb_couch_log_requests_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{instance}} - {{level}}"
    }
   ]
  }
 ]
}