{
 "title": "Apache CouchDB overview",
 "tags": [ "apache-couchdb-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(couchdb_database_reads_total{}, job)"
   },
   {
    "name": "couchdb_cluster",
    "label": "CouchDB cluster",
    "query": "label_values(couchdb_database_reads_total{job=~\"$job\"}, couchdb_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(couchdb_database_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(couchdb_database_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Number of clusters",
   "type": "stat",
   "description": "The number of clusters being reported.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(job, couchdb_cluster, cluster) (couchdb_request_time_seconds_count{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "description": "The number of nodes being reported.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by(job, couchdb_cluster, cluster, instance) (couchdb_request_time_seconds_count{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Clusters healthy",
   "type": "stat",
   "description": "Percentage of clusters that have all nodes that are currently reporting healthy.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(min by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_cluster_is_stable{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})) / count(count by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_cluster_is_stable{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})) * 100",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Open OS files",
   "type": "timeseries",
   "description": "The total number of file descriptors open aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_open_os_files_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})\nor\nsum by(job, couchdb_cluster, cluster) (couchdb_open_os_files{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Open databases",
   "type": "timeseries",
   "description": "The total number of open databases aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_open_databases_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})\nor\nsum by(job, couchdb_cluster, cluster) (couchdb_open_databases{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Database writes",
   "type": "timeseries",
   "description": "The total number of database writes aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (rate(couchdb_database_writes_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Database reads",
   "type": "timeseries",
   "description": "The total number of database reads aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (rate(couchdb_database_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "View reads",
   "type": "timeseries",
   "description": "The total number of view reads aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (rate(couchdb_httpd_view_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "View timeouts",
   "type": "timeseries",
   "description": "The total number of view requests that timed out aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (rate(couchdb_httpd_view_timeouts_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Temporary view reads",
   "type": "timeseries",
   "description": "The total number of temporary view reads aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (rate(couchdb_httpd_temporary_view_reads_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "Request methods",
   "type": "timeseries",
   "description": "The request rate split by HTTP Method aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster, method) (increase(couchdb_httpd_request_methods{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval))",
     "legendFormat": "{{ couchdb_cluster }} - {{method}}"
    }
   ]
  },
  {
   "title": "Request latency quantiles",
   "type": "histogram",
   "description": "The request latency aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster, quantile) (couchdb_request_time_seconds{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster }} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Bulk requests",
   "type": "timeseries",
   "description": "The total number of bulk requests aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (rate(couchdb_httpd_bulk_requests_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))\nor\nsum by(job, couchdb_cluster, cluster) (rate(couchdb_httpd_bulk_requests{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }}"
    }
   ]
  },
  {
   "title": "Response status overview",
   "type": "piechart",
   "description": "The responses grouped by HTTP status type (2xx, 3xx, 4xx, and 5xx) aggregated across all nodes by default. If you want to see the data for a specific node, you can filter by instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"2.*\"}[$__interval:] offset $__interval)) != 0",
     "legendFormat": "{{ couchdb_cluster }} - 2xx"
    },
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"3.*\"}[$__interval:] offset $__interval)) != 0",
     "legendFormat": "{{ couchdb_cluster }} - 3xx"
    },
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"4.*\"}[$__interval:] offset $__interval)) != 0",
     "legendFormat": "{{ couchdb_cluster }} - 4xx"
    },
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (increase(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"5.*\"}[$__interval:] offset $__interval)) != 0",
     "legendFormat": "{{ couchdb_cluster }} - 5xx"
    }
   ]
  },
  {
   "title": "Good response statuses",
   "type": "timeseries",
   "description": "The total number of good response (HTTP 2xx-3xx) statuses aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster, code) (rate(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"[23].*\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }} - {{code}}"
    }
   ]
  },
  {
   "title": "Error response statuses",
   "type": "timeseries",
   "description": "The total number of error response statuses (HTTP 4xx-5xx) aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster, code) (rate(couchdb_httpd_status_codes{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", code=~\"[45].*\"}[$__rate_interval]))",
     "legendFormat": "{{ couchdb_cluster }} - {{code}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 58 } },
  {
   "title": "Replicator changes manager deaths",
   "type": "timeseries",
   "description": "Number of replicator changes manager processor deaths across all nodes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (increase(couchdb_couch_replicator_changes_manager_deaths_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval))",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  },
  {
   "title": "Replicator changes queue deaths",
   "type": "timeseries",
   "description": "Number of replicator changes queue processor deaths across all nodes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_changes_queue_deaths_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  },
  {
   "title": "Replicator changes reader deaths",
   "type": "timeseries",
   "description": "Number of replicator changes reader processor deaths across all nodes.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_changes_reader_deaths_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  },
  {
   "title": "Replicator connection owner crashes",
   "type": "timeseries",
   "description": "Number of replicator connection owner crashes across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_connection_owner_crashes_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  },
  {
   "title": "Replicator connection worker crashes",
   "type": "timeseries",
   "description": "Number of replicator connection worker crashes across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_connection_worker_crashes_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  },
  {
   "title": "Replicator jobs crashes",
   "type": "timeseries",
   "description": "Number of replicator jobs crashes across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_jobs_crashes_total{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  },
  {
   "title": "Replicator jobs queued",
   "type": "timeseries",
   "description": "Number of replicator jobs queued across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, couchdb_cluster, cluster) (couchdb_couch_replicator_jobs_pending{job=~\"$job\",couchdb_cluster=~\"$couchdb_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ couchdb_cluster}}"
    }
   ]
  }
 ]
}