{
 "title": "Metrics endpoint scrape overview",
 "tags": [ "metrics-endpoint" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"metrics_endpoint_export_response_success\",job!=\"\"}, job)"
   },
   {
    "name": "scrape_job",
    "label": "Scrape_job",
    "query": "label_values({__name__=~\"metrics_endpoint_export_response_success\",job!=\"\",job=~\"$job\"}, scrape_job)"
   }
  ]
 },
 "panels": [
  { "title": "Scrape overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; justify-content: center; align-items: center;\">\n  <img\n     style=\"width:auto;height:100%\"\n     src=\"https://storage.googleapis.com/grafanalabs-integration-logos/metrics-endpoint-prometheus.svg\">\n</div>\n"
   }
  },
  {
   "title": "Samples scraped",
   "type": "stat",
   "description": "Number of samples scraped. Every unique metric/label combination counts as a separate sample.",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,scrape_job) (\n  scrape_samples_scraped{job!=\"\",job=~\"$job\",scrape_job=~\"$scrape_job\"}\n)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "options": {
    "content": "# Metrics scrape dashboard\nThis dashboard helps you analyze scrape metadata for the [Metrics Endpoint integration](https://grafana.com/docs/grafana-cloud/monitor-infrastructure/integrations/integration-reference/integration-metrics-endpoint/).\nIt can help you debug issues with metrics not arriving or unexpected cardinality.\n\nFor metrics on Metrics Endpoint itself, refer to the [other dashboards provided by this integration](/dashboards/f/integration---metrics-endpoint).\n"
   }
  },
  {
   "title": "Highest cardinality metrics",
   "type": "timeseries",
   "description": "Top ten metrics with the highest cardinality. For more information on cardinality, refer to the [cardinality management dashboards](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/analyze-costs/metrics-costs/prometheus-metrics-costs/cardinality-management/)",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,count({job!=\"\",job=~\"$job\",scrape_job=~\"$scrape_job\"}) by (__name__))",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "Scrape status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by (job,scrape_job) (\n  metrics_endpoint_export_response_success{job!=\"\",job=~\"$job\",scrape_job=~\"$scrape_job\"}\n)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "description": "How long it takes for the metrics scrape to complete. Long durations might indicate issues with the endpoint.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job,scrape_job) (\n  scrape_duration_seconds{job!=\"\",job=~\"$job\",scrape_job=~\"$scrape_job\"}\n)",
     "legendFormat": "{{scrape_job}}: Scrape duration"
    }
   ]
  }
 ]
}