{
 "title": "PHP-FPM Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pool", "label": "Pool", "query": "label_values(phpfpm_up, pool)" }
  ]
 },
 "panels": [
  { "title": "Current (${pool})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scrape Failures",
   "type": "stat",
   "description": "The number of scrape attempts that have failed (all pools)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(phpfpm_scrape_failures{pool=~\"$pool\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Worker Limit Reached",
   "type": "stat",
   "description": "The number of times the process limit has been reached (all pools), when the process manager tries to start more children (only with \"dynamic\" and \"ondemand\" process management)\n\nGenerally any value > 0 should be interpreted as php-fpm over capacity.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(phpfpm_max_children_reached{pool=~\"$pool\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Workers Utilization",
   "type": "gauge",
   "description": "The number of active workers at present. This value can be misleading since php-fpm allocates workers differently depending on the \"pm\" (process manager) setting.\n\nThis value must ALWAYS be read with the \"Max Children Reached\" value, since all workers being active just means that php-fpm has created an appropriate number of workers for the given requests.\n\nIf \"Max Children Reached\" > 0, this is cause for concern.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum(sum_over_time(phpfpm_active_processes{pool=~\"$pool\"}[$__interval])) / \n  sum(sum_over_time(phpfpm_total_processes{pool=~\"$pool\"}[$__interval]))\n)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Accepted Requests",
   "type": "stat",
   "description": "The number of request accepted (all pools)",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(phpfpm_accepted_connections{pool=~\"$pool\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Pending Requests",
   "type": "stat",
   "description": "The number of request in the queue of pending connections (all pools)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(phpfpm_listen_queue{pool=~\"$pool\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "stat",
   "description": "The number of requests (across all pools) that took longer to respond than the value configured in \"request_slowlog_timeout\" (hint: \"slowlog\" also needs to be set in order for this to work)",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(phpfpm_slow_requests{pool=~\"$pool\"}[$__interval]))"
    }
   ]
  },
  { "title": "Historic (per pool)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Accepted Requests",
   "type": "graph",
   "description": "The number of request accepted by the pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(phpfpm_accepted_connections{pool=~\"$pool\"}[$__interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pending Requests",
   "type": "graph",
   "description": "The number of request in the queue of pending connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(phpfpm_listen_queue{pool=~\"$pool\"}[$__interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Worker Limit Reached",
   "type": "graph",
   "description": "The number of times the process limit has been reached, when the process manager tries to start more children (only with \"dynamic\" and \"ondemand\" process management)\n\nGenerally any value > 0 should be interpreted as php-fpm over capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(phpfpm_max_children_reached{pool=~\"$pool\"}[$__interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "graph",
   "description": "The number of requests that took longer to respond than the value configured in \"request_slowlog_timeout\" (hint: \"slowlog\" also needs to be set in order for this to work)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(phpfpm_slow_requests{pool=~\"$pool\"}[$__interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Workers Utilization",
   "type": "graph",
   "description": "The number of active workers at present. This value can be misleading since php-fpm allocates workers differently depending on the \"pm\" (process manager) setting.\n\nThis value must ALWAYS be read with the \"Max Children Reached\" value, since all workers being active just means that php-fpm has created an appropriate number of workers for the given requests.\n\nIf \"Max Children Reached\" > 0, this is cause for concern.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pool) (\n  sum by (pool) (sum_over_time(phpfpm_active_processes{pool=~\"$pool\"}[$__interval])) / \n  sum by (pool) (sum_over_time(phpfpm_total_processes{pool=~\"$pool\"}[$__interval]))\n)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Scrape Failures",
   "type": "graph",
   "description": "The number of scrape attempts that have failed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pool) (increase(phpfpm_scrape_failures{pool=~\"$pool\"}[$__interval]))",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}