{
 "title": "MSSQL pages",
 "description": "An overview of MSSQL paging metrics.",
 "tags": [ "mssql-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mssql_build_info{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mssql_build_info{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mssql_build_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Page file memory",
   "type": "timeseries",
   "description": "Memory used for the OS page file.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mssql_os_page_file{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Buffer cache hit percentage",
   "type": "timeseries",
   "description": "Percentage of page found and read from the SQL Server buffer cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mssql_buffer_cache_hit_ratio{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page checkpoints",
   "type": "timeseries",
   "description": "Rate of page checkpoints per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "checkpoints/s" } },
   "targets": [
    {
     "expr": "mssql_checkpoint_pages_sec{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "timeseries",
   "description": "The number of page faults that were incurred by the SQL Server process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "faults" } },
   "targets": [
    {
     "expr": "increase(mssql_page_fault_count_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval:])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}