{
 "title": "MSSQL overview",
 "description": "An overview of an MSSQL instance.",
 "tags": [ "mssql-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mssql_build_info{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mssql_build_info{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mssql_build_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(mssql_log_growths_total{job=~\"$job\", instance=~\"$instance\"}, db)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of network connections to each database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "mssql_connections{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "Batch requests",
   "type": "timeseries",
   "description": "Number of batch requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mssql_batch_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Severe errors",
   "type": "timeseries",
   "description": "Number of severe errors that caused connections to be killed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "increase(mssql_kill_connection_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "description": "Rate of deadlocks occurring over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deadlocks" } },
   "targets": [
    {
     "expr": "rate(mssql_deadlocks_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS memory usage",
   "type": "timeseries",
   "description": "The amount of physical memory available and used by SQL Server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mssql_os_memory{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  {
   "title": "Memory manager",
   "type": "timeseries",
   "description": "The committed memory and target committed memory for the SQL Server memory manager. See https://learn.microsoft.com/en-us/sql/relational-databases/performance-monitor/monitor-memory-usage?view=sql-server-ver16#isolating-memory-used-by-",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mssql_server_total_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - total"
    },
    {
     "expr": "mssql_server_target_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - target"
    }
   ]
  },
  {
   "title": "Committed memory utilization",
   "type": "gauge",
   "description": "The committed memory utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * mssql_server_total_memory_bytes{job=~\"$job\", instance=~\"$instance\"} / clamp_min(mssql_available_commit_memory_bytes{job=~\"$job\", instance=~\"$instance\"},1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "description": "Recent logs from the error log file.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\", log_type=\"mssql_error\"}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Database write stall duration",
   "type": "timeseries",
   "description": "The current stall (latency) for database writes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(mssql_io_stall_seconds_total{job=~\"$job\", instance=~\"$instance\", db=~\"$database\", operation=\"write\"}[$__rate_interval:])",
     "legendFormat": "{{instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "Database read stall duration",
   "type": "timeseries",
   "description": "The current stall (latency) for database reads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(mssql_io_stall_seconds_total{job=~\"$job\", instance=~\"$instance\", db=~\"$database\", operation=\"read\"}[$__rate_interval:])",
     "legendFormat": "{{instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "Transaction log expansions",
   "type": "timeseries",
   "description": "Number of times the transaction log has been expanded for a database.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "expansions" } },
   "targets": [
    {
     "expr": "increase(mssql_log_growths_total{job=~\"$job\", instance=~\"$instance\", db=~\"$database\"}[$__rate_interval:])",
     "legendFormat": "{{instance}} - {{db}}"
    }
   ]
  }
 ]
}