{
 "title": "ZooKeeper overview",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "kafka_cluster",
    "label": "Kafka_cluster",
    "query": "label_values({__name__=~\"outstanding_requests|zookeeper_outstandingrequests|outstanding_requests\"}, kafka_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"outstanding_requests|zookeeper_outstandingrequests|outstanding_requests\",kafka_cluster=~\"$kafka_cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Quorum size",
   "type": "stat",
   "description": "Quorum size of ZooKeeper ensemble.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (kafka_cluster) (\n  quorum_size{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)\nor\nmax by (kafka_cluster) (\n  zookeeper_status_quorumsize{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Quorum size"
    }
   ]
  },
  {
   "title": "Alive connections",
   "type": "stat",
   "description": "Number of alive connections.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (kafka_cluster) (\n  num_alive_connections{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)\nor\nmax by (kafka_cluster) (\n  zookeeper_numaliveconnections{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Alive connections"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "timeseries",
   "description": "Outstanding requests to ZooKeeper cluster.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (kafka_cluster) (\n  outstanding_requests{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)\nor\nsum by (kafka_cluster) (\n  zookeeper_outstandingrequests{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Outstanding requests"
    }
   ]
  },
  {
   "title": "znodes count",
   "type": "stat",
   "description": "Number of znodes.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (kafka_cluster) (\n  znode_count{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)\nor\nmax by (kafka_cluster) (\n  zookeeper_inmemorydatatree_nodecount{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: znodes count"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "stat",
   "description": "Number of watchers.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (kafka_cluster) (\n  watch_count{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)\nor\nmax by (kafka_cluster) (\n  zookeeper_inmemorydatatree_watchcount{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Watchers"
    }
   ]
  },
  {
   "title": "Current zookeeper role",
   "type": "status-history",
   "description": "0 - zookeeper, 1 - zookeeper(leader).\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamp_max(leader_uptime{kafka_cluster=~\"$kafka_cluster\"}, 1) or clamp_max(num_alive_connections{kafka_cluster=~\"$kafka_cluster\"}, 0)\nor\nclamp_max(zookeeper_leaderuptime{kafka_cluster=~\"$kafka_cluster\"}, 1) or clamp_max(zookeeper_numaliveconnections{kafka_cluster=~\"$kafka_cluster\"}, 0)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 19 } },
  {
   "title": "Latency(min)",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min_latency{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\nor\nzookeeper_minrequestlatency{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n  * ignoring (minrequestlatency,ticktime)\nzookeeper_ticktime{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}: Latency(min)"
    }
   ]
  },
  {
   "title": "Latency(avg)",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_latency{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\nor\nzookeeper_avgrequestlatency{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n  * ignoring (avgrequestlatency,ticktime)\nzookeeper_ticktime{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}: Latency(avg)"
    }
   ]
  },
  {
   "title": "Latency(max)",
   "type": "timeseries",
   "description": "Amount of time it takes for the server to respond to a client request.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_latency{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\nor\nzookeeper_maxrequestlatency{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n  * ignoring (maxrequestlatency,ticktime)\nzookeeper_ticktime{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n",
     "legendFormat": "{{instance}}: Latency(max)"
    }
   ]
  },
  {
   "title": "JVM overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used(heap)",
     "type": "stat",
     "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"heap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n))/(avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"heap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n))) * 100",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(heap)"
      }
     ]
    },
    {
     "title": "Memory used(nonheap)",
     "type": "stat",
     "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"nonheap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n))/(avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"nonheap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n))) * 100",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(nonheap)"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "description": "The current number of live threads including both daemon and non-daemon threads.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_threads_current{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "stat",
     "description": "The number of classes that are currently loaded in the JVM.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_classes_loaded{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Classes loaded"
      }
     ]
    }
   ]
  },
  {
   "title": "Process overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Process uptime.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "targets": [
      {
       "expr": "time()-process_start_time_seconds{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: Uptime"
      }
     ]
    },
    {
     "title": "Process start time",
     "type": "stat",
     "description": "Process start time.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster,instance) (\n  process_start_time_seconds{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} * 1000\n)",
       "legendFormat": "{{instance}}: Process start time"
      }
     ]
    },
    {
     "type": "text",
     "description": "Load average: Signal not found.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } }
    },
    {
     "title": "CPU usage (process)",
     "type": "timeseries",
     "description": "Process CPU usage.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster,instance) (\n  rate(process_cpu_seconds_total{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval]) * 100\n)",
       "legendFormat": "{{instance}}: CPU usage (process)"
      }
     ]
    },
    {
     "title": "Process memory used (rss)",
     "type": "timeseries",
     "description": "Process resident memory size in bytes.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster,instance) (\n  process_resident_memory_bytes{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{instance}}: Process memory used (rss)"
      }
     ]
    },
    {
     "title": "Process files open",
     "type": "timeseries",
     "description": "Process files open (avg): Process files opened.  \n\nProcess files max (avg): Process files opened limit.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "targets": [
      {
       "expr": "avg by (kafka_cluster,instance) (\n  process_open_fds{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{instance}}: Process files open"
      },
      {
       "expr": "avg by (kafka_cluster,instance) (\n  process_max_fds{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{instance}}: Process files max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM memory used(heap)",
     "type": "timeseries",
     "description": "JVM memory used(heap) (avg): The used space is the amount of memory that is currently occupied by Java objects.  \n\nJVM memory max(heap) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nJVM memory committed(heap) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"heap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(heap)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"heap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory max(heap)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_committed{area=\"heap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory committed(heap)"
      }
     ]
    },
    {
     "title": "JVM memory used(nonheap)",
     "type": "timeseries",
     "description": "JVM memory used(nonheap) (avg): The amount of memory that is currently in non-heap.  \n\nJVM memory max(nonheap) (avg): Measure of memory max possible (non-heap). Returns -1 if the maximum memory size is undefined.  \n\nJVM memory committed(nonheap) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine(non-heap).\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"nonheap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(nonheap)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"nonheap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory max(nonheap)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_committed{area=\"nonheap\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory committed(nonheap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space (used)",
     "type": "timeseries",
     "description": "Eden Space (used) (avg): Memory used for G1 Eden Space Collection.  \n\nEden Space (max) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nEden Space (committed) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_used{pool=~\"(G1 |PS )?Eden Space\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Eden Space (used)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_max{pool=~\"(G1 |PS )?Eden Space\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Eden Space (max)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_committed{pool=~\"(G1 |PS )?Eden Space\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Eden Space (committed)"
      }
     ]
    },
    {
     "title": "Survival space (used)",
     "type": "timeseries",
     "description": "Survival space (used) (avg): Memory used for Survival collection.  \n\nSurvival space (max) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nSurvival space (committed) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_used{pool=~\"(G1 |PS )?Survivor Space\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Survival space (used)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_max{pool=~\"(G1 |PS )?Survivor Space\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1\n)",
       "legendFormat": "{{kafka_cluster}}: Survival space (max)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_committed{pool=~\"(G1 |PS )?Survivor Space\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Survival space (committed)"
      }
     ]
    },
    {
     "title": "Tenured space (used)",
     "type": "timeseries",
     "description": "Tenured space (used) (avg): Memory used for Tenured(Old Gen) collection.  \n\nTenured space (max) (avg): The max heap size is the size specified via the -Xmx flag.\nReturns -1 if the maximum memory size is undefined.\n\nThis amount of memory is not guaranteed to be available for memory management\nif it is greater than the amount of committed memory.\nThe Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.\n\nSee also: https://docs.oracle.com/javase/10/docs/api/java/lang/management/MemoryUsage.html\n  \n\nTenured space (committed) (avg): The committed size is the amount of memory guaranteed to be available for use by the Java virtual machine.\n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_used{pool=\"G1 Old Gen\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Tenured space (used)"
      },
      {
       "expr": "\n  avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_max{pool=\"G1 Old Gen\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)\n != -1",
       "legendFormat": "{{kafka_cluster}}: Tenured space (max)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_memory_pool_bytes_committed{pool=\"G1 Old Gen\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Tenured space (committed)"
      }
     ]
    },
    {
     "title": "Garbage collections",
     "type": "timeseries",
     "description": "Major and minor garbage collections",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster,gc) (\n  rate(jvm_gc_collection_seconds_count{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{kafka_cluster}}"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "timeseries",
     "description": "GC time (avg) (avg): Garbage collection time (max).  \n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster, gc) (\n  rate(jvm_gc_collection_seconds_sum{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n  /\n  rate(jvm_gc_collection_seconds_count{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)\n",
       "legendFormat": "{{kafka_cluster}}: {{ gc }} (avg)"
      }
     ]
    },
    {
     "title": "Allocated/promoted",
     "type": "timeseries",
     "description": "Allocated (bytes) (avg): Memory allocated to Eden Space.  \n",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  rate(jvm_memory_pool_allocated_bytes_total{pool=~\"(G1 |PS )?Eden Space\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{kafka_cluster}}: Allocated (bytes)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Threads (avg): The current number of live threads including both daemon and non-daemon threads.  \n\nThreads (daemon) (avg): Daemon thread count of a JVM.  \n\nThreads (peak) (avg): Peak thread count of a JVM.  \n\nThreads (deadlocked) (avg): Cycles of JVM-threads that are in deadlock waiting to acquire object monitors or ownable synchronizers.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_threads_current{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_threads_daemon{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads (daemon)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_threads_peak{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads (peak)"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_threads_deadlocked{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads (deadlocked)"
      }
     ]
    },
    {
     "title": "Threads states",
     "type": "timeseries",
     "description": "Threads by current state.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state, kafka_cluster) (jvm_threads_state{kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})",
       "legendFormat": "{{ state }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct buffer used bytes",
     "type": "timeseries",
     "description": "Direct buffer used bytes (avg): Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.  \n\nDirect buffer capacity (avg): Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_buffer_pool_used_bytes{pool=\"direct\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Direct buffer used bytes"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_buffer_pool_capacity_bytes{pool=\"direct\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Direct buffer capacity"
      }
     ]
    },
    {
     "title": "Mapped buffer used",
     "type": "timeseries",
     "description": "Mapped buffer used (avg): The mapped buffer pool is used for its FileChannel instances.  \n\nMapped buffer capacity (avg): The mapped buffer pool is used for its FileChannel instances.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_buffer_pool_used_bytes{pool=\"mapped\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Mapped buffer used"
      },
      {
       "expr": "avg by (kafka_cluster) (\n  jvm_buffer_pool_capacity_bytes{pool=\"mapped\", kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Mapped buffer capacity"
      }
     ]
    }
   ]
  }
 ]
}