{
 "title": "Velero Copy",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "schedule", "label": "schedule", "query": { "query": "label_values(schedule)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# ![veleroimage](https://velero.io/img/Velero.svg)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Backups",
   "type": "stat",
   "description": "Current number of existent backups",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Total Successful Backups",
   "type": "stat",
   "description": "Total number of Successful Backups",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Total backup Items",
   "type": "stat",
   "description": "Total backup Items in Velero",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_items_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Total Restores",
   "type": "stat",
   "description": "Total number of Restores",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_restore_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Total Succesful Restores",
   "type": "stat",
   "description": "Total number of Succesful Restores",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Total Backup Deletion Attempts",
   "type": "stat",
   "description": "Total number of Backup Deletion Attempts",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "velero_backup_deletion_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Current Status of Velero",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups Overview",
   "type": "timeseries",
   "description": "Overview of Velero Backup attempts including success and failure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(velero_backup_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Attempts"
    },
    {
     "expr": "increase(velero_backup_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(velero_backup_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Restore Overview",
   "type": "timeseries",
   "description": "Overview of Velero restore attempts including success and failure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(velero_restore_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Attempts"
    },
    {
     "expr": "increase(velero_restore_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(velero_restore_failed_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Backup Deletion Overview",
   "type": "timeseries",
   "description": "Overview of Velero Backup Deletion attempts including success and failure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(velero_backup_deletion_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Attemps"
    },
    {
     "expr": "increase(velero_backup_deletion_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(velero_backup_deletion_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Volume Snapshots overview",
   "type": "timeseries",
   "description": "Overview of Volume snapshot attempts including success and failure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(velero_volume_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Attempts"
    },
    {
     "expr": "increase(velero_volume_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(velero_volume_snapshot_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "CSI Snapshots overview",
   "type": "timeseries",
   "description": "Overview of CSI snapshot attempts including success and failure",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(velero_csi_snapshot_attempt_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Attempts"
    },
    {
     "expr": "increase(velero_csi_snapshot_success_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(velero_csi_snapshot_failure_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[$__rate_interval])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Backup Last status",
   "type": "timeseries",
   "description": "Last status of the backup. A value of 1 is success, 0 is failure",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "velero_backup_last_status{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "timeseries",
   "description": "Time taken to complete backup, in seconds",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backup_duration_seconds{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "timeseries",
   "description": "Size in bytes of a backup",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(velero_backup_tarball_size_bytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",schedule=~\"$schedule\"}[15m])",
     "legendFormat": "{{schedule}}"
    }
   ]
  }
 ]
}