groups:
    - name: squid-alerts
      rules:
        - alert: SquidHighHTTPServerRequestErrors
          annotations:
            description: |
                The percentage of HTTP server request errors is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} which is above the threshold of 5.
            summary: There are a high number of HTTP server errors.
          expr: |
            rate(squid_server_http_errors_total[5m]) / clamp_min(rate(squid_server_http_requests_total[5m]),1) * 100 > 5
          for: 5m
          labels:
            severity: critical
        - alert: SquidHighFTPServerRequestErrors
          annotations:
            description: |
                The percentage of FTP server request errors is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} which is above the threshold of 5.
            summary: There are a high number of FTP server request errors.
          expr: |
            rate(squid_server_ftp_errors_total[5m]) / clamp_min(rate(squid_server_ftp_requests_total[5m]),1) * 100 > 5
          for: 5m
          labels:
            severity: critical
        - alert: SquidHighOtherServerRequestErrors
          annotations:
            description: |
                The percentage of other server request errors is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} which is above the threshold of 5.
            summary: There are a high number of other server request errors.
          expr: |
            rate(squid_server_other_errors_total[5m]) / clamp_min(rate(squid_server_other_requests_total[5m]),1) * 100 > 5
          for: 5m
          labels:
            severity: critical
        - alert: SquidHighClientRequestErrors
          annotations:
            description: |
                The percentage of HTTP client request errors is {{ printf "%.0f" $value }} over the last 5m on {{ $labels.instance }} which is above the threshold of 5.
            summary: There are a high number of HTTP client request errors.
          expr: |
            rate(squid_client_http_errors_total[5m]) / clamp_min(rate(squid_client_http_requests_total[5m]),1) * 100 > 5
          for: 5m
          labels:
            severity: critical
        - alert: SquidLowCacheHitRatio
          annotations:
            description: |
                The cache hit ratio is {{ printf "%.0f" $value }} over the last 10m on {{ $labels.instance }} which is below the threshold of 85.
            summary: The cache hit ratio has fallen below the configured threshold (%).
          expr: |
            rate(squid_client_http_hits_total[10m]) / clamp_min(rate(squid_client_http_requests_total[10m]),1) * 100 < 85
          for: 10m
          labels:
            severity: warning
