{
 "title": "Jira",
 "description": "Shows Jira server and usage metrics",
 "tags": [
  "prometheus",
  "Atlassian"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jira_total_issues_gauge, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jira_total_issues_gauge {job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Status",
   "type": "stat",
   "description": "If the server is up and responding",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Countdown Until License Expiry",
   "type": "stat",
   "description": "The amount of time until the JIRA license expires",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_license_expiry_days_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Percentage of Available User Accounts",
   "type": "stat",
   "description": "The percentage of user accounts that are still available for new accounts.",
   "gridPos": { "h": 5, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (jira_all_users_gauge{job=\"$job\", instance=\"$instance\"}/jira_allowed_users_gauge{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  { "title": "Server Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jira_request_duration_on_path_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval])/rate(jira_request_duration_on_path_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "description": "The total amount of memory used by the JIRA server.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds over time.",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  { "title": "JIRA Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total Projects",
   "type": "stat",
   "description": "Total Projects in JIRA",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_projects_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Groups",
   "type": "stat",
   "description": "The total number of groups in JIRA",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_groups_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "Total number of users in JIRA",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_active_users_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "stat",
   "description": "Total number of current sessions in JIRA",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_sessions_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "stat",
   "description": "The total issues in JIRA",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_issues_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Attachments",
   "type": "stat",
   "description": "The total number of attachments within the JIRA instance",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_attachments_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Attachment Size",
   "type": "stat",
   "description": "Displays the total size of attachments used in the JIRA instance.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jira_total_attachment_size_gauge{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}