groups:
    - name: ArgoCD
      rules:
        - alert: ArgoAppOutOfSync
          annotations:
            description: Application {{ $labels.name }} has sync status as {{ $labels.sync_status }}.
            summary: Application is OutOfSync.
          expr: argocd_app_info{sync_status="OutOfSync"} == 1
          for: 1m
          labels:
            severity: warning
        - alert: ArgoAppSyncFailed
          annotations:
            description: Application {{ $labels.name }} has sync phase as {{ $labels.phase }}.
            summary: Application Sync Failed.
          expr: argocd_app_sync_total{phase!="Succeeded"} == 1
          for: 1m
          labels:
            severity: warning
        - alert: ArgoAppMissing
          annotations:
            description: "ArgoCD has not reported any applications data for the past 15 minutes which means that it must be down or not functioning properly.  \n"
            summary: No reported applications in ArgoCD.
          expr: absent(argocd_app_info)
          for: 15m
          labels:
            severity: critical
