{
 "title": "Catchpoint web performance by node",
 "tags": [ "catchpoint" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(catchpoint_any_error{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(catchpoint_any_error{job=~\"$job\"}, instance)"
   },
   {
    "name": "node_name",
    "label": "Node_name",
    "query": "label_values(catchpoint_any_error{job=~\"$job\",instance=~\"$instance\"}, node_name)"
   },
   {
    "name": "test_name",
    "label": "Test_name",
    "query": "label_values(catchpoint_any_error{}, test_name)"
   }
  ]
 },
 "panels": [
  { "title": "Errors and content types", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "bargauge",
   "description": "Indicates various errors that are occuring.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  catchpoint_error_objects_loaded{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "object loaded"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_dns_error{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "DNS"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_load_error{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "load"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_timeout_error{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "timeout"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_connection_error{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "connection"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_transaction_error{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "transaction"
    }
   ]
  },
  {
   "title": "Content types loaded by size",
   "type": "piechart",
   "description": "Size of content loaded.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  catchpoint_image_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "image"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_html_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "html"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_css_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "css"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_script_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "script"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_font_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "font"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_xml_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "xml"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_media_content_type{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "media"
    }
   ]
  },
  {
   "title": "Content loaded by type",
   "type": "bargauge",
   "description": "Number of elements loaded.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  catchpoint_image_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "image"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_html_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "html"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_css_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "css"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_script_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "script"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_font_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "font"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_xml_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "xml"
    },
    {
     "expr": "sum by (node_name) (\n  catchpoint_media_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "media"
    }
   ]
  },
  { "title": "Content handling and loading", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "Page completion time",
   "type": "timeseries",
   "description": "Time taken for the browser to fully render the page after all resources are downloaded.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_document_complete_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - completion"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_total_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - load"
    }
   ]
  },
  {
   "title": "Client processing",
   "type": "timeseries",
   "description": "Client processing time, which reflects the time spent on client-side processing, including script execution and rendering.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_client_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Connection and DNS resolution",
   "type": "timeseries",
   "description": "Time taken to establish an SSL handshake, DNS resolution, and connect.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_dns_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - DNS"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_ssl_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - SSL"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_connect_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - connect"
    }
   ]
  },
  {
   "title": "Content handling",
   "type": "timeseries",
   "description": "Time taken to load and render content on the webpage.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_content_load_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - load"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_render_start_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - render"
    }
   ]
  },
  {
   "title": "Additional delays",
   "type": "timeseries",
   "description": "Additional delays encountered due to redirects, as well as time from successful connection to receiving the first byte.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_redirect_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - redirect"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_wait_time{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - wait"
    }
   ]
  },
  { "title": "Response", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 32 } },
  {
   "title": "Response content size",
   "type": "timeseries",
   "description": "Size of the HTTP response content.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_response_content_size{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - content"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_response_header_size{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - header"
    }
   ]
  },
  {
   "title": "Total content size",
   "type": "timeseries",
   "description": "Total size of the HTTP response content and headers.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_total_content_size{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - content"
    },
    {
     "expr": "sum by (test_name) (\n  catchpoint_total_header_size{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}} - header"
    }
   ]
  },
  { "title": "Network activity", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 39 } },
  {
   "title": "Network connections",
   "type": "timeseries",
   "description": "Number of connections made.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_connections_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Hosts contacted",
   "type": "timeseries",
   "description": "Number of hosts contacted.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hosts" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_hosts_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Cache access",
   "type": "timeseries",
   "description": "Number of cached elements accessed.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_cached_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 46 } },
  {
   "title": "Requests success ratio",
   "type": "timeseries",
   "description": "Success ratio of requests made.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by (test_name) (catchpoint_requests_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}) - avg by (test_name) (catchpoint_failed_requests_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"})) / avg by (test_name) (catchpoint_requests_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "timeseries",
   "description": "Number of HTTP redirections encountered.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (test_name) (\n  catchpoint_redirections_count{test_name=~\"$test_name\",node_name=~\"$node_name\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  }
 ]
}