{
 "title": "Catchpoint overview",
 "tags": [ "catchpoint" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(catchpoint_any_error{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(catchpoint_any_error{job=~\"$job\"}, instance)"
   },
   {
    "name": "test_name",
    "label": "Test_name",
    "query": "label_values(catchpoint_any_error{job=~\"$job\",instance=~\"$instance\"}, test_name)"
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Top errors by tests",
   "type": "timeseries",
   "description": "The top number of errors encountered among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(1, \n  sum by (test_name) (\n  sum_over_time(catchpoint_any_error{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  { "title": "Catchpoint alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 } },
  { "title": "Content handling and loading", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "Top average total load time by tests",
   "type": "timeseries",
   "description": "The top average total load time among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (test_name) (\n  avg_over_time(catchpoint_load_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Top average total load time by nodes",
   "type": "timeseries",
   "description": "The top average total load time among all nodes over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (node_name) (\n  avg_over_time(catchpoint_load_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top average document completion time by tests",
   "type": "timeseries",
   "description": "The top average document completion time among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (test_name) (\n  avg_over_time(catchpoint_document_complete_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Top average document completion time by nodes",
   "type": "timeseries",
   "description": "The top average document completion time among all nodes over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (node_name) (\n  avg_over_time(catchpoint_document_complete_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 20 } },
  {
   "title": "Bottom average success request ratio by tests",
   "type": "timeseries",
   "description": "The lowest average success request ratio among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(1, \n  avg by (test_name) (\n  avg_over_time(((catchpoint_requests_count{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"} - catchpoint_failed_requests_count{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}) / clamp_min(catchpoint_requests_count{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"},1))[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Bottom average success request ratio by nodes",
   "type": "timeseries",
   "description": "The lowest average success request ratio among all nodes over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(1, \n  avg by (node_name) (\n  avg_over_time(((catchpoint_requests_count{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"} - catchpoint_failed_requests_count{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}) / clamp_min(catchpoint_requests_count{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"},1))[$__interval:])\n)\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Top average connection setup time by tests",
   "type": "timeseries",
   "description": "The top average connection setup time among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (test_name) (\n  avg_over_time(catchpoint_connect_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Top average connection setup time by nodes",
   "type": "timeseries",
   "description": "The top average connection setup time among all nodes over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (node_name) (\n  avg_over_time(catchpoint_connect_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top average content loading time by tests",
   "type": "timeseries",
   "description": "The top average content loading time among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (test_name) (\n  avg_over_time(catchpoint_content_load_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Top average content loading time by nodes",
   "type": "timeseries",
   "description": "The top average content loading time among all nodes over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (node_name) (\n  avg_over_time(catchpoint_content_load_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Top average redirect time by tests",
   "type": "timeseries",
   "description": "The top average time spent following redirects among all tests over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (test_name) (\n  avg_over_time(catchpoint_redirect_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{test_name}}"
    }
   ]
  },
  {
   "title": "Top average redirect time by nodes",
   "type": "timeseries",
   "description": "The top average time spent following redirects among all nodes over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(1, \n  avg by (node_name) (\n  avg_over_time(catchpoint_redirect_time{test_name=~\"$test_name\",job=~\"$job\",instance=~\"$instance\"}[$__interval:])\n)\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}