{
 "title": "Presto overview",
 "tags": [ "presto-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\"}, cluster)"
   },
   {
    "name": "presto_cluster",
    "label": "Presto cluster",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\"}, presto_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Active resource managers",
   "type": "stat",
   "description": "Active resource managers",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (presto_cluster) (presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "Resource manager"
    }
   ]
  },
  {
   "title": "Active coordinators",
   "type": "stat",
   "description": "Active coordinators",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (presto_cluster) (presto_metadata_DiscoveryNodeManager_ActiveCoordinatorCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "Coordinator"
    }
   ]
  },
  {
   "title": "Active workers",
   "type": "stat",
   "description": "Active workers",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (presto_cluster) (presto_metadata_DiscoveryNodeManager_ActiveNodeCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Inactive workers",
   "type": "stat",
   "description": "Inactive workers",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (presto_cluster) (presto_metadata_DiscoveryNodeManager_InactiveNodeCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{presto_cluster}} - inactive"
    }
   ]
  },
  {
   "title": "Completed queries - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_QueryManager_CompletedQueries_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{presto_cluster}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 } },
  {
   "title": "User error failures - one minute rate",
   "type": "timeseries",
   "description": "The rate of user error failures occurring across clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "presto_QueryManager_UserErrorFailures_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{presto_cluster}}"
    }
   ]
  },
  {
   "title": "Queued queries",
   "type": "timeseries",
   "description": "The number of queued queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_QueryManager_QueuedQueries{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{presto_cluster}}"
    }
   ]
  },
  {
   "title": "Blocked nodes",
   "type": "timeseries",
   "description": "The number of nodes that are blocked due to memory restrictions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_ClusterMemoryPool_general_BlockedNodes{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{presto_cluster}}"
    }
   ]
  },
  {
   "title": "Internal error failures - one minute rate",
   "type": "timeseries",
   "description": "The rate of internal error failures occurring across clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "presto_QueryManager_InternalFailures_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{presto_cluster}}"
    }
   ]
  },
  {
   "title": "Cluster memory distributed bytes",
   "type": "timeseries",
   "description": "The amount of memory available across the clusters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (presto_cluster) (presto_ClusterMemoryPool_reserved_FreeDistributedBytes{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{presto_cluster}} - reserved"
    },
    {
     "expr": "sum by (presto_cluster) (presto_ClusterMemoryPool_general_FreeDistributedBytes{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{presto_cluster}} - general"
    }
   ]
  },
  {
   "title": "Insufficient resource failures - one minute rate",
   "type": "timeseries",
   "description": "The rate that failures are occurring due to insufficient resources.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "presto_QueryManager_InsufficientResourcesFailures_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{presto_cluster}}"
    }
   ]
  },
  {
   "title": "Data processing throughput - one minute rate",
   "type": "timeseries",
   "description": "The rate at which volumes of data are being processed.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (presto_cluster) (presto_TaskManager_InputDataSize_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{presto_cluster}} - input"
    },
    {
     "expr": "sum by (presto_cluster) (presto_TaskManager_OutputDataSize_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{presto_cluster}} - output"
    }
   ]
  }
 ]
}