{
 "title": "Ruby Rack application overview",
 "description": "Http metrics for Rack applications",
 "tags": [ "ruby-rack-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_requests_total, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_total, instance)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(http_server_requests_total, path)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_server_requests_total, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Http requests throughput by path.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "description": "Http requests duration percentiles and average.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99, \n  sum (\n    rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])\n  ) by (le) \n) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.5, \n  sum (\n    rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])\n  ) by (le) \n) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])) * 1e3 \n/\nsum(rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Http requests error rate (5xx) by path.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path) (\n  rate(http_server_requests_total{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", path=~\"$path\", code=~\"5.+\"}[$__rate_interval])\n)\n/\nsum by(path) (\n  rate(http_server_requests_total{job=~\"$job\", instance=~\"$instance\", method=~\"$method\", path=~\"$path\"}[$__rate_interval])\n)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}