{
 "title": "Apache Cassandra overview",
 "tags": [ "cassandra-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cassandra_cache_hitrate{}, job)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cassandra cluster",
    "query": "label_values(cassandra_cache_hitrate{job=~\"$job\"}, cassandra_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cassandra_cache_hitrate{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Number of clusters",
   "type": "stat",
   "description": "The number of unique jobs being reported.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (cassandra_cluster) (cassandra_up_endpoint_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "description": "Number of down nodes in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count by (job,cassandra_cluster,instance) (cassandra_up_endpoint_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Number of down nodes",
   "type": "stat",
   "description": "Number of down nodes in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max by (job,cassandra_cluster,instance) (cassandra_down_endpoint_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "stat",
   "description": "The total number of bytes being used by Apache Cassandra for storage.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cassandra_storage_load_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (cassandra_cluster)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "The number of local writes aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cassandra_cluster) (increase(cassandra_keyspace_writelatency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "The number of local reads aggregated across all nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cassandra_cluster) (increase(cassandra_keyspace_readlatency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write average latency",
   "type": "timeseries",
   "description": "Average write latency for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds_average{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read average latency",
   "type": "timeseries",
   "description": "Average read latency for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds_average{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write latency heatmap",
   "type": "heatmap",
   "description": "Local write latency heatmap for this cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"} >= 0) by (quantile)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read latency heatmap",
   "type": "heatmap",
   "description": "Local read latency heatmap for this cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"} >= 0) by (quantile)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write latency quartiles",
   "type": "timeseries",
   "description": "Local write latency quartiles for this cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p99"
    }
   ]
  },
  {
   "title": "Read latency quartiles",
   "type": "timeseries",
   "description": "Local read latency quartiles for this cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p99"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "timeseries",
   "description": "The number of timeouts experienced from each node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_connection_timeouts_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}[$__interval:])) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{ cassandra_cluster }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Average key cache hit ratio",
   "type": "timeseries",
   "description": "The average key cache hit ratio being reported.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cassandra_cache_hitrate{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", cache=\"KeyCache\"} * 100) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "description": "The number of tasks that a connection has either completed, dropped, or is pending.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cassandra_connection_largemessagedroppedtasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{instance }} - large dropped"
    },
    {
     "expr": "sum(cassandra_connection_largemessageactivetasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{instance }} - large active"
    },
    {
     "expr": "sum(cassandra_connection_largemessagependingtasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{instance }} - large pending"
    },
    {
     "expr": "sum(cassandra_connection_smallmessagedroppedtasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{instance }} - small dropped"
    },
    {
     "expr": "sum(cassandra_connection_smallmessageactivetasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{instance }} - small active"
    },
    {
     "expr": "sum(cassandra_connection_smallmessagependingtasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{instance }} - small pending"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The number of bytes used by each node of the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cassandra_storage_load_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (job,cassandra_cluster,instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Client requests", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 57 } },
  {
   "title": "Write requests",
   "type": "timeseries",
   "description": "Rate of standard client write requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_latency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", clientrequest=\"Write\"}[$__rate_interval])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write requests timed out",
   "type": "timeseries",
   "description": "Standard client write requests returning timed out exceptions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", clientrequest=\"Write\"}[$__rate_interval])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write requests unavailable",
   "type": "timeseries",
   "description": "Standard client write requests returning unavailable exceptions.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_unavailables_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", clientrequest=\"Write\"}[$__rate_interval])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read requests",
   "type": "timeseries",
   "description": "Rate of standard client read requests.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_latency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", clientrequest=\"Read\"}[$__rate_interval])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read requests timed out",
   "type": "timeseries",
   "description": "Standard client read requests returning timed out exceptions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", clientrequest=\"Read\"}[$__rate_interval])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read requests unavailable",
   "type": "timeseries",
   "description": "Standard client read requests returning unavailable exceptions.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_unavailables_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", clientrequest=\"Read\"}[$__rate_interval])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  }
 ]
}