{
 "title": "Apache Cassandra overview",
 "tags": [ "apache-cassandra-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cassandra_up_endpoint_count, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cassandra_up_endpoint_count{job=~\"$job\"}, cluster)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cassandra cluster",
    "query": "label_values(cassandra_up_endpoint_count{job=~\"$job\"}, cassandra_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of clusters",
   "type": "stat",
   "description": "The number of unique jobs being reported",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cassandra_cluster) (cassandra_up_endpoint_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "description": "The sum of unique instances being reported.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_up_endpoint_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"})",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Number of down nodes",
   "type": "stat",
   "description": "Number of down nodes in the cluster",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cassandra_down_endpoint_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"})",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "timeseries",
   "description": "The number of timeouts experienced from each node",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(cassandra_connection_timeouts_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}[$__interval:])) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Average key cache hit ratio",
   "type": "timeseries",
   "description": "The number of medium tasks that a connection has either completed, dropped, or is pending",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cassandra_cache_hitrate{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", cache=\"KeyCache\",} * 100) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} "
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "description": "The number of tasks that a connection has either completed, dropped, or is pending",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(cassandra_connection_largemessagedroppedtasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }} - large dropped"
    },
    {
     "expr": "sum(cassandra_connection_largemessageactivetasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }} - large active"
    },
    {
     "expr": "sum(cassandra_connection_largemessagependingtasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }} - large pending"
    },
    {
     "expr": "sum(cassandra_connection_smallmessagedroppedtasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }} - small dropped"
    },
    {
     "expr": "sum(cassandra_connection_smallmessageactivetasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }} - small active"
    },
    {
     "expr": "sum(cassandra_connection_smallmessagependingtasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }} - small pending"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "stat",
   "description": "The total number of bytes being used by Apache Cassandra for storage.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cassandra_storage_load_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster)",
     "legendFormat": "{{cassandra_cluster}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The number of bytes used by each node of the cluster",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cassandra_storage_load_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (cassandra_cluster, instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "The number of local writes aggregated across all nodes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase((sum by (cassandra_cluster) (cassandra_keyspace_writelatency_seconds_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"})[$__interval:]))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "The number of local writes aggregated across all nodes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase((sum by (cassandra_cluster) (cassandra_keyspace_readlatency_seconds_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"})[$__interval:]))",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write average latency",
   "type": "timeseries",
   "description": "Average write latency for the cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds_average{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read average latency",
   "type": "timeseries",
   "description": "Average read latency for the cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds_average{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write latency heatmap",
   "type": "heatmap",
   "description": "Local write latency heatmap for this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (quantile)"
    }
   ]
  },
  {
   "title": "Read latency heatmap",
   "type": "heatmap",
   "description": "Local read latency heatmap for this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}) by (quantile)"
    }
   ]
  },
  {
   "title": "Write latency quartiles",
   "type": "timeseries",
   "description": "Local write latency quartiles for this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.95\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.99\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p99"
    }
   ]
  },
  {
   "title": "Read latency quartiles",
   "type": "timeseries",
   "description": "Local read latency quartiles for this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.95\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.99\"} >= 0) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }} - p99"
    }
   ]
  },
  {
   "title": "Client requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    { "legendFormat": "{{ cassandra_cluster }}" }
   ]
  },
  {
   "title": "Write requests",
   "type": "timeseries",
   "description": "Rate of standard client write requests.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_clientrequest_latency_seconds_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", clientrequest=\"Write\"}[$__interval:])) by (cassandra_cluster)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Write requests timed out",
   "type": "timeseries",
   "description": "Standard client write requests returning timed out exceptions.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_clientrequest_timeouts_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", clientrequest=\"Write\"}[$__interval:])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Write requests unavailable",
   "type": "timeseries",
   "description": "Standard client write requests returning timed out exceptions.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_clientrequest_unavailables_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", clientrequest=\"Write\"}[$__interval:])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read requests",
   "type": "timeseries",
   "description": "Rate of standard client read requests.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_clientrequest_latency_seconds_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", clientrequest=\"Read\"}[$__interval:])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read requests timed out",
   "type": "timeseries",
   "description": "Standard client read requests returning timed out exceptions.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_clientrequest_timeouts_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", clientrequest=\"Read\"}[$__interval:])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  },
  {
   "title": "Read requests unavailable",
   "type": "timeseries",
   "description": "Standard client write requests returning timed out exceptions.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(increase(cassandra_clientrequest_unavailables_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", clientrequest=\"Read\"}[$__interval:])) by (cassandra_cluster)",
     "legendFormat": "{{ cassandra_cluster }}"
    }
   ]
  }
 ]
}