{
 "title": "Apache Cassandra keyspaces",
 "tags": [ "apache-cassandra-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cassandra_up_endpoint_count, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cassandra_up_endpoint_count{job=~\"$job\"}, cluster)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cassandra cluster",
    "query": "label_values(cassandra_up_endpoint_count{job=~\"$job\"}, cassandra_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cassandra_up_endpoint_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}, instance)"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": "label_values(cassandra_keyspace_caspreparelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}, keyspace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Keyspaces count",
   "type": "stat",
   "description": "The total count of the amount of keyspaces being reported.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (keyspace) (cassandra_keyspace_writelatency_seconds{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}))"
    }
   ]
  },
  {
   "title": "Keyspace total disk space used",
   "type": "timeseries",
   "description": "Total amount of disk space used by keyspaces.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_totaldiskspaceused{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Keyspace pending compactions",
   "type": "timeseries",
   "description": "The number of compaction operations a keyspace is pending to perform.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_pendingcompactions{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Keyspace max partition size",
   "type": "timeseries",
   "description": "Max partition size for keyspaces.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(cassandra_table_maxpartitionsize{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}) by (keyspace)",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "The number of writes performed on the keyspace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_writelatency_seconds_count{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}) by (keyspace)[$__interval:])",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "The number of reads performed on the keyspace.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_readlatency_seconds_count{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}) by (keyspace)[$__interval:])",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Repair jobs started",
   "type": "timeseries",
   "description": "The number of repair jobs started per keyspace.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_repairjobsstarted_count{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"} >= 0) by (keyspace)[$__interval:])",
     "legendFormat": "{{keyspace}} "
    }
   ]
  },
  {
   "title": "Repair jobs completed",
   "type": "timeseries",
   "description": "The number of repair jobs that were completed.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_repairjobscompleted_count{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\"}) by (keyspace)[$__interval:])",
     "legendFormat": "{{keyspace}} "
    }
   ]
  },
  {
   "title": "Keyspace write latency",
   "type": "timeseries",
   "description": "The 95th and 99th percentils of local write latency for keyspaces",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.95\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.99\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p99"
    }
   ]
  },
  {
   "title": "Keyspace read latency",
   "type": "timeseries",
   "description": "Average local read latency for keyspaces",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.95\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", instance=~\"$instance\", keyspace=~\"$keyspace\", cassandra_cluster=~\"$cassandra_cluster\", quantile=\"0.99\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p99"
    }
   ]
  }
 ]
}