{
 "title": "Istio Service Overview",
 "tags": [ "Integration - Istio" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "source",
    "label": "source",
    "query": {
     "query": "label_values(source_canonical_service)"
    }
   },
   {
    "name": "destination",
    "label": "destination",
    "query": {
     "query": "label_values(destination_canonical_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client Request Volume",
   "type": "stat",
   "description": "Client Request Volume",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{source_canonical_service=~\"$source\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])), 0.001)"
    }
   ]
  },
  {
   "title": "Server Request Volume",
   "type": "stat",
   "description": "Server Request Volume",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_canonical_service=~\"$destination\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])), 0.001)"
    }
   ]
  },
  {
   "title": "TCP Sent Bytes",
   "type": "stat",
   "description": "TCP Sent Bytes",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total{destination_canonical_service=~\"$destination\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg Request Duration",
   "type": "stat",
   "description": "Avg Request Duration",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(istio_request_duration_milliseconds_bucket{source_canonical_service=~\"$source\",job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Requests By Response Code",
   "type": "timeseries",
   "description": "Requests By Response Code",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\", source_canonical_service=~\"$source\", destination_canonical_service=~\"$destination\"}) by  (response_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 destinations by Source",
   "type": "bargauge",
   "description": "Top 10 destinations services by Source",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(destination_canonical_service) (10, sum by(destination_canonical_service) (istio_requests_total{source_canonical_service=~\"$source\", destination_canonical_service=~\"$destination\", cluster=~\"$cluster\", job=~\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "{{destination_canonical_service}}"
    }
   ]
  },
  { "title": "Source Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Request Size by destination",
   "type": "timeseries",
   "description": "Request Size By destination Workload",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(istio_request_bytes_bucket{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$instance\", source_canonical_service=~\"$source\"}) by (destination_canonical_service)",
     "legendFormat": "{{destination_canonical_service}}"
    }
   ]
  },
  {
   "title": "Response Size by destination",
   "type": "timeseries",
   "description": "Response Size By destination Workload",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(istio_response_bytes_bucket{cluster=~\"$cluster\", job=~\"$job\", instance=~\"$instance\", source_canonical_service=~\"$source\"}) by (destination_canonical_service)",
     "legendFormat": "{{destination_canonical_service}}"
    }
   ]
  },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "timeseries",
   "description": "Bytes Received from Incoming TCP Connection",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{destination_canonical_service=~\"$service\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "timeseries",
   "description": "Bytes Sent to Incoming TCP Connection",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{destination_canonical_service=~\"$service\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (source_workload, source_workload_namespace), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace}} (🔐mTLS)"
    }
   ]
  },
  { "title": "Destination Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "timeseries",
   "description": "Bytes Received from Incoming TCP Connection",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{destination_canonical_service=~\"$service\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}} (🔐mTLS)"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "timeseries",
   "description": "Bytes Sent to Incoming TCP Connection",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{destination_canonical_service=~\"$service\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }} (🔐mTLS)"
    }
   ]
  }
 ]
}