{
 "title": "Istio",
 "description": "Istio",
 "tags": [ "Integration - Istio" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "# ![argoimage](https://github.com/cncf/artwork/blob/master/projects/istio/horizontal/color/istio-horizontal-color.png?raw=true)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Services",
   "type": "stat",
   "description": "Virtual Services in Istio system",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"add\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) - (max(pilot_k8s_cfg_events{type=\"VirtualService\", event=\"delete\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) or max(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} * 0))"
    }
   ]
  },
  {
   "title": "Service Entries",
   "type": "stat",
   "description": "Service Entries in Istio system",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"ServiceEntry\", event=\"add\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) - (max(pilot_k8s_cfg_events{type=\"ServiceEntry\", event=\"delete\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) or max(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} * 0))"
    }
   ]
  },
  {
   "title": "Destination Rules",
   "type": "stat",
   "description": "Destination Rules in Istio system",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"add\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) - (max(pilot_k8s_cfg_events{type=\"DestinationRule\", event=\"delete\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) or max(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} * 0))"
    }
   ]
  },
  {
   "title": "Workload Entries",
   "type": "stat",
   "description": "Workload Entries in Istio system",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"WorkloadEntry\", event=\"add\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) - (max(pilot_k8s_cfg_events{type=\"WorkloadEntry\", event=\"delete\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) or max(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} * 0))"
    }
   ]
  },
  {
   "title": "Authorization Policies",
   "type": "stat",
   "description": "Authorization Policies in Istio system",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"AuthorizationPolicy\", event=\"add\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) - (max(pilot_k8s_cfg_events{type=\"AuthorizationPolicy\", event=\"delete\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) or max(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} * 0))"
    }
   ]
  },
  {
   "title": "PeerAuthentication Policies",
   "type": "stat",
   "description": "PeerAuthentication Policies in Istio System",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pilot_k8s_cfg_events{type=\"PeerAuthentication\", event=\"add\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) - (max(pilot_k8s_cfg_events{type=\"PeerAuthentication\", event=\"delete\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) or max(up{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} * 0))"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "gauge",
   "description": "Global Success Rate (non-5xx responses)",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "istio_requests_total{reporter=\"source\", response_code!~\"5.*\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"} / istio_requests_total{reporter=\"source\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "stat",
   "description": "Number of 4xx's requests",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(istio_requests_total{response_code=~\"4.*\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) / sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Global Request Volume",
   "type": "timeseries",
   "description": "Global Request Volume in Istio",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "istio_requests_total{reporter=\"source\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "stat",
   "description": "Number of 5xx's requests",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(istio_requests_total{response_code=~\"5.*\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) / sum(istio_requests_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}))"
    }
   ]
  },
  { "title": "Pilot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Version",
   "type": "table",
   "description": "Pilot Version",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(istio_build{component=\"pilot\", job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  {
   "title": "Pilot Pushes",
   "type": "timeseries",
   "description": "Shows the rate of pilot pushes",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pilot_xds_pushes{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Number of endpoints connected using xDS",
   "type": "stat",
   "description": "Gauge metric that indicates the number of endpoints connected to a pilot using xDS (a group of APIs that make up Discovery Service).",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_xds{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Duplicate subsets",
   "type": "gauge",
   "description": "Duplicate subsets across destination rules for same host",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_destrule_subsets{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Duplicate envoy clusters caused by service entries ",
   "type": "gauge",
   "description": "Duplicate envoy clusters caused by service entries with same hostname",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_duplicate_envoy_clusters{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Updates received by type",
   "type": "barchart",
   "description": "Total number of updates received by pilot.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pilot_inbound_updates{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Services known to pilot",
   "type": "gauge",
   "description": "Total services known to pilot\n",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_services{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Virtual services known to pilot",
   "type": "gauge",
   "description": "Total virtual services known to pilot",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_virt_services{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual services with dup domains",
   "type": "gauge",
   "description": "Virtual services with dup domains",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_vservice_dup_domain{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Delay between config change and a proxy receiving configuration",
   "type": "timeseries",
   "description": "Delay in seconds between config change and a proxy receiving all required configuration",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pilot_proxy_convergence_time_bucket{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Conflicting listeners",
   "type": "status-history",
   "description": "Number of conflicting inbound listeners.\nNumber of conflicting wildcard http listeners with current wildcard tcp listener.\nNumber of conflicting wildcard tcp listeners with current wildcard http listener.\nNumber of conflicting tcp listeners with current tcp listener.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pilot_conflict_inbound_listener{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Inbound Listners"
    },
    {
     "expr": "pilot_conflict_outbound_listener_http_over_current_tcp{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Wildcard http Outbound listeners"
    },
    {
     "expr": "pilot_conflict_outbound_listener_tcp_over_current_tcp{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Wildcard tcp Outbound listeners"
    },
    {
     "expr": "pilot_conflict_outbound_listener_tcp_over_current_http{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "tcp Outbound listeners with current tcp listener"
    }
   ]
  },
  {
   "title": "Events from k8s registry",
   "type": "barchart",
   "description": "Events from k8s registry",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pilot_k8s_reg_events{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{event}} {{type}}"
    }
   ]
  },
  {
   "title": "Events from k8s config",
   "type": "barchart",
   "description": "Events from k8s config",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pilot_k8s_cfg_events{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{type}} {{event}}"
    }
   ]
  },
  {
   "title": "Pods not found in the endpoint table",
   "type": "stat",
   "description": "Pods not found in the endpoint table, possibly invalid.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pilot_no_ip{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total time in seconds Pilot takes to push by type",
   "type": "heatmap",
   "description": "Total time in seconds Pilot takes to push lds, rds, cds and eds",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 47 },
   "targets": [
    {
     "expr": "pilot_xds_push_time_sum{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Sidecar Injections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Total number of sidecar injection requests",
   "type": "timeseries",
   "description": "Total number of sidecar injection requests.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sidecar_injection_requests_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}\n"
    }
   ]
  },
  {
   "title": "Total number of successful sidecar injection requests",
   "type": "timeseries",
   "description": "Total number of successful sidecar injection requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "sidecar_injection_success_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Webhook patching attempts",
   "type": "status-history",
   "description": "Webhook patching attempts by name",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "targets": [
    {
     "expr": "webhook_patch_attempts_total{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Citadel and Galley Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Number of CSRs received by Citadel",
   "type": "stat",
   "description": "The number of CSR received by the Istio Citadel component",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citadel_server_csr_count{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time to Citadel root cert expiry",
   "type": "stat",
   "description": "The unix timestamp, in seconds, when Citadel root cert will expire. A negative time indicates the cert is expired",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citadel_server_root_cert_expiry_timestamp{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of succeeded certificates issuances by Citadel",
   "type": "stat",
   "description": "The number of certificates issued that Citadel has served successfully",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citadel_server_success_cert_issuance_count{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Configuration updates by Galley",
   "type": "timeseries",
   "description": "k8s webhook configuration updates",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 63 },
   "targets": [
    {
     "expr": "galley_validation_config_updates{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "Updates"
    }
   ]
  }
 ]
}