{
 "title": "Oracle Database overview",
 "tags": [ "oracledb-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(oracledb_up{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(oracledb_up{job=~\"$job\"}, instance)"
   },
   {
    "name": "tablespace",
    "label": "Tablespace",
    "query": "label_values(oracledb_up{job=~\"$job\",instance=~\"$instance\"}, tablespace)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Database status",
   "type": "stat",
   "description": "Database status either Up or Down. Colored to be green when Up or red when Down.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "oracledb_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Number of sessions.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{job=~\"$job\",instance=~\"$instance\", resource_name=\"sessions\"}",
     "legendFormat": "{{ instance }} - open"
    },
    {
     "expr": "oracledb_resource_limit_value{job=~\"$job\",instance=~\"$instance\", resource_name=\"sessions\"}",
     "legendFormat": "{{ instance }} - limit"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "description": "Number of processes.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{job=~\"$job\",instance=~\"$instance\", resource_name=\"processes\"}",
     "legendFormat": "{{ instance }} - current"
    },
    {
     "expr": "oracledb_resource_limit_value{job=~\"$job\",instance=~\"$instance\", resource_name=\"processes\"}",
     "legendFormat": "{{ instance }} - limit"
    }
   ]
  },
  { "title": "Wait time", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Application wait time",
   "type": "timeseries",
   "description": "Application wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_application{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit wait time",
   "type": "timeseries",
   "description": "Commit wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_commit{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrency wait time",
   "type": "timeseries",
   "description": "Concurrency wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_concurrency{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration wait time",
   "type": "timeseries",
   "description": "Configuration wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_configuration{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network wait time",
   "type": "timeseries",
   "description": "Network wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_network{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scheduler wait time",
   "type": "timeseries",
   "description": "Scheduler wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_scheduler{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System I/O wait time",
   "type": "timeseries",
   "description": "System I/O wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_system_io{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User I/O wait time",
   "type": "timeseries",
   "description": "User I/O wait time, in seconds, waiting for wait events.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_user_io{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Tablespace", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 26 } },
  {
   "title": "Tablespace size",
   "type": "timeseries",
   "description": "Shows the size over time for the tablespace.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "oracledb_tablespace_bytes{job=~\"$job\",instance=~\"$instance\",tablespace=~\"$tablespace\"}",
     "legendFormat": "{{ instance }} - {{ tablespace }} - used"
    },
    {
     "expr": "oracledb_tablespace_free{job=~\"$job\",instance=~\"$instance\",tablespace=~\"$tablespace\"}",
     "legendFormat": "{{ instance }} - {{ tablespace }} - free"
    },
    {
     "expr": "oracledb_tablespace_max_bytes{job=~\"$job\",instance=~\"$instance\",tablespace=~\"$tablespace\"}",
     "legendFormat": "{{ instance }} - {{ tablespace }} - max"
    }
   ]
  }
 ]
}