{
 "title": "Apache Mesos overview",
 "tags": [ "apache-mesos-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mesos_master_uptime_seconds{}, job)"
   },
   {
    "name": "mesos_cluster",
    "label": "Mesos cluster",
    "query": "label_values(mesos_master_uptime_seconds{job=~\"$job\"}, mesos_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mesos_master_uptime_seconds{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mesos_master_uptime_seconds{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Master overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Master uptime",
   "type": "stat",
   "description": "Master uptime in seconds",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_uptime_seconds{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "CPUS available",
   "type": "stat",
   "description": "CPUs available in the cluster",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_cpus{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"total\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "stat",
   "description": "Memory available in the cluster",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_mem{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"total\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "GPUs available",
   "type": "stat",
   "description": "GPUs available in the cluster",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_gpus{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"total\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Disk available",
   "type": "stat",
   "description": "Disk available in the cluster",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_disk{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"total\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Memory utilization in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_mem{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"percent\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "timeseries",
   "description": "Disk utilization in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_disk{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"percent\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Events in queue",
   "type": "timeseries",
   "description": "Events in queue in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by(mesos_cluster, type) (mesos_master_event_queue_length{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}} - {{type}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "description": "Messages in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "max by(mesos_cluster, type) (increase(mesos_master_messages{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval)) > 0",
     "legendFormat": "{{mesos_cluster}} - {{type}}"
    }
   ]
  },
  {
   "title": "Registrar state",
   "type": "timeseries",
   "description": "Registrar state store and fetch in the cluster",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_registrar_state_store_ms{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", type=\"mean\"})",
     "legendFormat": "{{mesos_cluster}} - store"
    },
    {
     "expr": "max by(mesos_cluster) (mesos_registrar_state_fetch_ms{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}} - fetch"
    }
   ]
  },
  {
   "title": "Registrar log recovered",
   "type": "stat",
   "description": "Registrar log recovered in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_registrar_log_recovered{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Allocation runs",
   "type": "timeseries",
   "description": "Allocation runs in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (increase(mesos_master_allocation_run_ms_count{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval] offset $__interval))",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Allocation duration",
   "type": "timeseries",
   "description": "Allocation duration in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_allocation_run_ms{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Allocation latency",
   "type": "timeseries",
   "description": "Allocation latency in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_allocation_run_latency_ms{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Event queue dispatches",
   "type": "timeseries",
   "description": "Event queue dispatches in the cluster",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (mesos_master_event_queue_dispatches{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  { "title": "Agent overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 41 } },
  {
   "title": "Agent memory utilization",
   "type": "timeseries",
   "description": "Memory utilization in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (100 * mesos_slave_mem_used_bytes{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"} / clamp_min(mesos_slave_mem_bytes{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"},1))",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  },
  {
   "title": "Agent disk utilization",
   "type": "timeseries",
   "description": "The percentage of allocated disk storage in use by the agent.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(mesos_cluster) (100 * mesos_slave_disk_used_bytes{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"} / clamp_min(mesos_slave_disk_bytes{job=~\"$job\",mesos_cluster=~\"$mesos_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"},1))",
     "legendFormat": "{{mesos_cluster}}"
    }
   ]
  }
 ]
}