{
 "title": "Couchbase node overview",
 "tags": [ "couchbase-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\"}, job)"
   },
   {
    "name": "couchbase_cluster",
    "label": "Couchbase_cluster",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\"}, couchbase_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Percentage of memory allocated to Couchbase on this node actually in use.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_mem_actual_used{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"} / (clamp_min(sys_mem_actual_free{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"} + sys_mem_actual_used{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}, 1))",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization percentage across all available cores on this Couchbase node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(couchbase_cluster, job, instance) (sys_cpu_utilization_rate{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total memory used by service",
   "type": "timeseries",
   "description": "Memory used by the index, analytics, and data services for a node.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(couchbase_cluster, instance, job) (kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - data"
    },
    {
     "expr": "index_memory_used_total{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - index"
    },
    {
     "expr": "cbas_direct_memory_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - analytics"
    }
   ]
  },
  {
   "title": "Backup size",
   "type": "timeseries",
   "description": "Size of the backup for a node.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(couchbase_cluster, instance, job) (backup_data_size{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "timeseries",
   "description": "Number of active connections to a node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kv_curr_connections{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP response codes",
   "type": "timeseries",
   "description": "Rate of HTTP response codes handled by the cluster manager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sum by(job, instance, couchbase_cluster, code) (rate(cm_http_requests_total{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - {{code}}"
    }
   ]
  },
  {
   "title": "HTTP request methods",
   "type": "timeseries",
   "description": "Rate of HTTP request methods handled by the cluster manager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sum by(job, instance, couchbase_cluster, method) (rate(cm_http_requests_total{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - {{method}}"
    }
   ]
  },
  {
   "title": "Query service requests",
   "type": "timeseries",
   "description": "Rate of N1QL requests processed by the query service for a node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rate(n1ql_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval]) + rate(n1ql_invalid_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - total"
    },
    {
     "expr": "rate(rate(n1ql_errors{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - error"
    },
    {
     "expr": "rate(rate(n1ql_invalid_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - invalid"
    }
   ]
  },
  {
   "title": "Query service request processing time",
   "type": "timeseries",
   "description": "Rate of queries grouped by processing time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rate(n1ql_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - >0ms"
    },
    {
     "expr": "rate(rate(n1ql_requests_250ms{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - >250ms"
    },
    {
     "expr": "rate(rate(n1ql_requests_500ms{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - >500ms"
    },
    {
     "expr": "rate(rate(n1ql_requests_1000ms{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - >1000ms"
    },
    {
     "expr": "rate(rate(n1ql_requests_5000ms{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - >5000ms"
    }
   ]
  },
  {
   "title": "Index service requests",
   "type": "timeseries",
   "description": "Rate of index service requests served.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sum by(couchbase_cluster, instance, job) (rate(index_num_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))[$__rate_interval])",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Index cache hit ratio",
   "type": "timeseries",
   "description": "Ratio at which cache scans result in a hit rather than a miss.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(couchbase_cluster, job, instance) (increase(index_cache_hits{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])) / (clamp_min(sum by(couchbase_cluster, job, instance) (increase(index_cache_hits{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])), 1) + sum by(couchbase_cluster, job, instance) (increase(index_cache_misses{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Average scan latency",
   "type": "timeseries",
   "description": "Average time to serve a scan request per index.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(couchbase_cluster, index, instance, job) (index_avg_scan_latency{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{couchbase_cluster}} - {{instance}} - {{index}}"
    }
   ]
  }
 ]
}