{
 "title": "Couchbase bucket overview",
 "tags": [ "couchbase-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\"}, job)"
   },
   {
    "name": "couchbase_cluster",
    "label": "Couchbase_cluster",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\"}, couchbase_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Top buckets by memory used",
   "type": "timeseries",
   "description": "Memory used for the top buckets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by disk used",
   "type": "bargauge",
   "description": "Disk used for the top buckets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, couch_docs_actual_disk_size{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by current items",
   "type": "timeseries",
   "description": "Number of active items for the largest buckets.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum by(couchbase_cluster, job, bucket) (kv_curr_items{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by operations",
   "type": "timeseries",
   "description": "Rate of operations for the busiest buckets.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum by(bucket, job,couchbase_cluster,instance, op) (rate(kv_ops{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} - {{bucket}} - {{op}}"
    }
   ]
  },
  {
   "title": "Top buckets by operations failed",
   "type": "timeseries",
   "description": "Rate of operations failed for the most problematic buckets.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum by(bucket, job,couchbase_cluster,instance) (rate(kv_ops_failed{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by high priority requests",
   "type": "timeseries",
   "description": "Rate of high priority requests processed by the KV engine for the top buckets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(bucket, job,couchbase_cluster,instance) (kv_num_high_pri_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Bottom buckets by cache hit ratio",
   "type": "timeseries",
   "description": "Worst buckets by cache hit ratio.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(5, sum by(bucket, job,couchbase_cluster,instance) (increase(index_cache_hits{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval)) / (clamp_min(sum by(bucket, job,couchbase_cluster,instance) (increase(index_cache_hits{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval)), 1) + sum by(bucket, job,couchbase_cluster,instance) (increase(index_cache_misses{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval))))",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by vBuckets count",
   "type": "bargauge",
   "description": "The number of vBuckets for the top buckets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum by(bucket, job,couchbase_cluster,instance) (kv_num_vbuckets{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{instance}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by vBucket queue memory",
   "type": "timeseries",
   "description": "Memory occupied by the queue for a virtual bucket for the top buckets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster, bucket) (kv_vb_queue_memory_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  }
 ]
}