name: pr
kind: pipeline
platform:
  os: linux
  arch: amd64
steps:
- name: check .drone/drone.yml
  image: jdbgrafana/haproxy-mixin-build-image:0.0.1
  commands:
  - make .drone/drone.yml
  - git diff --exit-code -- .drone/drone.yml
---
name: default
kind: pipeline
platform:
  os: linux
  arch: amd64
steps:
- name: fmt
  image: jdbgrafana/haproxy-mixin-build-image:0.0.1
  commands:
  - make fmt
- name: .drone/drone.yml
  image: jdbgrafana/haproxy-mixin-build-image:0.0.1
  commands:
  - make .drone/drone.yml
- name: build
  image: jdbgrafana/haproxy-mixin-build-image:0.0.1
  commands:
  - make build
- name: lint
  image: jdbgrafana/haproxy-mixin-build-image:0.0.1
  commands:
  - make lint

