{
 "title": "Jenkins Overview",
 "time": { "from": "2021-02-09T18:14:32.797Z", "to": "2021-02-09T21:55:54.715Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Instance", "query": "label_values(instance)" },
   { "name": "Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Executors (In Use)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_executor_in_use_value", "legendFormat": "In Use" },
    { "expr": "jenkins_executor_count_value", "legendFormat": "Total Available" }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "description": "Number of builds waiting in the queue for an executor to become available.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_queue_size_value", "legendFormat": "Queue Size" }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_offline_value", "legendFormat": "Offline" },
    { "expr": "jenkins_node_online_value", "legendFormat": "Online" }
   ]
  },
  { "title": "Miscellaneous Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Builds (Total)",
   "type": "singlestat",
   "description": " Number of build runs initiated.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_total_total" }
   ]
  },
  {
   "title": "Projects (Enabled)",
   "type": "singlestat",
   "description": " Number of enabled projects.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_project_enabled_count_value"
    }
   ]
  },
  {
   "title": "Projects (Disabled)",
   "type": "singlestat",
   "description": " Number of configured but disabled projects.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_value"
    }
   ]
  },
  {
   "title": "Plugins (Active)",
   "type": "singlestat",
   "description": "Number of active plugins.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "Plugins (Inactive)",
   "type": "singlestat",
   "description": "Number of installed but inactive plugins.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "Plugins (Failed)",
   "type": "singlestat",
   "description": "Number of installed but failed plugins.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  {
   "title": "Plugins (Outdated)",
   "type": "singlestat",
   "description": "Number of installed plugins which have an update available.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_withUpdate" }
   ]
  }
 ]
}