{
 "title": "Kubescape",
 "tags": [ "Integration - Kubescape" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![kubescapeimage](https://landscape.cncf.io/logos/kubescape.svg)"
   }
  },
  {
   "title": "Compliance Score by framework",
   "type": "gauge",
   "description": "Compliance Score by AllControls, MITRE and NSA frameworks",
   "gridPos": { "h": 6, "w": 15, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_complianceScore{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cluster Risk Score",
   "type": "stat",
   "description": "Current Risk Score of the Cluster",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_cluster_complianceScore{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "\"Healthy\" if Kubescape -cloud-operator is running and \"Unhealthy\" if not",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\",instance=~\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controls Passed by Framework",
   "type": "stat",
   "description": "Percentage of Controls passed by the each framework",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_control_passed{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"} / (kubescape_framework_count_control_passed{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"} +    kubescape_framework_count_control_failed{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"} + kubescape_framework_count_control_skipped{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Control Status by AllControls framework",
   "type": "piechart",
   "description": "Control Status(Passed, Skipped, Failed) by AllControls framework",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_control_passed{name=\"AllControls\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Passed"
    },
    {
     "expr": "kubescape_framework_count_control_skipped{name=\"AllControls\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"AllControls\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Control Status by MITRE framework",
   "type": "piechart",
   "description": "Control Status(Passed, Skipped, Failed) by MITRE framework",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_control_passed{name=\"MITRE\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Passed"
    },
    {
     "expr": "kubescape_framework_count_control_skipped{name=\"MITRE\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"MITRE\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Control Status by NSA framework",
   "type": "piechart",
   "description": "Control Status(Passed, Skipped, Failed) by NSA framework",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_control_passed{name=\"NSA\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Passed"
    },
    {
     "expr": "kubescape_framework_count_control_skipped{name=\"NSA\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"NSA\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Resources Passed by Framework",
   "type": "stat",
   "description": "Percentage of Resources Passed by  each Framework",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubescape_framework_count_resources_passed{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"} / (kubescape_framework_count_resources_passed{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"} +    kubescape_framework_count_resources_failed{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"} + kubescape_framework_count_resources_skipped{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resource Status by AllControls framework",
   "type": "piechart",
   "description": "Resource Status(Passed, Skipped, Failed) by NSA framework",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"AllControls\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Passed"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"AllControls\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"AllControls\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Resource Status by MITRE framework",
   "type": "piechart",
   "description": "Resource Status(Passed, Skipped, Failed) by NSA framework",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"MITRE\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Passed"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"MITRE\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"MITRE\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Resource Status by NSA framework",
   "type": "piechart",
   "description": "Resource Status(Passed, Skipped, Failed) by NSA framework",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"NSA\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Passed"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"NSA\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "kubescape_framework_count_resources_failed{name=\"NSA\", job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Scanned Severity",
   "type": "table",
   "description": "Scanned Severity with name, severity level and reference link",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count(kubescape_control_count_resources_failed{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\"}) by (name, severity, link)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 10 Severity with level",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(name) (kubescape_control_complianceScore{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\",severity=\"High\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}