{
 "title": "Aerospike overview",
 "tags": [ "aerospike" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(aerospike_namespace_data_used_pct{}, job)"
   },
   {
    "name": "aerospike_cluster",
    "label": "Aerospike cluster",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\"}, aerospike_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}, ns)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "k",
    "label": "Top node count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Number of nodes in an Aerospike cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster, instance,ns) (aerospike_namespace_ns_cluster_size{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "table",
   "description": "Number of namespaces in an Aerospike cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster, instance,ns) (aerospike_namespace_ns_cluster_size{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})"
    }
   ]
  },
  {
   "title": "Unavailable partitions",
   "type": "bargauge",
   "description": "Number of unavailable partitions in Aerospike namespaces",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (aerospike_namespace_unavailable_partitions{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})",
     "legendFormat": "{{aerospike_cluster}}"
    }
   ]
  },
  {
   "title": "Dead partitions",
   "type": "bargauge",
   "description": "Number of dead partitions in Aerospike namespaces",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (aerospike_namespace_dead_partitions{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})",
     "legendFormat": "{{aerospike_cluster}}"
    }
   ]
  },
  {
   "title": "Top nodes by memory usage",
   "type": "table",
   "description": "Memory utilization for the top k nodes in an Aerospike cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk($k, 100 - sum by(job,aerospike_cluster,cluster, instance,ns) (avg_over_time(aerospike_node_stats_system_free_mem_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Top nodes by disk usage",
   "type": "table",
   "description": "Disk utilization for the top k nodes in an Aerospike cluster. Compatible with Aerospike versions < 7.0 using legacy metrics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk($k, 100 - sum by(job,aerospike_cluster,cluster, instance,ns) (avg_over_time(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__interval])))\nor\ntopk($k, 100 - sum by(job,aerospike_cluster,cluster, instance,ns) (avg_over_time(aerospike_namespace_device_free_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Client reads",
   "type": "timeseries",
   "description": "Rate of client read transactions in an Aerospike cluster organized by result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_read_success{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - success"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_read_error{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - error"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_read_timeout{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - timeout"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_read_not_found{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - not found"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_read_filtered_out{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - filtered"
    }
   ]
  },
  {
   "title": "Client writes",
   "type": "timeseries",
   "description": "Rate of client write transactions in an Aerospike cluster organized by result.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_write_success{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - success"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_write_error{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - error"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_write_timeout{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - timeout"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_write_filtered_out{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - filtered"
    }
   ]
  },
  {
   "title": "Client UDF transactions",
   "type": "timeseries",
   "description": "Rate of client UDF transactions in an Aerospike cluster organized by result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_udf_complete{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - complete"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_udf_error{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - error"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_udf_timeout{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - timeout"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (rate(aerospike_namespace_client_udf_filtered_out{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval]))",
     "legendFormat": "{{aerospike_cluster}} - filtered"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of active connections to an Aerospike cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (aerospike_node_stats_client_connections{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})",
     "legendFormat": "{{aerospike_cluster}} - client"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (aerospike_node_stats_fabric_connections{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})",
     "legendFormat": "{{aerospike_cluster}} - fabric"
    },
    {
     "expr": "sum by(job,aerospike_cluster,cluster) (aerospike_node_stats_heartbeat_connections{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"})",
     "legendFormat": "{{aerospike_cluster}} - heartbeat"
    }
   ]
  }
 ]
}