{
 "title": "Aerospike namespace overview",
 "tags": [ "aerospike" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(aerospike_namespace_data_used_pct{}, job)"
   },
   {
    "name": "aerospike_cluster",
    "label": "Aerospike cluster",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\"}, aerospike_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(aerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}, ns)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Unavailable partitions",
   "type": "bargauge",
   "description": "Number of unavailable partitions in this Aerospike namespace",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_namespace_unavailable_partitions{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}",
     "legendFormat": "{{instance}} {{ns}} - {{ns}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - aerospike_namespace_device_free_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}\nor\naerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\", storage_engine=\"device\"}",
     "legendFormat": "{{instance}} {{ns}} - {{ns}}"
    }
   ]
  },
  {
   "title": "Dead partitions",
   "type": "bargauge",
   "description": "Number of dead partitions in this Aerospike namespace",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_namespace_dead_partitions{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}",
     "legendFormat": "{{instance}} {{ns}} - {{ns}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory utilization in an Aerospike namespace",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - aerospike_namespace_memory_free_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}\nor\naerospike_namespace_data_used_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\", storage_engine=\"memory\"}",
     "legendFormat": "{{instance}} {{ns}} - {{ns}}"
    }
   ]
  },
  {
   "title": "Client reads",
   "type": "timeseries",
   "description": "Rate of client read transactions in this Aerospike namespace organized by result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_client_read_success{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - success"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_error{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - error"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_timeout{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - timeout"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_not_found{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - not found"
    },
    {
     "expr": "rate(aerospike_namespace_client_read_filtered_out{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - filtered"
    }
   ]
  },
  {
   "title": "Client writes",
   "type": "timeseries",
   "description": "Rate of client write transactions in this Aerospike namespace organized by result.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_client_write_success{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - success"
    },
    {
     "expr": "rate(aerospike_namespace_client_write_error{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - error"
    },
    {
     "expr": "rate(aerospike_namespace_client_write_timeout{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - timeout"
    },
    {
     "expr": "rate(aerospike_namespace_client_write_filtered_out{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - filtered"
    }
   ]
  },
  {
   "title": "Client UDF transactions",
   "type": "timeseries",
   "description": "Rate of client UDF transactions in this Aerospike namespace organized by result.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(aerospike_namespace_client_udf_complete{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - complete"
    },
    {
     "expr": "rate(aerospike_namespace_client_udf_error{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - error"
    },
    {
     "expr": "rate(aerospike_namespace_client_udf_timeout{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - timeout"
    },
    {
     "expr": "rate(aerospike_namespace_client_udf_filtered_out{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}[$__rate_interval])",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }} - filtered"
    }
   ]
  },
  {
   "title": "Cache read utilization",
   "type": "timeseries",
   "description": "Percentage of read transactions that are resolved by a cache hit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aerospike_namespace_cache_read_pct{job=~\"$job\",aerospike_cluster=~\"$aerospike_cluster\",cluster=~\"$cluster\",instance=~\"$instance\",ns=~\"$ns\"}",
     "legendFormat": "{{ aerospike_cluster }} - {{ ns }}"
    }
   ]
  }
 ]
}