{
 "title": "Apache Hadoop ResourceManager overview",
 "tags": [ "apache-hadoop-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\"}, job)"
   },
   {
    "name": "hadoop_cluster",
    "label": "Hadoop cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\",job=~\"$job\"}, hadoop_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "ResourceManager overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Node Managers state",
   "type": "bargauge",
   "description": "The number of Node Managers by state in the Hadoop ResourceManager.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_numactivenms{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"ClusterMetrics\"}",
     "legendFormat": "active"
    },
    {
     "expr": "hadoop_resourcemanager_numdecommissionednms{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"ClusterMetrics\"}",
     "legendFormat": "decommissioned"
    },
    {
     "expr": "hadoop_resourcemanager_numlostnms{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"ClusterMetrics\"}",
     "legendFormat": "lost"
    },
    {
     "expr": "hadoop_resourcemanager_numunhealthynms{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"ClusterMetrics\"}",
     "legendFormat": "unhealthy"
    },
    {
     "expr": "hadoop_resourcemanager_numrebootednms{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"ClusterMetrics\"}",
     "legendFormat": "rebooted"
    },
    {
     "expr": "hadoop_resourcemanager_numshutdownnms{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"ClusterMetrics\"}",
     "legendFormat": "shutdown"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Applications state",
   "type": "timeseries",
   "description": "Number of applications by state for the Hadoop ResourceManager.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appsrunning{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "running"
    },
    {
     "expr": "hadoop_resourcemanager_appspending{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "hadoop_resourcemanager_appskilled{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "killed"
    },
    {
     "expr": "hadoop_resourcemanager_appssubmitted{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "submitted"
    },
    {
     "expr": "hadoop_resourcemanager_appscompleted{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "completed"
    },
    {
     "expr": "hadoop_resourcemanager_appsfailed{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "timeseries",
   "description": "The available memory in the Hadoop ResourceManager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_availablemb{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "available"
    },
    {
     "expr": "hadoop_resourcemanager_allocatedmb{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "Available virtual cores",
   "type": "timeseries",
   "description": "The available virtual cores in the Hadoop ResourceManager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_availablevcores{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "available"
    },
    {
     "expr": "hadoop_resourcemanager_allocatedvcores{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"QueueMetrics\", q0=\"root\", q1=\"default\"}",
     "legendFormat": "allocated"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 26 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "The Heap and non-heap memory used for the ResourceManager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_memheapusedm{name=\"JvmMetrics\", job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "hadoop_resourcemanager_memnonheapusedm{name=\"JvmMetrics\", job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "nonheap"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "description": "The Heap and non-heap memory committed for the ResourceManager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_memheapcommittedm{name=\"JvmMetrics\", job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "hadoop_resourcemanager_memnonheapcommittedm{name=\"JvmMetrics\", job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "nonheap"
    }
   ]
  },
  {
   "title": "Garbage collection count",
   "type": "timeseries",
   "description": "The recent increase in the number of garbage collection events for the ResourceManager JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "increase(hadoop_resourcemanager_gccount{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}: GC count"
    }
   ]
  },
  {
   "title": "Average garbage collection time",
   "type": "timeseries",
   "description": "The average duration for each garbage collection operation in the ResourceManager JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_resourcemanager_gctimemillis{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval) / clamp_min(increase(hadoop_resourcemanager_gccount{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset $__interval), 1)",
     "legendFormat": "{{instance}}: Average GC time"
    }
   ]
  }
 ]
}