{
 "title": "Apache Hadoop DataNode overview",
 "tags": [ "apache-hadoop-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\"}, job)"
   },
   {
    "name": "hadoop_cluster",
    "label": "Hadoop cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\",job=~\"$job\"}, hadoop_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hadoop_namenode_blockstotal{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "DataNode overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Unread blocks evicted",
   "type": "timeseries",
   "description": "Total number of blocks evicted without being read by the Hadoop DataNode.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(hadoop_datanode_ramdiskblocksevictedwithoutread{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Blocks removed",
   "type": "timeseries",
   "description": "Total number of blocks removed by the Hadoop DataNode.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "increase(hadoop_datanode_blocksremoved{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Volume failures",
   "type": "timeseries",
   "description": "Displays the total number of volume failures encountered by the Hadoop DataNode.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "increase(hadoop_datanode_volumefailures{job=\"integrations/apache-hadoop\",job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  }
 ]
}