{
 "title": "Apache Hadoop NodeManager overview",
 "tags": [ "apache-hadoop-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hadoop_namenode_blockstotal{}, job)"
   },
   {
    "name": "hadoop_cluster",
    "label": "Hadoop cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=~\"$job\"}, hadoop_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hadoop_namenode_blockstotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "NodeManager overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Applications running",
   "type": "stat",
   "description": "Number of applications currently running for the NodeManager.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_nodemanager_applicationsrunning{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Allocated containers",
   "type": "stat",
   "description": "Number of containers currently allocated for the NodeManager.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_nodemanager_allocatedcontainers{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Containers localization duration",
   "type": "stat",
   "description": "Average time taken for the NodeManager to localize necessary resources for a container.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_localizationdurationmillisavgtime{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Containers launch duration",
   "type": "stat",
   "description": "Average time taken to launch a container on the NodeManager after the necessary resources have been localized.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_containerlaunchdurationavgtime{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "The Heap and non-heap memory used for the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_memheapusedm{name=\"JvmMetrics\", job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - heap"
    },
    {
     "expr": "hadoop_nodemanager_memnonheapusedm{name=\"JvmMetrics\", job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - nonheap"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "description": "The Heap and non-heap memory committed for the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_memheapcommittedm{name=\"JvmMetrics\", job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - heap"
    },
    {
     "expr": "hadoop_nodemanager_memnonheapcommittedm{name=\"JvmMetrics\", job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - nonheap"
    }
   ]
  },
  {
   "title": "Garbage collection count",
   "type": "timeseries",
   "description": "The number of garbage collection events for the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hadoop_nodemanager_gccount{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Average garbage collection time",
   "type": "timeseries",
   "description": "The average duration for each garbage collection operation in the NodeManager JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hadoop_nodemanager_gctimemillis{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval) / clamp_min(increase(hadoop_nodemanager_gccount{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval), 1)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 26 } },
  {
   "title": "Node memory used",
   "type": "timeseries",
   "description": "The Heap and non-heap memory used for the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_memheapusedm{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - heap"
    },
    {
     "expr": "hadoop_nodemanager_memnonheapusedm{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - nonheap"
    }
   ]
  },
  {
   "title": "Node memory committed",
   "type": "timeseries",
   "description": "The Heap and non-heap memory committed for the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_memheapcommittedm{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - heap"
    },
    {
     "expr": "hadoop_nodemanager_memnonheapcommittedm{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - nonheap"
    }
   ]
  },
  {
   "title": "Node CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization of the Node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * hadoop_nodemanager_nodecpuutilization{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU utilization",
   "type": "timeseries",
   "description": "GPU utilization of the Node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * hadoop_nodemanager_nodegpuutilization{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 43 } },
  {
   "title": "Container state",
   "type": "timeseries",
   "description": "Number of containers with a given state for the NodeManager.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_containerspaused{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - paused"
    },
    {
     "expr": "hadoop_nodemanager_containerslaunched{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - launched"
    },
    {
     "expr": "hadoop_nodemanager_containerscompleted{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - completed"
    },
    {
     "expr": "hadoop_nodemanager_containersfailed{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - failed"
    },
    {
     "expr": "hadoop_nodemanager_containerskilled{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - killed"
    },
    {
     "expr": "hadoop_nodemanager_containersiniting{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - initing"
    },
    {
     "expr": "hadoop_nodemanager_containersreiniting{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - reiniting"
    }
   ]
  },
  {
   "title": "Containers used memory",
   "type": "timeseries",
   "description": "Total memory used by containers for the NodeManager.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_containerusedmemgb{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - used memory"
    }
   ]
  },
  {
   "title": "Containers used virtual memory",
   "type": "timeseries",
   "description": "Total virtual memory used by containers for the NodeManager.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_containerusedvmemgb{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - used virtual memory"
    }
   ]
  },
  {
   "title": "Containers available memory",
   "type": "timeseries",
   "description": "The memory available and currently allocated for containers by the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_availablegb{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - available memory"
    },
    {
     "expr": "hadoop_nodemanager_allocatedgb{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - allocated memory"
    }
   ]
  },
  {
   "title": "Containers available virtual cores",
   "type": "timeseries",
   "description": "The virtual cores available and currently allocated for containers by the NodeManager.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_availablevcores{name=\"NodeManagerMetrics\", job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - available"
    },
    {
     "expr": "hadoop_nodemanager_allocatedvcores{name=\"NodeManagerMetrics\", job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - allocated"
    }
   ]
  }
 ]
}