{
 "title": "ArgoCD",
 "tags": [ "argocd-integration" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info,cluster)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "![argoimage](https://cncf-branding.netlify.app/img/projects/argo/stacked/color/argo-stacked-color.png)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of ArgoCD",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"integrations/argocd/application-controller\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "Total number of Cluster connected to ArgoCD",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{job=\"integrations/argocd/application-controller\", cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "description": "Total number of repositories connected to ArgoCD",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{namespace=~\"$namespace\",cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "description": "Number of ArgoCD Applications",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",cluster=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "description": "Total Number of Projects",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (project) (argocd_cluster_info{job=\"integrations/argocd/application-controller\", cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Healthy Applications",
   "type": "gauge",
   "description": "Percentage of Healthy Applications",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",cluster=~\"$cluster\",health_status=~\"Healthy\",sync_status=~\"$sync_status\",health_status!=\"\"}) / sum(argocd_app_info{namespace=~\"$namespace\",cluster=~\"$cluster\",sync_status=~\"$sync_status\",health_status!=\"\"})",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Synced Applications",
   "type": "gauge",
   "description": "Percentage of Synced Applications",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",cluster=~\"$cluster\",health_status=~\"$health_status\",sync_status=\"Synced\"}) / sum(argocd_app_info{namespace=~\"$namespace\",cluster=~\"$cluster\",health_status=~\"$health_status\"})",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Sync Rate",
   "type": "stat",
   "description": "Sync Success of ArgoCD Applications",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(argocd_app_sync_total{namespace=~\"$namespace\",cluster=~\"$cluster\", phase=\"Succeeded\"}[$__rate_interval])) by ($grouping) * 60",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "stat",
   "description": "Sync Failures of ArgoCD Applications",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(argocd_app_sync_total{namespace=~\"$namespace\",cluster=~\"$cluster\", phase=~\"Error|Failed\"}[$__rate_interval])) by ($grouping) * 60",
     "legendFormat": "{{phase}}: {{$grouping}}"
    }
   ]
  },
  {
   "title": "Cluster Connection",
   "type": "stat",
   "description": "The k8s cluster current connection status",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_cluster_connection_status{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Cluster cache age",
   "type": "stat",
   "description": "Cluster cache age in seconds",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "argocd_cluster_cache_age_seconds{job=\"integrations/argocd/application-controller\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Git Requests (ls-remote)",
   "type": "stat",
   "description": "Git Requests(ls-remote) per Repository",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"ls-remote\",job=\"integrations/argocd/repo-server\"}[10m])) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Git Requests (fetch)",
   "type": "stat",
   "description": "Git Requests(Fetch) per Repository",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{request_type=\"fetch\",job=\"integrations/argocd/repo-server\"}[10m])) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Application Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Status",
   "type": "table",
   "description": "ArgoCD applications status panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "argocd_app_info{cluster=~\"$cluster\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Controller Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "heatmap",
   "description": "Total K8s API Activity by ArgoCD",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "argocd_app_k8s_request_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "{{verb}} {{resource_kind}}"
    }
   ]
  },
  {
   "title": "kubectl executions",
   "type": "timeseries",
   "description": "Number of kubectl executions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(argocd_kubectl_exec_total{cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Pending kubectl executions",
   "type": "gauge",
   "description": "Number of pending kubectl executions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_kubectl_exec_pending{job=\"integrations/argocd/application-controller\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Reconciliation Activity",
   "type": "timeseries",
   "description": "Applications Reconciliation Activity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(argocd_app_reconcile_count{namespace=~\"$namespace\",cluster=~\"$cluster\"}[$__rate_interval])) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "description": "Workqueue Depth of Applications",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{name=~\"app_.*\",job=\"integrations/argocd/application-controller\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resource Objects Count",
   "type": "stat",
   "description": "Number of k8s resource objects in the cache",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_cluster_api_resource_objects{cluster=~\"$cluster\",job=\"integrations/argocd/application-controller\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "API Resources Count",
   "type": "stat",
   "description": "Number of monitored kubernetes API resources",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(argocd_cluster_api_resources{cluster=~\"$cluster\",job=\"integrations/argocd/application-controller\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Events Count",
   "type": "timeseries",
   "description": "Number of processes k8s resource events",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_cluster_events_total{cluster=~\"$cluster\"}[5m])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Repo Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "Memory used by Repo Server",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"integrations/argocd/repo-server\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "description": "Goroutines used by Repo Server",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"integrations/argocd/repo-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending requests requiring repository lock",
   "type": "timeseries",
   "description": "Number of pending requests requiring repository lock",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "argocd_repo_pending_request_total{cluster=~\"$cluster\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "description": "Memory used by ArgoCD Server",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"integrations/argocd/argocd-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPCs completion rate",
   "type": "timeseries",
   "description": "Rate of completed RPCs",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"integrations/argocd/argocd-server\"}[$__rate_interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC stream message rate",
   "type": "timeseries",
   "description": "Rate of gRPC stream messages sent by the server",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{job=\"integrations/argocd/argocd-server\"}[$__rate_interval])) by (grpc_service)",
     "legendFormat": "{{ grpc_service }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutines by ArgoCD Server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"integrations/argocd/argocd-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "description": "GC Time Quantiles by ArgoCD Server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"integrations/argocd/argocd-server\", quantile=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}