{
 "title": "InfluxDB instance overview",
 "description": "Dashboard providing detailed overview of InfluxDB instance performance, including configuration stats, Go runtime performance, query/request load, and task scheduler activity.",
 "tags": [ "influxdb-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(influxdb_uptime_seconds{job=\"integrations/influxdb\"}, job)"
   },
   {
    "name": "influxdb_cluster",
    "label": "InfluxDB cluster",
    "query": "label_values(influxdb_uptime_seconds{job=\"integrations/influxdb\",job=~\"$job\"}, influxdb_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(influxdb_uptime_seconds{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "InfluxDB instance overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time that the InfluxDB process has been running.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "influxdb_uptime_seconds{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "stat",
   "description": "Number of buckets on the server.",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "influxdb_buckets_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Buckets"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Total number of users for the server.",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "influxdb_users_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Replications",
   "type": "stat",
   "description": "Number of replication configurations on the server.",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "influxdb_replications_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Replications"
    }
   ]
  },
  {
   "title": "Remotes",
   "type": "stat",
   "description": "Number of remote connections configured on the server.",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "influxdb_remotes_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Remotes"
    }
   ]
  },
  {
   "title": "Scrapers",
   "type": "stat",
   "description": "Number of scrapers on the server.",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "influxdb_scrapers_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Scrapers"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "description": "Number of dashboards on the server.",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "influxdb_dashboards_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "Dashboards"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Number of threads currenty active on the server.",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries and operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "HTTP API requests",
   "type": "timeseries",
   "description": "Rate of HTTP API requests to the API, organized by response code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job,influxdb_cluster,instance) (rate(http_api_requests_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Active queries",
   "type": "timeseries",
   "description": "Number of queries compiling, queuing, and executing on this instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,influxdb_cluster,instance) (qc_compiling_active{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - compiling"
    },
    {
     "expr": "sum by (job,influxdb_cluster,instance) (qc_queueing_active{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - queuing"
    },
    {
     "expr": "sum by (job,influxdb_cluster,instance) (qc_executing_active{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - executing"
    }
   ]
  },
  {
   "title": "HTTP operations",
   "type": "timeseries",
   "description": "Rate of HTTP query and write operations handled by this instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job,influxdb_cluster,instance, status) (rate(http_query_request_count{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - query - {{status}}"
    },
    {
     "expr": "sum by (job,influxdb_cluster,instance, status) (rate(http_write_request_count{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - write - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP operation data",
   "type": "timeseries",
   "description": "Bytes per second for HTTP query and write request/response bodies.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,influxdb_cluster,instance) (rate(http_query_request_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - query request"
    },
    {
     "expr": "sum by (job,influxdb_cluster,instance) (rate(http_query_response_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - query response"
    },
    {
     "expr": "sum by (job,influxdb_cluster,instance) (rate(http_write_request_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - write request"
    },
    {
     "expr": "sum by (job,influxdb_cluster,instance) (rate(http_write_response_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - write response"
    }
   ]
  },
  {
   "title": "IQL query rate",
   "type": "timeseries",
   "description": "Rate of InfluxQL queries executed by this instance.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "query/s" } },
   "targets": [
    {
     "expr": "sum by (job,influxdb_cluster,instance, result) (rate(influxql_service_requests_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{result}}"
    }
   ]
  },
  {
   "title": "IQL response time / $__interval",
   "type": "timeseries",
   "description": "Total time spent executing InfluxQL queries during each $__interval.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job,influxdb_cluster,instance, result) (increase(influxql_service_executing_duration_seconds_sum{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__interval] offset -$__interval))",
     "legendFormat": "{{instance}} - {{result}}"
    }
   ]
  },
  {
   "title": "BoltDB operations",
   "type": "timeseries",
   "description": "Rate of reads and writes to the underlying BoltDB storage engine for the server.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(boltdb_reads_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "rate(boltdb_writes_total{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  { "title": "Task scheduler", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 34 } },
  {
   "title": "Active tasks",
   "type": "timeseries",
   "description": "Number of tasks currently being executed for the server.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "task_scheduler_current_execution{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active workers",
   "type": "timeseries",
   "description": "Number of workers currently running tasks on the server.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "task_executor_total_runs_active{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker usage",
   "type": "timeseries",
   "description": "Percentage of available workers that are currently busy.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "task_executor_workers_busy{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "Rate of executions and execution failures for the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(task_scheduler_total_execution_calls{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - total"
    },
    {
     "expr": "rate(task_scheduler_total_execute_failure{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - failed"
    }
   ]
  },
  {
   "title": "Schedules",
   "type": "timeseries",
   "description": "Rate of schedule operations and schedule operation failures for the server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(task_scheduler_total_schedule_calls{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - total"
    },
    {
     "expr": "rate(task_scheduler_total_schedule_fails{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - failed"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 51 } },
  {
   "title": "Time since last GC",
   "type": "stat",
   "description": "Amount of time since the last garbage collection cycle.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - go_memstats_last_gc_time_seconds{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "description": "Server CPU time spent on garbage collection.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_sum{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC CPU usage",
   "type": "timeseries",
   "description": "Percent of server CPU time used for garbage collection.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{influxdb_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "timeseries",
   "description": "Heap memory usage for the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"} / clamp_min(go_memstats_heap_idle_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"} + go_memstats_heap_alloc_bytes{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of OS threads created for the server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=\"integrations/influxdb\",job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}