{
 "title": "WSO2 Siddhi Table Statistics",
 "tags": [
  "prometheus",
  "siddhi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(siddhi_table_latency,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(siddhi_table_latency{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(siddhi_table_latency{job=~\"$job\",instance=~\"$instance\"},app)"
    }
   },
   {
    "name": "element",
    "label": "Element",
    "query": {
     "query": "label_values(siddhi_table_latency{job=~\"$job\",instance=~\"$instance\",app=~\"$application\"},element)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(siddhi_table_latency{job=~\"$job\",instance=~\"$instance\",app=~\"$application\",element=~\"$element\"},operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Table Statistics Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(siddhi_table_latency{job=~\"$job\",instance=~\"$instance\",app=~\"$application\",element=~\"$element\",operation=~\"$operation\"}) by (instance,app,element,operation)"
    },
    {
     "expr": "sum(siddhi_table_throughput_total{job=~\"$job\",instance=~\"$instance\",app=~\"$application\",element=~\"$element\",operation=~\"$operation\"}) by (instance,app,element,operation)"
    }
   ]
  },
  {
   "title": "Back to Overall Statistics",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(count by (element) (siddhi_table_latency{job=~\"$job\",instance=~\"$instance\",app=~\"$application\"})))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "siddhi_table_latency{job=~\"$job\",instance=~\"$instance\",app=~\"$application\",element=~\"$element\",operation=~\"$operation\"}",
     "legendFormat": "Application=\"{{app}}\", element=\"{{element}}\", operation=\"{{operation}}\", instance=\"{{instance}}\" "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "siddhi_table_throughput_total{job=~\"$job\",instance=~\"$instance\",app=~\"$application\",element=~\"$element\",operation=~\"$operation\"}",
     "legendFormat": "Application=\"{{app}}\", element=\"{{element}}\", operation=\"{{operation}}\", instance=\"{{instance}}\" "
    }
   ]
  }
 ]
}