{
 "title": "WSO2 Siddhi Server Statistics",
 "tags": [
  "prometheus ",
  "siddhi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\",instance=~\"$instance\"},app)"
    }
   },
   {
    "name": "element",
    "label": "Element",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\",instance=~\"$instance\",app=\"$application\"},element)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\",instance=~\"$instance\",app=\"$application\"},type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Up/Down",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=~\"integrations/wso2-streaming-integrator\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Back to Overall Statistics",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Siddhi Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count(count by (app) (siddhi_stream_throughput_total{job=~\"$job\", instance=~\"$instance\"})))"
    }
   ]
  },
  {
   "title": "Server Statistics Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(siddhi_source_throughput_total{job=~\"$job\",instance=~\"$instance\",type=\"source\",operation!=\"inMemory\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_system_load_average{job=~\"$job\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_os_cpu_load_system{job=~\"$job\", instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(jvm_memory_heap_usage{job=~\"$job\", instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Overall Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(siddhi_source_throughput_total{job=~\"$job\",instance=~\"$instance\",type=\"source\",operation!=\"inMemory\"})",
     "legendFormat": "Instance=\"{{instance}}\" "
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_os_system_load_average{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Instance=\"{{instance}}\" "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jvm_os_cpu_load_system{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "cpu system load{Instance=\"{{instance}}\"}"
    },
    {
     "expr": "jvm_os_cpu_load_process{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "cpu process load{Instance=\"{{instance}}\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_heap_usage{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "used memory{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_memory_heap_max{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "total memory{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Physical Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_os_physical_memory_total_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "physical memory total{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_os_physical_memory_free_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "physical memory free{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Threads ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "threads count{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_threads_daemon_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "daemon threads count{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Class Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_class_loading_unloaded_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "unloaded total{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_class_loading_loaded_current{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "loaded current{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_class_loading_loaded_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "loaded total{instance=\"{{instance}}\" }"
    }
   ]
  },
  {
   "title": "JVM Swap Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_os_swap_space_total_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "total swap size{instance=\"{{instance}}\" }"
    },
    {
     "expr": "jvm_os_swap_space_free_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "free swap size{instance=\"{{instance}}\" }"
    }
   ]
  }
 ]
}