---
kind: pipeline
name: build
steps:
- commands:
  - make install-ci-deps
  - make lint-fmt
  - make lint-mixins
  - make tests
  image: golang:1.18
  name: lint-fmt
- commands:
  - make tests
  image: golang:1.18
  name: tests
trigger:
  event:
    include:
    - pull_request
---
kind: signature
hmac: 87f057027e279509009043bb1d100de9d0b64fc610c13044b82f0067a9607a4f

...
