---
kind: pipeline
name: build
steps:
- commands:
  - make install-ci-deps
  - make lint-fmt
  - make lint-mixins
  image: golang:1.18
  name: lint-fmt
- commands:
  - make install-ci-deps
  - make tests
  image: golang:1.18
  name: tests
trigger:
  event:
    include:
    - pull_request
---
kind: signature
hmac: 569cd1940689a70b907683e347d832a4a2809c1dbf23035ab036acf88b72a57a

...
