---
kind: pipeline
name: build
steps:
- commands:
  - make install-ci-deps
  - make lint-fmt
  image: golang:1.18
  name: lint-fmt
trigger:
  event:
    include:
    - pull_request
---
kind: signature
hmac: 3596beb8fdd28b1bba163be586d4cd0190530f739bc5c9991a9a9d7da3d03fef

...
