---
kind: pipeline
name: build
steps:
- commands:
  - make install-ci-deps
  - make lint-fmt
  image: golang:1.18
  name: lint-fmt
- commands:
  - make install-ci-deps
  - make lint-mixins
  image: golang:1.18
  name: lint-mixtool
trigger:
  event:
    include:
    - pull_request
---
kind: signature
hmac: b6502f5e449dd49bea534353ff7163cc2304c16de248d8e347a16cfaee00d76d

...
