{
 "title": "HAProxy / Frontend",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(haproxy_process_start_time_seconds, instance)"
   },
   {
    "name": "job",
    "query": "label_values(haproxy_process_start_time_seconds, job)"
   },
   {
    "name": "frontend",
    "query": "label_values(haproxy_frontend_status, proxy)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP",
   "type": "graph",
   "description": "HTTP requests per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_http_requests_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Connections per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "connps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_connections_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Bytes in/out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}:in",
     "refID": "A"
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}:out",
     "refID": "B"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Request errors per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_request_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "graph",
   "description": "Internal errors per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errps" } },
   "targets": [
    {
     "expr": "rate(haproxy_frontend_internal_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$frontend\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  }
 ]
}