{
 "title": "HAProxy / Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(haproxy_process_start_time_seconds, instance)"
   },
   {
    "name": "job",
    "query": "label_values(haproxy_process_start_time_seconds, job)"
   },
   {
    "name": "backend",
    "query": "label_values(haproxy_backend_status, proxy)"
   },
   {
    "name": "server",
    "query": "label_values(haproxy_server_status, server)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "x": 0, "y": 0, "h": 1, "w": 24 } },
  {
   "title": "HTTP",
   "type": "graph",
   "description": "HTTP responses per second. There will be no data for servers using tcp mode.",
   "gridPos": { "x": 0, "y": 0, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Attempted connections",
   "type": "graph",
   "description": "Attempted connections per second",
   "gridPos": { "x": 8, "y": 0, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "connps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_attempts_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Bytes in/out",
   "type": "graph",
   "gridPos": { "x": 16, "y": 0, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "in{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "rate(haproxy_server_bytes_out_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "out{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "x": 0, "y": 6, "h": 1, "w": 24 } },
  {
   "title": "Response",
   "type": "graph",
   "description": "Response errors per second",
   "gridPos": { "x": 0, "y": 6, "h": 6, "w": 8 },
   "targets": [
    {
     "expr": "rate(haproxy_server_response_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "graph",
   "description": "Connection errors per second",
   "gridPos": { "x": 8, "y": 6, "h": 6, "w": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "graph",
   "description": "Internal errors per second",
   "gridPos": { "x": 16, "y": 6, "h": 6, "w": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_internal_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "x": 0, "y": 12, "h": 1, "w": 24 } },
  {
   "title": "Average duration",
   "type": "graph",
   "description": "Average duration for last 1024 succesful connections",
   "gridPos": { "x": 0, "y": 12, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_queue_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "haproxy_server_connect_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "haproxy_server_response_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "haproxy_server_total_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Max duration",
   "type": "graph",
   "description": "Max duration for last 1024 succesful connections",
   "gridPos": { "x": 8, "y": 12, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_queue_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "haproxy_server_max_connect_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "haproxy_server_max_response_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    },
    {
     "expr": "haproxy_server_max_total_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}"
    }
   ]
  }
 ]
}