{
 "title": "Kafka topic overview",
 "tags": [ "kafka-integration" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_log_log_logstartoffset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\"}, job)"
   },
   {
    "name": "kafka_cluster",
    "label": "Kafka_cluster",
    "query": "label_values(kafka_log_log_logstartoffset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\"}, kafka_cluster)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_log_log_logstartoffset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}, topic)"
   },
   {
    "name": "consumergroup",
    "label": "Consumergroup",
    "query": "label_values(kafka_consumergroup_uncommitted_offsets{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Topic overview",
   "type": "table",
   "description": "Kafka active topics overview. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (job,kafka_cluster,topic,partition) (\n  kafka_log_log_logstartoffset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}\n)",
     "legendFormat": "{{ topic }}"
    },
    {
     "expr": "max by (job,kafka_cluster,topic,partition) (\n  kafka_log_log_logendoffset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}\n)",
     "legendFormat": "{{ topic }}"
    },
    {
     "expr": "sum by (job,kafka_cluster,topic,partition) (\n  rate(kafka_topic_partition_current_offset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}[$__rate_interval])\n)",
     "legendFormat": "{{ topic }}"
    },
    {
     "expr": "max by (job,kafka_cluster,topic,partition) (\n  kafka_log_log_size{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}\n)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "timeseries",
   "description": "Messages in per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,topic) (\n  rate(kafka_topic_partition_current_offset{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}[$__rate_interval])\n)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Topic bytes in",
   "type": "timeseries",
   "description": "Topic bytes in rate.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,topic) (\n  rate(kafka_server_brokertopicmetrics_bytesinpersec{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}[$__rate_interval])\n)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Topic bytes out",
   "type": "timeseries",
   "description": "Topic bytes out rate.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,topic) (\n  rate(kafka_server_brokertopicmetrics_bytesoutpersec{topic!=\"__consumer_offsets\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\"}[$__rate_interval])\n)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  { "title": "Consumer groups", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 23 } },
  {
   "title": "Consumer group overview",
   "type": "table",
   "description": "Consumer group consume rate.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,consumergroup,topic) (\n  rate(kafka_consumergroup_current_offset{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}[$__rate_interval])\n)",
     "legendFormat": "{{ consumergroup }} ({{ topic }})"
    },
    {
     "expr": "sum by (job,kafka_cluster,consumergroup,topic) (\n  kafka_consumergroup_uncommitted_offsets{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}\n)",
     "legendFormat": "{{ consumergroup }} ({{ topic }})"
    },
    {
     "expr": "avg by (job,kafka_cluster,consumergroup,topic) (\n  kafka_consumer_lag_millis{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}\n)",
     "legendFormat": "{{ consumergroup }} ({{ topic }})"
    }
   ]
  },
  {
   "title": "Consumer group consume rate",
   "type": "timeseries",
   "description": "Consumer group consume rate.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,consumergroup,topic) (\n  rate(kafka_consumergroup_current_offset{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}[$__rate_interval])\n)",
     "legendFormat": "{{ consumergroup }} ({{ topic }})"
    }
   ]
  },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "description": "Current approximate lag of a ConsumerGroup at Topic/Partition.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,consumergroup,topic) (\n  kafka_consumergroup_uncommitted_offsets{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}\n)",
     "legendFormat": "{{ consumergroup }} ({{ topic }})"
    }
   ]
  },
  {
   "title": "Consumer group lag in ms",
   "type": "timeseries",
   "description": "Current approximate lag of a ConsumerGroup at Topic/Partition.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,consumergroup,topic) (\n  kafka_consumer_lag_millis{topic!=\"__consumer_offsets\",consumergroup!=\"\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}\n)",
     "legendFormat": "{{ consumergroup }} ({{ topic }})"
    }
   ]
  }
 ]
}