{
 "title": "Kafka overview",
 "tags": [ "kafka-integration" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesinpersec{job=\"integrations/kafka\"}, job)"
   },
   {
    "name": "kafka_cluster",
    "label": "Kafka_cluster",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesinpersec{job=\"integrations/kafka\",job=~\"$job\"}, kafka_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesinpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Active kafka controllers",
   "type": "stat",
   "description": "Active kafka controllers count.\n",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  kafka_controller_kafkacontroller_activecontrollercount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Active kafka controllers"
    }
   ]
  },
  {
   "title": "Brokers count",
   "type": "stat",
   "description": "Active brokers count.\n",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (job,kafka_cluster) (\n  kafka_server_kafkaserver_brokerstate{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Brokers count"
    }
   ]
  },
  {
   "title": "Unclean leader election",
   "type": "stat",
   "description": "Unclean leader election rate.\n",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (kafka_controller_controllerstats_uncleanleaderelectionspersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{kafka_cluster}}: Unclean leader election"
    }
   ]
  },
  {
   "title": "Preferred replica inbalance",
   "type": "stat",
   "description": "The count of topic partitions for which the leader is not the preferred leader.\n",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  kafka_controller_kafkacontroller_preferredreplicaimbalancecount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Preferred replica inbalance"
    }
   ]
  },
  {
   "title": "Cluster network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{kafka_cluster}}: Cluster bytes in"
    },
    {
     "expr": "sum by (job,kafka_cluster) (\n  rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{kafka_cluster}}: Cluster bytes out"
    }
   ]
  },
  {
   "title": "Cluster messages throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{kafka_cluster}}: Cluster messages in"
    }
   ]
  },
  {
   "title": "Online partitions",
   "type": "stat",
   "description": "Online partitions.\n",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  kafka_server_replicamanager_partitioncount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Online partitions"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "stat",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.\n",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  kafka_controller_kafkacontroller_offlinepartitionscount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Offline partitions"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "description": "Number of under replicated partitions (| ISR | < | all replicas |).\n",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  kafka_cluster_partition_underreplicated{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Under replicated partitions"
    }
   ]
  },
  {
   "title": "Under min ISR partitions",
   "type": "stat",
   "description": "Under min ISR(In-Sync replicas) partitions.\n",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster) (\n  kafka_cluster_partition_underminisr{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{kafka_cluster}}: Under min ISR partitions"
    }
   ]
  },
  {
   "title": "Current role",
   "type": "status-history",
   "description": "0 - follower, 1 - controller.\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  kafka_controller_kafkacontroller_activecontrollercount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}\n)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "clamp_max(zookeeper_leaderuptime{job=~\"integrations/kafka-zookeeper|integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}, 1) or clamp_max(zookeeper_numaliveconnections{job=~\"integrations/kafka-zookeeper|integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}, 0)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  kafka_server_kafkaserver_brokerstate{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 20 } },
  {
   "title": "Broker network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  rate(kafka_server_brokertopicmetrics_bytesinpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}: Broker bytes in"
    },
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  rate(kafka_server_brokertopicmetrics_bytesoutpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}: Broker bytes out"
    }
   ]
  },
  {
   "title": "Broker messages throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  rate(kafka_server_brokertopicmetrics_messagesinpersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}: Broker messages in"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 29 } },
  {
   "title": "Online partitions",
   "type": "timeseries",
   "description": "Online partitions.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  kafka_server_replicamanager_partitioncount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Online partitions"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "timeseries",
   "description": "Number of partitions that dont have an active leader and are hence not writable or readable.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  kafka_controller_kafkacontroller_offlinepartitionscount{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Offline partitions"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "timeseries",
   "description": "Number of under replicated partitions (| ISR | < | all replicas |).\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  kafka_cluster_partition_underreplicated{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Under replicated partitions"
    }
   ]
  },
  {
   "title": "Under min ISR partitions",
   "type": "timeseries",
   "description": "Under min ISR(In-Sync replicas) partitions.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (\n  kafka_cluster_partition_underminisr{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Under min ISR partitions"
    }
   ]
  },
  {
   "title": "ISR shrinks",
   "type": "timeseries",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static,\nthe only exceptions are when you are expanding your broker cluster or removing partitions.\nIn order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. \n\nA replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leaders offset\n(user-configurable by setting the replica.lag.max.messages configuration parameter),\nor it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason,\nan increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.\n\nThe Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (kafka_server_replicamanager_isrshrinkspersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: ISR shrinks"
    }
   ]
  },
  {
   "title": "ISR expands",
   "type": "timeseries",
   "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static,\nthe only exceptions are when you are expanding your broker cluster or removing partitions.\nIn order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. \n\nA replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leaders offset\n(user-configurable by setting the replica.lag.max.messages configuration parameter),\nor it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason,\nan increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.\n\nThe Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (job,kafka_cluster,instance) (kafka_server_replicamanager_isrexpandspersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: ISR expands"
    }
   ]
  },
  {
   "title": "Requests time breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer ($instance)",
     "type": "timeseries",
     "description": "Total time breakdown for producer requests.\nquantile: 0.95\n\n- `Request queue`: Time spent waiting in the request queue.\n- `Local time`: Time spent being processed by leader.\n- `Remote time`: Time spent waiting for follower response (only when 'require acks' is set).\n- `Response queue`: Time spent waiting in the response queue.\n- `Response time`: Time to send the response.\n\n",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_requestqueuetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Produce\"}\n)",
       "legendFormat": "request queue time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_localtimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Produce\"}\n)",
       "legendFormat": "local time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_remotetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Produce\"}\n)",
       "legendFormat": "remote time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_responsequeuetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Produce\"}\n)",
       "legendFormat": "response queue time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_responsesendtimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Produce\"}\n)",
       "legendFormat": "response time"
      }
     ]
    },
    {
     "title": "Fetch-follower ($instance)",
     "type": "timeseries",
     "description": "Total time breakdown for fetch-follower requests.\nquantile: 0.95\n\n- `Request queue`: Time spent waiting in the request queue.\n- `Local time`: Time spent being processed by leader.\n- `Remote time`: Time spent waiting for follower response (only when 'require acks' is set).\n- `Response queue`: Time spent waiting in the response queue.\n- `Response time`: Time to send the response.\n\n",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_requestqueuetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"FetchFollower\"}\n)",
       "legendFormat": "request queue time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_localtimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"FetchFollower\"}\n)",
       "legendFormat": "local time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_remotetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"FetchFollower\"}\n)",
       "legendFormat": "remote time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_responsequeuetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"FetchFollower\"}\n)",
       "legendFormat": "response queue time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_responsesendtimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"FetchFollower\"}\n)",
       "legendFormat": "response time"
      }
     ]
    },
    {
     "title": "Fetch-consumer ($instance)",
     "type": "timeseries",
     "description": "Total time breakdown for fetch requests.\nquantile: 0.95\n\n- `Request queue`: Time   spent waiting in the request queue.\n- `Local time`: Time spent being processed by leader.\n- `Remote time`: Time spent waiting for follower response (only when 'require acks' is set).\n- `Response queue`: Time spent waiting in the response queue.\n- `Response time`: Time to send the response.\n\n",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_requestqueuetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Fetch\"}\n)",
       "legendFormat": "request queue time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_localtimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Fetch\"}\n)",
       "legendFormat": "local time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_remotetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Fetch\"}\n)",
       "legendFormat": "remote time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_responsequeuetimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Fetch\"}\n)",
       "legendFormat": "response queue time"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_network_requestmetrics_responsesendtimems{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\", request=\"Fetch\"}\n)",
       "legendFormat": "response time"
      }
     ]
    }
   ]
  },
  {
   "title": "Message conversion",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message conversion (producer)",
     "type": "timeseries",
     "description": "The number of messages produced converted to match the log.message.format.version.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum by (job,kafka_cluster) (\n  rate(kafka_server_brokertopicmetrics_producemessageconversionspersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{kafka_cluster}}: Message conversion (producer)"
      }
     ]
    },
    {
     "title": "Message conversion (consumer)",
     "type": "timeseries",
     "description": "The number of messages consumed converted at consumer to match the log.message.format.version.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "sum by (job,kafka_cluster) (\n  rate(kafka_server_brokertopicmetrics_fetchmessageconversionspersec{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{kafka_cluster}}: Message conversion (consumer)"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper client",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zookeeper request latency",
     "type": "timeseries",
     "description": "Latency in millseconds for ZooKeeper requests from broker.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{instance}}: Zookeeper request latency"
      }
     ]
    },
    {
     "title": "Zookeeper connections",
     "type": "timeseries",
     "description": "Zookeeper connections rate.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  rate(kafka_server_sessionexpirelistener_zookeepersyncconnectspersec{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}}: Zookeeper connections"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  rate(kafka_server_sessionexpirelistener_zookeeperexpirespersec{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}}: Zookeeper expired connections"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  rate(kafka_server_sessionexpirelistener_zookeeperdisconnectspersec{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}}: Zookeeper disconnects"
      },
      {
       "expr": "avg by (job,kafka_cluster,instance) (\n  rate(kafka_server_sessionexpirelistener_zookeeperauthfailurespersec{quantile=\"0.95\",job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{instance}}: Zookeeper auth failures"
      }
     ]
    }
   ]
  },
  { "title": "Process overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 69 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Process start time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,instance) (\n  process_start_time_seconds{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} * 1000\n)",
     "legendFormat": "{{instance}}: Process start time"
    }
   ]
  },
  {
   "type": "text",
   "description": "Load average: Signal not found.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } }
  },
  {
   "title": "CPU usage (process)",
   "type": "timeseries",
   "description": "Process CPU usage.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,instance) (\n  rate(process_cpu_seconds_total{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}[$__rate_interval]) * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (process)"
    }
   ]
  },
  {
   "title": "Process memory used (rss)",
   "type": "timeseries",
   "description": "Process resident memory size in bytes.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,instance) (\n  process_resident_memory_bytes{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process memory used (rss)"
    }
   ]
  },
  {
   "title": "Process files open",
   "type": "timeseries",
   "description": "Process files opened.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "avg by (job,kafka_cluster,instance) (\n  process_open_fds{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files open"
    },
    {
     "expr": "avg by (job,kafka_cluster,instance) (\n  process_max_fds{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files max"
    }
   ]
  },
  {
   "title": "JVM overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used(heap)",
     "type": "stat",
     "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"heap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n))/(avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"heap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n))) * 100",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(heap)"
      }
     ]
    },
    {
     "title": "Memory used(nonheap)",
     "type": "stat",
     "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"nonheap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n))/(avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"nonheap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n))) * 100",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(nonheap)"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "description": "The current number of live threads including both daemon and non-daemon threads.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 83 },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster) (\n  jvm_threads_current{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads"
      }
     ]
    },
    {
     "title": "Classes loaded",
     "type": "stat",
     "description": "The number of classes that are currently loaded in the JVM.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster) (\n  jvm_classes_loaded{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Classes loaded"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM memory used(heap)",
     "type": "timeseries",
     "description": "The used space is the amount of memory that is currently occupied by Java objects.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"heap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(heap)"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"heap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory max(heap)"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_committed{area=\"heap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory committed(heap)"
      }
     ]
    },
    {
     "title": "JVM memory used(nonheap)",
     "type": "timeseries",
     "description": "The amount of memory that is currently in non-heap.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_used{area=\"nonheap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory used(nonheap)"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_max{area=\"nonheap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"} != -1)\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory max(nonheap)"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  sum without (id) (jvm_memory_bytes_committed{area=\"nonheap\", job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})\n)",
       "legendFormat": "{{kafka_cluster}}: JVM memory committed(nonheap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "The current number of live threads including both daemon and non-daemon threads.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "avg by (job,kafka_cluster) (\n  jvm_threads_current{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  jvm_threads_daemon{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads (daemon)"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  jvm_threads_peak{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads (peak)"
      },
      {
       "expr": "avg by (job,kafka_cluster) (\n  jvm_threads_deadlocked{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{kafka_cluster}}: Threads (deadlocked)"
      }
     ]
    },
    {
     "title": "Threads states",
     "type": "timeseries",
     "description": "Threads by current state.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
     "targets": [
      {
       "expr": "sum by (state, job,kafka_cluster) (jvm_threads_state{job=\"integrations/kafka\",job=~\"$job\",kafka_cluster=~\"$kafka_cluster\",instance=~\"$instance\"})",
       "legendFormat": "{{ state }}"
      }
     ]
    }
   ]
  }
 ]
}