{
 "title": "Springboot JVM overview",
 "tags": [
  "java",
  "jvm",
  "springboot",
  "micrometer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(jvm_memory_used_bytes{job!=\"\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{job!=\"\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "JVM overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Memory used(heap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    }
   ]
  },
  {
   "title": "Memory used(nonheap)",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"nonheap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"})\n))/(avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"nonheap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"} != -1)\n))) * 100",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_threads_live_threads{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "stat",
   "description": "The number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_classes_loaded_classes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Classes loaded"
    }
   ]
  },
  { "title": "Process overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job!=\"\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "Process start time",
   "type": "stat",
   "description": "Process start time.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_start_time_seconds{job!=\"\",job=~\"$job\",instance=~\"$instance\"} * 1000\n)",
     "legendFormat": "{{instance}}: Process start time"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "System's load average.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  system_load_average_1m{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Load average"
    },
    {
     "expr": "avg by (job,instance) (\n  system_cpu_count{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: CPU count"
    }
   ]
  },
  {
   "title": "CPU usage (process)",
   "type": "timeseries",
   "description": "Process CPU usage.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_cpu_usage{job!=\"\",job=~\"$job\",instance=~\"$instance\"} * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (process)"
    },
    {
     "expr": "avg by (job,instance) (\n  system_cpu_usage{job!=\"\",job=~\"$job\",instance=~\"$instance\"} * 100\n)",
     "legendFormat": "{{instance}}: CPU usage (system)"
    }
   ]
  },
  {
   "type": "text",
   "description": "Process memory used (rss): Signal not found.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } }
  },
  {
   "title": "Process files open",
   "type": "timeseries",
   "description": "Process files opened.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_files_open_files{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files open"
    },
    {
     "expr": "avg by (job,instance) (\n  process_files_max_files{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Process files max"
    }
   ]
  },
  { "title": "JVM memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "JVM memory used(heap)",
   "type": "timeseries",
   "description": "The used space is the amount of memory that is currently occupied by Java objects.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(heap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(heap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_committed_bytes{area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(heap)"
    }
   ]
  },
  {
   "title": "JVM memory used(nonheap)",
   "type": "timeseries",
   "description": "The amount of memory that is currently in non-heap.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_used_bytes{area=\"nonheap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory used(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_max_bytes{area=\"nonheap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"} != -1)\n)",
     "legendFormat": "{{job}}: JVM memory max(nonheap)"
    },
    {
     "expr": "avg by (job) (\n  sum without (id) (jvm_memory_committed_bytes{area=\"nonheap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"})\n)",
     "legendFormat": "{{job}}: JVM memory committed(nonheap)"
    }
   ]
  },
  { "title": "JVM garbage collection", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Eden Space (used)",
   "type": "timeseries",
   "description": "Memory used for G1 Eden Space Collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_used_bytes{id=~\"(G1 |PS )?Eden Space\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_max_bytes{id=~\"(G1 )?Eden Space\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\n != -1",
     "legendFormat": "{{job}}: Eden Space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed_bytes{id=~\"(G1 |PS )?Eden Space\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Eden Space (committed)"
    }
   ]
  },
  {
   "title": "Survival space (used)",
   "type": "timeseries",
   "description": "Memory used for Survival collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_used_bytes{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (used)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_max_bytes{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"} != -1\n)",
     "legendFormat": "{{job}}: Survival space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed_bytes{id=~\"(G1 |PS )?Survivor Space\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Survival space (committed)"
    }
   ]
  },
  {
   "title": "Tenured space (used)",
   "type": "timeseries",
   "description": "Memory used for Tenured(Old Gen) collection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_memory_used_bytes{id=\"Tenured Gen\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (used)"
    },
    {
     "expr": "\n  avg by (job) (\n  jvm_memory_max_bytes{id=\"Tenured Gen\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\n != -1",
     "legendFormat": "{{job}}: Tenured space (max)"
    },
    {
     "expr": "avg by (job) (\n  jvm_memory_committed_bytes{id=\"Tenured Gen\", area=\"heap\", job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Tenured space (committed)"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(\n  avg by (job,action,cause) (\n  rate(jvm_gc_pause_seconds_count{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "description": "Major and minor garbage collections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(\n  avg by (job, action, cause) (\n  rate(jvm_gc_pause_seconds_sum{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n  /\n  rate(jvm_gc_pause_seconds_count{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{ job }}: {{ action }} ({{ cause }}) (avg)"
    },
    {
     "expr": "label_replace(\n  avg by (action,cause, job) (rate(jvm_gc_pause_seconds_max{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n, \"action\", \"$1\", \"action\", \"end of (.+)\")",
     "legendFormat": "{{ job }}: {{ action }} ({{ cause }}) (max)"
    }
   ]
  },
  {
   "title": "Allocated/promoted",
   "type": "timeseries",
   "description": "'Allocated' is the size increase of the young generation memory pool after one GC and before the next. It reflects minor GC.\n'Promoted' is the size increase of the old generation memory pool after GC. It reflects full GC.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  rate(jvm_gc_memory_allocated_bytes_total{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Allocated (bytes)"
    },
    {
     "expr": "avg by (job) (\n  rate(jvm_gc_memory_promoted_bytes_total{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}: Promoted"
    }
   ]
  },
  { "title": "JVM threads", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "The current number of live threads including both daemon and non-daemon threads.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_threads_live_threads{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_daemon_threads{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (daemon)"
    },
    {
     "expr": "avg by (job) (\n  jvm_threads_peak_threads{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Threads (peak)"
    }
   ]
  },
  {
   "title": "Threads states",
   "type": "timeseries",
   "description": "Threads by current state.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by (state, job) (jvm_threads_states_threads{job!=\"\",job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "JVM buffers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 53 } },
  {
   "title": "Direct buffer used bytes",
   "type": "timeseries",
   "description": "Direct buffer is allocated outside the Java heap and represents the OS native memory used by the JVM process. It is generally used for I/O operations. Note that direct buffers aren't freed up by GC.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_memory_used_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer used bytes"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_total_capacity_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Direct buffer capacity"
    }
   ]
  },
  {
   "title": "Mapped buffer used",
   "type": "timeseries",
   "description": "The mapped buffer pool is used for its FileChannel instances.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job) (\n  jvm_buffer_memory_used_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer used"
    },
    {
     "expr": "avg by (job) (\n  jvm_buffer_total_capacity_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{job}}: Mapped buffer capacity"
    }
   ]
  },
  {
   "title": "Hikari pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "stat",
     "description": "Hikari pool connections",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{pool}}: Connections"
      }
     ]
    },
    {
     "title": "Connections timeouts",
     "type": "stat",
     "description": "Hikari pool timeouts",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 63 },
     "targets": [
      {
       "expr": "avg by (job,pool) (\n  rate(hikaricp_connections_timeout_total{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
       "legendFormat": "{{pool}}: Connections timeouts"
      }
     ]
    },
    {
     "title": "Connections (active) ",
     "type": "timeseries",
     "description": "Hikari pool active connections.",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 63 },
     "targets": [
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections_active{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{pool}}: Connections (active) "
      },
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections_idle{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{pool}}: Connections (idle) "
      },
      {
       "expr": "avg by (job,pool) (\n  hikaricp_connections_pending{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
       "legendFormat": "{{pool}}: Connections (pending) "
      }
     ]
    },
    {
     "title": "Connection create duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n/rate(hikaricp_connections_creation_seconds_count{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
       "legendFormat": "{{pool}}: Connections creation time (avg)"
      }
     ]
    },
    {
     "title": "Connection create duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n/rate(hikaricp_connections_usage_seconds_count{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
       "legendFormat": "{{pool}}: Connections usage time (avg)"
      }
     ]
    },
    {
     "title": "Connection acquire duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n/rate(hikaricp_connections_acquire_seconds_count{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n",
       "legendFormat": "{{pool}}: Connections acquire time (avg)"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logback events",
     "type": "timeseries",
     "description": "Logback events.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "topk(10,\n  sum by (job,level) (\n  rate(logback_events_total{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n[$__rate_interval])\n)\n)",
       "legendFormat": "{{level}}: Logback events"
      }
     ]
    }
   ]
  }
 ]
}