{
 "title": "Varnish overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(varnish_main_sessions,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(varnish_main_sessions,instance)"
    }
   },
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Cache hit pass",
   "type": "stat",
   "description": "Number of cache hits for pass objects.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_cache_hitpass{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Session queue length",
   "type": "stat",
   "description": "Length of session queue waiting for threads.",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_thread_queue_len{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "description": "Number of thread pools.",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_pools{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Backend connections",
   "type": "timeseries",
   "description": "Number of recycled, reused, busy, unhealthy, and accepted backend connections by Varnish Cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_backend_conn{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Accepted"
    },
    {
     "expr": "increase(varnish_main_backend_recycle{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Recycled"
    },
    {
     "expr": "increase(varnish_main_backend_reuse{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Reused"
    },
    {
     "expr": "increase(varnish_main_backend_busy{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Busy"
    },
    {
     "expr": "increase(varnish_main_backend_unhealthy{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Unhealthy"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Number of connected, queued, and dropped sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",instance=~\"$instance\",type=\"conn\"}[$__interval:])",
     "legendFormat": "{{instance}} - Connected"
    },
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",instance=~\"$instance\",type=\"queued\"}[$__interval:])",
     "legendFormat": "{{instance}} - Queued"
    },
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",instance=~\"$instance\",type=\"dropped\"}[$__interval:])",
     "legendFormat": "{{instance}} - Dropped"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of client and backend requests received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_client_req{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Client"
    },
    {
     "expr": "increase(varnish_main_backend_req{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Backend"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "Ratio of cache hits to cache misses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__interval:]) / clamp_min((increase(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__interval:]) + increase(varnish_main_cache_miss{job=~\"$job\",instance=~\"$instance\"}[$__interval:])),1) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of failed, created, limited, and current threads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_threads_failed{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Failed"
    },
    {
     "expr": "increase(varnish_main_threads_created{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Created"
    },
    {
     "expr": "increase(varnish_main_threads_limited{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Limited"
    },
    {
     "expr": "varnish_main_threads{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Total"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "description": "Number of expired, LRU nuked objects, and current cache storage used in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(varnish_main_n_expired{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Expired"
    },
    {
     "expr": "increase(varnish_main_n_lru_nuked{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Nuked"
    },
    {
     "expr": "varnish_sma_g_bytes{job=~\"$job\",instance=~\"$instance\",type=\"s0\"}",
     "legendFormat": "{{instance}} - Used memory"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Response bytes of header and body for client and backends.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(varnish_main_s_resp_hdrbytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Client header"
    },
    {
     "expr": "increase(varnish_main_s_resp_bodybytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Client body"
    },
    {
     "expr": "increase(varnish_backend_beresp_hdrbytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Backend header"
    },
    {
     "expr": "increase(varnish_backend_beresp_bodybytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Backend body"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Client logs",
   "type": "logs",
   "description": "Client logs for Varnish Cache.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/varnish/varnishncsa.log\", job=~\"$job\", instance=~\"$instance\"} |= ``"
    }
   ]
  },
  {
   "title": "Backend logs",
   "type": "logs",
   "description": "Backend logs for Varnish Cache.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/varnish/varnishncsa-backend.log\", job=~\"$job\", instance=~\"$instance\"} |= ``"
    }
   ]
  }
 ]
}