{
 "title": "Varnish overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(varnish_main_sessions,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(varnish_main_sessions,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache hit rate",
   "type": "gauge",
   "description": "Rate of cache hits to misses.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + rate(varnish_main_cache_miss{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]), 1))) * 100\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend requests",
   "type": "stat",
   "description": "The rate of requests sent to the Varnish Cache frontend.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{nstance}}"
    }
   ]
  },
  {
   "title": "Backend requests",
   "type": "stat",
   "description": "The rate of requests sent to the Varnish Cache backends.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_backend_req{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "description": "The rate of total sessions created in the Varnish Cache instance.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_sessions_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "stat",
   "description": "The rate of cache hits.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend up and down",
   "type": "stat",
   "description": "Number of Varnish Cache backends that are up/down.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(count(varnish_backend_up{job=~\"$job\", instance=~\"$instance\"} == 1))",
     "legendFormat": "{{instance}} Up"
    },
    {
     "expr": "scalar(count(varnish_backend_up{job=~\"$job\", instance=~\"$instance\"} == 0))",
     "legendFormat": "{{instance}} Down"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "description": "Number of thread pools.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_pools{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hit pass",
   "type": "stat",
   "description": "Rate of cache hits for pass objects (fulfilled requests that are not cached).",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_cache_hitpass{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Backend connections",
   "type": "timeseries",
   "description": "Number of recycled, reused, busy, unhealthy, and accepted backend connections by Varnish Cache.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_backend_conn{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Accepted"
    },
    {
     "expr": "increase(varnish_main_backend_recycle{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Recycled"
    },
    {
     "expr": "increase(varnish_main_backend_reuse{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Reused"
    },
    {
     "expr": "increase(varnish_main_backend_busy{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Busy"
    },
    {
     "expr": "increase(varnish_main_backend_unhealthy{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Unhealthy"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Number of new connected, queued, and dropped sessions.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",instance=~\"$instance\",type=\"conn\"}[$__interval:])",
     "legendFormat": "{{instance}} - Connected"
    },
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",instance=~\"$instance\",type=\"queued\"}[$__interval:])",
     "legendFormat": "{{instance}} - Queued"
    },
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",instance=~\"$instance\",type=\"dropped\"}[$__interval:])",
     "legendFormat": "{{instance}} - Dropped"
    }
   ]
  },
  {
   "title": "Session queue length",
   "type": "stat",
   "description": "Length of session queue waiting for threads.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_main_thread_queue_len{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "Bytes allocated from Varnish Cache storage.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "varnish_sma_g_bytes{job=~\"$job\",instance=~\"$instance\",type=\"s0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "description": "Number of expired, LRU nuked objects, and current cache storage used in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "increase(varnish_main_n_expired{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Expired"
    },
    {
     "expr": "increase(varnish_main_n_lru_nuked{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Nuked"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of client and backend requests received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_client_req{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Frontend"
    },
    {
     "expr": "increase(varnish_main_backend_req{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Backend"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "Ratio of cache hits to cache misses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance, job) ((rate(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(varnish_main_cache_hit{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + rate(varnish_main_cache_miss{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]), 1))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Response bytes of header and body for client and backends.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(varnish_main_s_resp_hdrbytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} -  Frontend header"
    },
    {
     "expr": "increase(varnish_main_s_resp_bodybytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Frontend body"
    },
    {
     "expr": "increase(varnish_backend_beresp_hdrbytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} -  {{backend}} - Backend header"
    },
    {
     "expr": "increase(varnish_backend_beresp_bodybytes{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} -  {{backend}} - Backend body"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of failed, created, limited, and current threads.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_threads_failed{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Failed"
    },
    {
     "expr": "increase(varnish_main_threads_created{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Created"
    },
    {
     "expr": "increase(varnish_main_threads_limited{job=~\"$job\",instance=~\"$instance\"}[$__interval:])",
     "legendFormat": "{{instance}} - Limited"
    },
    {
     "expr": "varnish_main_threads{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Total"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Frontend logs",
   "type": "logs",
   "description": "Client logs for Varnish Cache.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/varnish/varnishncsa.log\", job=~\"$job\", instance=~\"$instance\"} |= ``"
    }
   ]
  },
  {
   "title": "Backend logs",
   "type": "logs",
   "description": "Backend logs for Varnish Cache.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/varnish/varnishncsa-backend.log\", job=~\"$job\", instance=~\"$instance\"} |= ``"
    }
   ]
  }
 ]
}