{
 "title": "Windows Active Directory overview",
 "tags": [ "windows" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(windows_ad_directory_service_threads{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(windows_ad_directory_service_threads{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Replication pending operations",
   "type": "stat",
   "description": "The number of replication operations that are pending in Active Directory.\nThese operations could include a variety of tasks, such as updating directory objects, processing changes made on other domain controllers, or applying new schema updates.\n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  windows_ad_replication_pending_operations{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "Pending operations"
    }
   ]
  },
  {
   "title": "Directory service threads",
   "type": "stat",
   "description": "The current number of active threads in the directory service.\n",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  windows_ad_directory_service_threads{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "Directory service threads"
    }
   ]
  },
  {
   "title": "Windows Active Directory alerts",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "Replication pending synchronizations",
   "type": "stat",
   "description": "The number of synchronization requests that are pending in Active Directory. Synchronization in AD refers to the process of ensuring that changes (like updates to user accounts, group policies, etc.) are consistently applied across all domain controllers.\n",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  windows_ad_replication_pending_synchronizations{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "Pending syncs"
    }
   ]
  },
  {
   "title": "LDAP bind requests",
   "type": "timeseries",
   "description": "The rate at which LDAP bind requests are being made.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_ad_binds_total{bind_method=~\"ldap\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LDAP operations",
   "type": "timeseries",
   "description": "The rate of LDAP read, search, and write operations.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_ad_directory_operations_total{origin=~\"ldap\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Bind operations overview",
   "type": "table",
   "description": "Distribution of different types of operations performed on the Active Directory database.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(windows_ad_binds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Intrasite replication traffic",
   "type": "timeseries",
   "description": "Rate of replication traffic between servers within the same site.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(windows_ad_replication_data_intrasite_bytes_total{job=~\"$job\",instance=~\"$instance\"} * 8[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ direction }}"
    }
   ]
  },
  {
   "title": "Intersite replication traffic",
   "type": "timeseries",
   "description": "Rate of replication traffic between servers across different sites.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(windows_ad_replication_data_intersite_bytes_total{job=~\"$job\",instance=~\"$instance\"} * 8[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ direction }}"
    }
   ]
  },
  {
   "title": "Inbound replication updates",
   "type": "timeseries",
   "description": "The rate of traffic received from other replication partners.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(windows_ad_replication_inbound_objects_updated_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: Object updates"
    },
    {
     "expr": "rate(windows_ad_replication_inbound_properties_updated_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: Property updates"
    }
   ]
  },
  {
   "title": "Database operations overview",
   "type": "table",
   "description": "Distribution of different types of operations performed on the Active Directory database.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(windows_ad_database_operations_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Database operations",
   "type": "timeseries",
   "description": "The rate of database operations.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_ad_database_operations_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ operation }}"
    }
   ]
  }
 ]
}