{
 "title": "Asterisk - Overview",
 "tags": [ "asterisk-integration" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(asterisk_core_uptime_seconds, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(asterisk_core_uptime_seconds{job =~ \"$job\"}, instance)"
    }
   },
   {
    "name": "eid",
    "label": "EID",
    "query": {
     "query": "label_values(asterisk_core_uptime_seconds{job =~ \"$job\", instance =~ \"$instance\"}, eid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Asterisk Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": {
    "content": "<img style=\"margin: 20px;\" src=\"https://storage.googleapis.com/grafanalabs-integration-logos/asterisk.png\">"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Asterisk Uptime",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_uptime_seconds{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Last Reload",
   "type": "stat",
   "description": "Time elapsed since last reload",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_last_reload_seconds{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Total Calls",
   "type": "stat",
   "description": "Calls count since last restart",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_calls_sum{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Current Active Calls",
   "type": "stat",
   "description": "Active current calls",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Max Active Calls",
   "type": "stat",
   "description": "Max active calls",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Calls per Second",
   "type": "stat",
   "description": "Calls per second arriving in the system",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(asterisk_calls_sum{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Active Calls",
   "type": "timeseries",
   "description": "Active calls in the system over the selected time interval",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "asterisk_calls_count{instance=~\"$instance\", job=~\"$job\", eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Current Active Channels",
   "type": "gauge",
   "description": "Current active channels on Asterisk",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_channels_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Max Active Channels",
   "type": "stat",
   "description": "Current active channels on Asterisk",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "asterisk_channels_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Current Active Endpoints",
   "type": "gauge",
   "description": "Current active endpoints on Asterisk",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_endpoints_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Max Active Endpoints",
   "type": "stat",
   "description": "Current active endpoints on Asterisk",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_endpoints_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Current Active Bridges",
   "type": "gauge",
   "description": "Current active bridges on Asterisk",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_bridges_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Max Active Bridges",
   "type": "stat",
   "description": "Current active bridges on Asterisk",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_bridges_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
    }
   ]
  },
  {
   "title": "Channels Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Channels",
     "type": "timeseries",
     "description": "Current active channels on Asterisk",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "asterisk_channels_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    },
    {
     "title": "Channels Details",
     "type": "table",
     "description": "Details of channels in the instance",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "asterisk_channels_state{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      },
      {
       "expr": "asterisk_channels_duration_seconds{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoints Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Endpoints",
     "type": "timeseries",
     "description": "Current active endpoints on Asterisk",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "asterisk_endpoints_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    },
    {
     "title": "Endpoints Details",
     "type": "table",
     "description": "Information regarding channels in the instance",
     "gridPos": { "h": 10, "w": 15, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "asterisk_endpoints_channels_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bridges Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Bridges",
     "type": "timeseries",
     "description": "Current active bridges on Asterisk",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "asterisk_bridges_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    },
    {
     "title": "Bridges Details",
     "type": "table",
     "description": "Information regarding bridges in the instance",
     "gridPos": { "h": 9, "w": 15, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "asterisk_bridges_channels_count{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Asterisk System Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asterisk System Information",
     "type": "table",
     "description": "**Core properties** This table shows core properties of the Asterisk instance reported by embedded prometheus exporter",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "asterisk_core_properties{instance=~\"$instance\",job=~\"$job\",eid=~\"$eid\"}"
      }
     ]
    }
   ]
  }
 ]
}