{
 "title": "Cilium / Components / Actionable",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [ "cilium-agent" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Informer Events TODO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "topk($k, sum(irate(cilium_kubernetes_events_received_total[$__rate_interval])) by (scope, action))",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "Endpoint Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "endpoints" } },
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{}) by (endpoint_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{endpoint_state=\"invalid\"}) by (pod, endpoint_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Policy Denied Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(cilium_operator_ipam_ips{type=\"available\"}) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Non Policy Denied Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{}[$__rate_interval])) by (reason)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Policy Denied Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{}[$__rate_interval])) by (reason) > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Denied Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{reason=\"Policy denied\"}[$__rate_interval])) by (reason) > 0\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}